'use strict';const EXPIRED_AFTER_21_DAYS=30240,loadSystemUserLoginSession=function(){LeoAdminApiUtil.callPostApi(baseLeoAdminUrl+"/user/login-session",{},function(c){0===c.httpCode&&""===c.errorMessage?(loginFormHandler(c.data.userSession),c="data:image/png;base64,"+c.data.captchaImage,$("#captcha_img").show().attr("src",c),$("#system_user_login_loader").hide(),$("#system_user_login_div").show()):LeoAdminApiUtil.logErrorPayload(c)})},loginFormHandler=function(c){var b=function(){var a=baseLeoAdminUrl+
"/user/check-login",e=$("#username").val(),d=$("#password").val(),g=$("#captcha").val();e={userlogin:e,userpass:d,usersession:c,captcha:g};$("#info-login").html("\x3cb\x3eSending data ...\x3c/b\x3e").show();LeoAdminApiUtil.callPostApi(a,e,function(h){if(""===h.errorMessage){var k=h.data;lscache.set("usersession",c,EXPIRED_AFTER_21_DAYS);lscache.set("encryptionkey",k,EXPIRED_AFTER_21_DAYS);$("#system_user_login_form, #btn_system_login").hide();$("#info-login").html('\x3ci class\x3d"fa fa-check-circle fa-2" aria-hidden\x3d"true"\x3e\x3c/i\x3e \x3cb\x3e Login successfully ! \x3c/b\x3e ');
setTimeout(function(){window.location.reload(!0)},2500)}else $("#info-login").hide(),$("#error-login").html('\x3ci class\x3d"fa fa-exclamation-circle" aria-hidden\x3d"true"\x3e\x3c/i\x3e '+h.errorMessage).show().delay(3E3).fadeOut(),setTimeout(function(){LeoAdminApiUtil.logErrorPayload(h)},2500)})};$("#btn_system_login").click(b);$("#username").on("keyup",function(a){13===a.keyCode&&$("#password").focus()});$("#password").on("keyup",function(a){13===a.keyCode&&$("#captcha").focus()});$("#captcha").on("keyup",
function(a){13===a.keyCode&&b()})},initSystemUserLogin=function(){$("#login_logo").attr("src",window.pageHeaderLogo).show();var c=lscache.get("usersession"),b=lscache.get("encryptionkey");"string"===typeof c&&"string"===typeof b?console.log("You login OK with session "+c):(loadSystemUserLoginSession(),console.log("loadSystemUserLoginSession is called "))},loadSystemEventsTable=function(c,b,a,e,d,g,h){var k=getUserSession();if(k){c=_.template($("#system-event-table-tpl").html())({eventObjectName:c});
$("#"+b).empty().html(c);var n=[{data:"createdAt"},{data:"action"},{data:"accessIp"},{data:"userAgent"},{data:"data"}];h="object"===typeof h?h:[20,30,40];return $("#system_event_table").DataTable({lengthMenu:[h,h],lengthChange:1<h.length?!0:!1,processing:!0,serverSide:!0,searching:!1,search:{return:!1},ordering:!0,serverMethod:"POST",ajax:{url:baseLeoAdminUrl+"/cdp/system-control/action-logs",contentType:"application/json",beforeSend:function(f){$("#system_event_loader").show();$("#system_event_list").hide();
f.setRequestHeader("leouss",k)},data:function(f){f.objectName=a;f.objectId=e;f.action="";f.accessIp="";f.requestUserLogin=d;var l=f.order[0];f.sortField=n[l.column].data;f.sortAsc="asc"===l.dir;f.searchValue=f.search.value;delete f.order;delete f.search;return JSON.stringify(f)},dataSrc:function(f){var l=f.canInsertData,m=f.canEditData,p=f.canDeleteData;$("#system_event_table").data("canInsertData",l);$("#system_event_table").data("canEditData",m);$("#system_event_table").data("canDeleteData",p);
$("#system_event_loader").hide();$("#system_event_list").show();"function"===typeof g&&g();return f.data}},columnDefs:[{render:function(f,l,m){return'\x3cdiv class\x3d"text-center" style\x3d"color:#3300ff; width:78px; margin: auto;" \x3e\x3cmark\x3e'+moment.utc(f).local().format("YYYY-MM-DD HH:mm:ss")+"\x3c/mark\x3e\x3c/div\x3e"},targets:0},{render:function(f,l,m){return'\x3cdiv style\x3d"font-size:0.9em; width:180px; text-align:center; margin: auto;word-wrap: break-word;" \x3e\x3cmark\x3e'+f+"\x3c/mark\x3e\x3c/div\x3e"},
targets:1,orderable:!1},{render:function(f,l,m){return'\x3cdiv style\x3d"font-size:0.9em; text-align:center; margin: auto; word-wrap: break-word;"\x3e\x3cmark\x3e'+f+"\x3c/mark\x3e\x3c/div\x3e"},targets:2,orderable:!1},{render:function(f,l,m){return'\x3cdiv style\x3d"font-size:0.8em; text-align:center; width:260px; margin: auto; word-wrap: break-word;" \x3e'+f+"\x3c/div\x3e"},targets:3,orderable:!1},{render:function(f,l,m){return'\x3cdiv style\x3d"font-size:0.78em; word-wrap: break-word; width:400px; margin: auto;" \x3e'+
textTruncate(f,300)+"\x3c/div\x3e"},targets:4,orderable:!1}],columns:n,order:[[0,"desc"]]})}},loadSystemEventsFromLoginUser=function(c){return loadSystemEventsTable("User Login","panel_login_account_view_logs","SystemUser","",c)};
var loadSystemInfoConfigs=function(){LeoAdminApiUtil.getSecuredData("/cdp/system-config/list-all",{},function(c){var b=$("#configs_holder");_.forEach(c.data,function(a,e){e=a.id;systemConfigMap[e]=a;a.disabledText=a.configs.read_only?"disabled":"";a.enterpriseEditionText=a.configs.active?"":"(only available in the Enterprise edition)";a.service_api_key=a.configs.service_api_key&&""!=a.configs.service_api_key?a.configs.service_api_key.substr(0,5)+"...":"";if(!0===a.configs.show){var d=_.template($("#tpl_system_config_box").html());
b.append(d(a));$("#header_"+e+"_true").css("color","#0000CD");"local-system"===a.configs.service_api_url&&($("#"+e+"_buttons_div").find("button").attr("disabled","disabled"),$("#"+e+"_api_key_div").css("visibility","hidden"));$("#"+e+"_api_key").focus(function(){$(this).val("")});1===a.status&&$("#"+e+"_api_key_label").html('\x3ci class\x3d"fa fa-check" aria-hidden\x3d"true"\x3e\x3c/i\x3e API Key is ready').addClass("config_ready")}});b.find("div.active_false button").attr("class","btn btn-default").attr("disabled",
"disabled");b.find("div.panel_active_false").find("input").attr("disabled","disabled");b.find("i.config_description").tooltip();c=_.map(systemConfigMap.profile_data_fields.coreFieldConfigs,function(a,e){return 0<a.dataQualityScore?(a.coreAttribute=!0,a):!1});c=_.filter(c,function(a){return!1!==a});c=_.sortBy(c,[function(a){return a.identityResolution?1E3*a.dataQualityScore:a.dataQualityScore}]).reverse();$("#profileAttributeCount").text(c.length);renderProfileMetaDataTable(c)})};
function renderProfileMetaDataTable(c){$("#profile_metadata_table").jsGrid({data:c,width:"100%",height:"auto",inserting:!1,editing:!0,sorting:!0,paging:!1,confirmDeleting:!0,deleteConfirm:function(b){return b.coreAttribute?"The attribute \x3cb\x3e["+b.attributeName+"]\x3c/b\x3e is the \x3cb\x3eattribute of system\x3c/b\x3e. You can not delete this attribute.":"The attribute ["+b.attributeName+"] will be removed. Are you sure ? "},onItemInserting:function(b){},onItemInserted:function(b){},onItemEditing:function(b){},
onItemUpdated:function(b){var a=b.item;console.log(a);b=systemConfigMap.profile_data_fields;var e=b.coreFieldConfigs[a.attributeName];e&&(e.dataQualityScore=a.dataQualityScore,b={objectJson:JSON.stringify(b)},LeoAdminApiUtil.callPostAdminApi("/cdp/system-config/save",b,function(d){0===d.httpCode&&""===d.errorMessage?notifySuccessMessage("The attribute \x3cb\x3e["+a.attributeName+"]\x3c/b\x3e is saved successfully !"):LeoAdminApiUtil.logErrorPayload(d)}))},onItemDeleting:function(b){},onRefreshed:function(b){},
fields:[{name:"identityResolution",title:"Identity Resolution Key",align:"center",type:"CustomCheckBox",width:64,sorter:"string",editTemplate:function(b){return'\x3cdiv class\x3d"text-center"\x3e'+getCheckedBoxIcon(b)+"\x3c/div\x3e"}},{name:"attributeName",title:"Attribute Name",align:"center",type:"text",validate:"required",validate:"required",editing:!1},{name:"label",title:"Label",align:"center",type:"text",validate:"required",width:120,editing:!1},{name:"type",title:"Data Type",align:"center",
type:"text",validate:"required",editing:!1,itemTemplate:function(b,a){a=b.lastIndexOf(".")+1;b=0<a?b.substr(a):b;return'\x3cdiv class\x3d"profile_field_type"\x3e '+b+" \x3c/div\x3e"}},{name:"dataQualityScore",title:"Data Quality Score",type:"number",align:"center",width:76,validate:"required",itemTemplate:function(b,a){return 0<b?'\x3cdiv class\x3d"highlight_text positive_dqs"\x3e '+b+" \x3c/div\x3e":0>b?'\x3cdiv class\x3d"highlight_text negative_dqs"\x3e '+b+" \x3c/div\x3e":b}},{name:"synchronizable",
title:"Synchronizable ",align:"center",type:"CustomCheckBox",width:64,validate:"required",sorter:"string"},{title:"Controls",type:"control",width:80,editButton:!0,deleteButton:!1,itemTemplate:function(b,a){jsGrid.fields.control.prototype.itemTemplate.apply(this,arguments);var e=a.coreAttribute,d=a.attributeName;var g="Edit Event Name: "+d;$("\x3cbutton\x3e").data("attributeName",d).attr({class:"jsgrid-custom-button",title:g}).html('\x3ci class\x3d"fa fa-cogs event-set-rules" style\x3d"" aria-hidden\x3d"true"\x3e\x3c/i\x3e').click(function(k){console.log("setRules button ",
$(this).data("attributeName"));underDevelopment(this);k.stopPropagation()});var h="customGridEditbutton jsgrid-button jsgrid-edit-button";g=$("\x3cbutton\x3e").data("attributeName",d).attr({class:h,title:"Edit Attribute"}).click(function(k){console.log("Edit button ",$(this).data("attributeName"))});h="customGridDeletebutton jsgrid-button jsgrid-delete-button";d=$("\x3cbutton\x3e").data("attributeName",d).attr({class:h,title:"Delete Attribute"}).click(function(k){var n=$(this).data("attributeName");
e?notifyErrorMessage("The attribute \x3cb\x3e["+n+"]\x3c/b\x3e is the \x3cb\x3eattribute of system\x3c/b\x3e. You can not delete this attribute."):deleteEventMetricMetaData(n);k.stopPropagation()});h=$("\x3cdiv\x3e");e?h.attr("title","The attribute of system"):(h.addClass("editable_profile_attribute"),h.attr("title","Click to edit or delete"));h.append(g).append(d);return h}}]})}
function callDataQualityComputeJob(){LeoAdminApiUtil.callPostAdminApi("/cdp/system-config/call-data-quality-compute-job",{},function(c){0===c.httpCode&&""===c.errorMessage?iziToast.success({title:"Information Box",message:"\x3cb\x3eCall Data Quality Compute Job\x3c/b\x3e is called successfully!"}):LeoAdminApiUtil.logErrorPayload(c)})}
function deleteSystemServiceInfo(c){var b=systemConfigMap[c];_.forOwn(b.configs,function(d,g){"string"!==typeof d||0!==g.indexOf("smtp_")&&0!==g.indexOf("service_")||(b.configs[g]="")});$("#"+c+"_api_key").val("");$("#"+c+"_api_url").val("");b.status=0;var a=function(d){null!=d?(iziToast.success({title:"System Config",message:"The config of \x3cb\x3e"+b.name+"\x3c/b\x3e is reset OK!",timeout:3E3}),$("#"+c+"_api_key").val(""),$("#"+c+"_api_key_label").html("API Key").removeClass("config_ready")):console.error("saveSystemServiceInfo ",
d)},e={objectJson:JSON.stringify(b)};LeoAdminApiUtil.callPostAdminApi("/cdp/system-config/save",e,function(d){0===d.httpCode&&""===d.errorMessage?a(d.data):LeoAdminApiUtil.logErrorPayload(d)},a)}
function saveSystemServiceInfo(c){var b=$(c).data("id"),a=systemConfigMap[b],e={};$("#"+b+"_api_key").val().trim();$("#systemServiceConfigList input").each(function(){var g=$(this).attr("name"),h=$(this).attr("type");e[g]="number"===h?parseInt($(this).val()):"checkbox"===h?$(this).prop("checked"):$(this).val()});a.configs=e;a.status=a.configs.service_api_key&&""!=a.configs.service_api_key?1:0;c={objectJson:JSON.stringify(a)};var d=function(g){if(null!=g){$("#dialogSetSystemConfigs").modal("hide");
iziToast.success({title:"System Config",message:"The config of \x3cb\x3e"+a.name+"\x3c/b\x3e is saved OK!",timeout:3E3});g=e.service_api_key.substr(0,5)+"...";var h=e.service_api_url;$("#"+b+"_api_key").val(g);$("#"+b+"_api_url").val(h);1===a.status&&$("#"+b+"_api_key_label").html('\x3ci class\x3d"fa fa-check" aria-hidden\x3d"true"\x3e\x3c/i\x3e API Key is ready').addClass("config_ready")}else console.error("saveSystemServiceInfo ",g)};LeoAdminApiUtil.callPostAdminApi("/cdp/system-config/save",c,
function(g){0===g.httpCode&&""===g.errorMessage?d(g.data):LeoAdminApiUtil.logErrorPayload(g)},d)}
function setSystemServiceInfo(c){var b=systemConfigMap[c];$("#dialogSetSystemConfigs").modal({backdrop:"static",keyboard:!1});$("#systemServiceName").text(b.name);$("#systemServiceDescription").text(b.description);$("#systemServiceSaveButton").data("id",c);var a=$("#systemServiceConfigList");a.empty();_.forOwn(b.configs,function(e,d){var g={inputName:d};g.inputType="number"===typeof e?"number":"boolean"===typeof e?"checkbox":"text";var h=_.template($("#tpl_config_row_item").html());a.append(h(g));
"checkbox"===g.inputType?a.find('input[name\x3d"'+d+'"]').prop("checked",e):a.find('input[name\x3d"'+d+'"]').val(e);if(0===d.indexOf("service")||0===d.indexOf("smtp_"))a.find('input[name\x3d"'+d+'"]').prop("disabled",!1),$("#config_label_"+d).addClass("highlight_text")})};