'use strict';const refreshSegmentDetails=function(){segmentDataModel&&(location.hash="#calljs-leoCdpRouter('Segment_Details','"+segmentDataModel.id+"','_refresh_"+(new Date).getTime()+"')")},loadSegmentData=function(b){LeoAdminApiUtil.callPostAdminApi(baseLeoAdminUrl+"/cdp/segment/load",{id:b},function(a){if(0===a.httpCode&&""===a.errorMessage){var c=a.data.behavioralEventMap,d=a.data.assetGroups,f=a.data.touchpointHubs;segmentDataModel=a.data.segmentData;segmentDataStats=a.data.segmentStats;var e=
segmentDataModel.managedBySystem,g=JSON.parse(segmentDataModel.jsonQueryRules);e?($("button.data-control-delete").attr("disabled","disabled"),$("button.data-control-delete").attr("title","Can not delete this segment, which is managed by system")):a.canDeleteData?$("button.data-control-delete").click(deleteSegment):$("button.data-control-delete").attr("disabled","disabled");a.canEditData?$("button.data-control-edit").click(function(){location.hash="calljs-leoCdpRouter('Segment_Builder','"+b+"')"}):
$("button.data-control-edit").attr("disabled","disabled");$("#segment_details_loader").hide();$("#segment_details_div").show();loadSegmentStatistics(segmentDataStats);loadSegmentEventReport();setupSegmentDataAndReports(segmentDataModel);initSegmentActivationButtons(segmentDataModel);loadSegmentBuilder(f,c,d,g,function(){loadProfilesInSegment();var h=$("#segment-builder-holder");h.find("input,select").attr("disabled","disabled");h.find("button").hide();$("#profilelist_holder").show()});loadActivationRules(segmentDataModel.activationRules);
document.title="Segment Details - "+segmentDataModel.name}else LeoAdminApiUtil.logErrorPayload(a)})},createSegmentJsonDataConnection=function(){var b=function(){iziToast.info({timeout:3E3,message:'The system is processing data for the segment "'+segmentDataModel.name+'"'});LeoAdminApiUtil.getSecuredData(window.baseLeoAdminUrl+"/cdp/segment/export-json",{segmentId:segmentDataModel.id},function(a){0===a.httpCode&&""===a.errorMessage&&a.data&&(a=window.baseLeoAdminUrl+a.data,$("#segment_json_url").val(a),
$("#btn_segment_json_url").data("url",a),setTimeout(function(){$("#btn_segment_json_url").data("init-done",!0).trigger("click")},800))})};null==mapClipboardJS["#btn_segment_json_url"]&&(mapClipboardJS["#btn_segment_json_url"]=!0,b(),new ClipboardJS("#btn_segment_json_url",{text:function(a){$("#btn_segment_json_url").data("init-done")&&notifySuccessMessage("Successfully copied URL into clipboard!");return $("#btn_segment_json_url").data("url")}}))},createSegmentCsvDataConnection=function(){var b=function(){iziToast.info({timeout:2E3,
message:'The system is processing data for the segment "'+segmentDataModel.name+'"'});LeoAdminApiUtil.getSecuredData(window.baseLeoAdminUrl+"/cdp/segment/export-csv",{segmentId:segmentDataModel.id,csvType:0},function(a){0===a.httpCode&&""===a.errorMessage&&a.data&&(a=window.baseLeoAdminUrl+a.data,$("#segment_csv_url").val(a),$("#btn_segment_csv_url").data("url",a),setTimeout(function(){$("#btn_segment_csv_url").data("init-done",!0).trigger("click")},800))})};null==mapClipboardJS["#btn_segment_csv_url"]&&
(mapClipboardJS["#btn_segment_csv_url"]=!0,b(),new ClipboardJS("#btn_segment_csv_url",{text:function(a){$("#btn_segment_csv_url").data("init-done")&&notifySuccessMessage("Successfully copied URL into clipboard!");return $("#btn_segment_csv_url").data("url")}}))},getAllSegmentRefs=function(b){if("function"!==typeof b)return!1;LeoAdminApiUtil.getSecuredData(window.baseLeoAdminUrl+"/cdp/segments/all-refs",{},function(a){0===a.httpCode&&""===a.errorMessage&&a.data?b(a.data):b(!1)});return!0},getSegmentDownloadUrl=
function(b,a){var c="#"+$(b).attr("id"),d=0,f="";"txt_exported_excel_csv"===a?(d=0,f="#ahref_exported_excel_csv"):"txt_exported_facebook_csv"===a&&(d=1,f="#ahref_exported_facebook_csv");b=function(){LeoAdminApiUtil.getSecuredData(window.baseLeoAdminUrl+"/cdp/segment/export-csv",{segmentId:segmentDataModel.id,csvType:d},function(e){0===e.httpCode&&""===e.errorMessage&&e.data&&(e=window.baseLeoAdminUrl+e.data,$("#"+a).val(e),$(c).data("url",e),$(f).attr("href",e).show(),setTimeout(function(){$(c).data("init-done",
!0).trigger("click")},800))})};null==mapClipboardJS[c]&&(mapClipboardJS[c]=!0,b(),iziToast.info({timeout:2E3,message:'The system is processing data for the segment "'+segmentDataModel.name+'"'}),new ClipboardJS(c,{text:function(e){$(c).data("init-done")&&notifySuccessMessage("Successfully copied URL into clipboard!");return $(c).data("url")}}))};window.segmentEventChart=!1;
const loadSegmentEventReport=function(b){var a=getDateFilterValues();a.segmentId=segmentDataModel.id;var c=a.beginFilterDate;$("#eventDataFromDate").text((new moment(c)).format("YYYY-MM-DD HH:mm:ss"));c=a.endFilterDate;$("#eventDataToDate").text((new moment(c)).format("YYYY-MM-DD HH:mm:ss"));c=baseLeoAdminUrl+"/cdp/analytics360/event-report/segment";$("#segment_report_loader").show();$("#segmentEventChart").css("visibility","hidden");LeoAdminApiUtil.getSecuredData(c,a,function(d){$("#segment_report_loader").hide();
$("#segmentEventChart").css("visibility","visible");0===d.httpCode&&""===d.errorMessage?!0===b&&!1!==segmentEventChart?renderTimeseriesChart("segmentEventChart",d.data,!0,segmentEventChart,!0):window.segmentEventChart=renderTimeseriesChart("segmentEventChart",d.data,!1,null,!0):LeoAdminApiUtil.logErrorPayload(d)})},initSegmentActivationButtons=function(b){var a=b.id,c=b.name,d=b.totalCount;$("button[data-purpose]").click(function(){var f=$(this).data("purpose");"forPersonalization"===f?showDataPersonalizationDialog(a,
c,d):"forDataEnrichment"===f?showDataEnrichmentDialog(a,c,d):"forSynchronization"===f?showDataSynchronizationDialog(a,c,d):"forAutomatedCampaigns"===f&&showAutomatedCampaignsDialog(a,c,d)})},getHtmlForAuthorizedUserLogin=function(b){var a="";b.forEach(function(c){a=6===currentUserProfile.role?a+("\x3ca title\x3d\"User Login Report\" href\x3d\"#calljs-leoCdpRouter('User_Login_Report','"+(c+"')\" \x3e")+c+"\x3c/a\x3e, "):a+(c+", ")});return a},setupSegmentDataAndReports=function(b){var a=b.name,c=b.totalCount.toLocaleString(),
d=4<=currentUserProfile.role;$("#sm_indexScore").text(b.indexScore);$("#sm_name").text(a);$("b.segment_size").text(c);$("#sm_description").text(b.description);$("#sm_authorizedViewers").html(getHtmlForAuthorizedUserLogin(b.authorizedViewers));$("#sm_authorizedEditors").html(getHtmlForAuthorizedUserLogin(b.authorizedEditors));a=$("#segment_data_personalization");b.forPersonalization&&d?(a.show(),setTimeout(loadPersonalizationTabForSegment,1E3)):a.hide();a=$("#segment_data_enrichment");(b.forDeepAnalytics||
b.forPredictiveAnalytics)&&d?a.show():a.hide();a=$("#segment_data_synchronization");(b.for3rdSynchronization||b.forEmailMarketing)&&d?a.show():a.hide()};function handleSegmentPersonalizationTabs(){$("#personalizationPlan li.active a").click()}
const loadPersonalizationTabForSegment=function(){var b=function(a,c){var d=$(a);c.forEach(function(f,e){d.append('\x3coption value\x3d"'+f.id+'" \x3e'+f.title+"\x3c/option\x3e")});d.chosen({width:"100%",no_results_text:"Oops, nothing found!"}).trigger("chosen:updated")};LeoAdminApiUtil.getSecuredData(window.baseLeoAdminUrl+"/cdp/asset-group/list-by-asset-types",{assetTypes:"1,2,15,16"},function(a){if(0===a.httpCode&&""===a.errorMessage){a=a.data;$("#productGroupSelector option").remove();$("#contentGroupSelector option").remove();
for(var c in a){var d=a[c];2===parseInt(c)?b("#productGroupSelector",d):b("#contentGroupSelector",d)}}else LeoAdminApiUtil.logErrorPayload(a)})},initPersonalizationInSegment=function(b){!1===window.segmentFirstProfileId&&(window.segmentFirstProfileId=b,loadRecommendedContentsOfProfile(segmentFirstProfileId,!1,function(a){$("#max_recommended_contents").html(a)}),loadRecommendedProductsOfProfile(segmentFirstProfileId,!1,function(a){$("#max_recommended_products").html(a)}))},setContentPersonalizationInSegment=
function(){var b=$("#contentGroupSelector").val();b&&""!==b&&segmentDataModel&&(iziToast.info({title:"Information Box",color:"green",message:"Starting content personalization..."}),LeoAdminApiUtil.callPostAdminApi(baseLeoAdminUrl+"/cdp/segment/set-recommended-items",{assetGroupId:b,segmentId:segmentDataModel.id,isProductGroup:!1},function(a){0===a.httpCode&&""===a.errorMessage&&(iziToast.info({title:"Information Box",color:"green",message:"Setting recommended contents for customer personalization is successful !"}),
!1!==segmentFirstProfileId&&loadRecommendedContentsOfProfile(segmentFirstProfileId,!1,function(c){$("#max_recommended_contents").html(c)}))}))},setProductPersonalizationInSegment=function(){var b=$("#productGroupSelector").val();b&&""!==b&&segmentDataModel&&(iziToast.info({title:"Information Box",color:"green",message:"Starting product personalization..."}),LeoAdminApiUtil.callPostAdminApi(baseLeoAdminUrl+"/cdp/segment/set-recommended-items",{assetGroupId:b,segmentId:segmentDataModel.id,isProductGroup:!0},
function(a){0===a.httpCode&&""===a.errorMessage&&(!1!==segmentFirstProfileId&&loadRecommendedProductsOfProfile(segmentFirstProfileId,!1,function(c){$("#max_recommended_products").html(c)}),iziToast.info({title:"Information Box",color:"green",message:"Setting recommended products for customer personalization is successful !"}))}))},removeRecommendedItemsInSegment=function(b,a,c){a&&""!==a&&segmentDataModel&&(iziToast.info({title:"Information Box",color:"yellow",message:"Starting to remove recommended items"}),
LeoAdminApiUtil.callPostAdminApi(baseLeoAdminUrl+"/cdp/segment/remove-recommended-items",{assetGroupId:a,segmentId:segmentDataModel.id,isProductGroup:b},function(d){0===d.httpCode&&""===d.errorMessage&&(iziToast.info({title:"Information Box",color:"green",message:"Successfully remove recommended items in the segment"}),c())}))},removeRecommendedContentsInSegment=function(b){b=!0===b?"remove_all":$("#contentGroupSelector").val();removeRecommendedItemsInSegment(!1,b,function(){!1!==window.segmentFirstProfileId&&
loadRecommendedContentsOfProfile(window.segmentFirstProfileId,!1,function(a){$("#max_recommended_contents").html(a)})})},removeRecommendedProductsInSegment=function(b){b=!0===b?"remove_all":$("#productGroupSelector").val();removeRecommendedItemsInSegment(!0,b,function(){!1!==window.segmentFirstProfileId&&loadRecommendedProductsOfProfile(window.segmentFirstProfileId,!1,function(a){$("#max_recommended_products").html(a)})})},loadDataServiceSelection=function(b,a){var c=$("#btnOkActivateSegment");c.data("segmentId",
b).data("segmentName",a).hide();$("#dataServiceSelector_loader").show();$("#dataServiceSelector_holder").hide();var d=$("#dataServiceSelector");d.find("option").remove().trigger("chosen:updated");b="true"===d.data("forSynchronization");a="true"===d.data("forDataEnrichment");var f="true"===d.data("forPersonalization");dataServiceLoader("",!0,f,a,b,0,1E4,function(e){c.show();$("#dataServiceSelector_loader").hide();$("#dataServiceSelector_holder").show();0<e.length?_.forEach(e,function(g,h){d.append('\x3coption value\x3d"'+
g.id+'" \x3e'+g.name+"\x3c/option\x3e")}):d.append('\x3coption value\x3d"" \x3e No available service for data enrichment\x3c/option\x3e');d.chosen({width:"100%"}).trigger("chosen:updated")})},setTimeToRunDataService=function(){var b=(new Date).getUTCHours();b=9<b?b:"0"+b;var a=((new Date).getUTCMinutes()+2)%60;b=b+":"+(9<a?a:"0"+a);$("#dataServiceDateTimeStart").val(b);b=$("#box_everyday_at_time");0<$("#dataServiceSchedulingTime").val()?b.show():b.hide()};var SchedulingTimeUnit="hour";
const SchedulingTimeMap={0:"Run immediately and repeat every 5 minutes"};SchedulingTimeMap["1"]="Run every 1 "+SchedulingTimeUnit+" starting from specific time";SchedulingTimeMap["2"]="Run every 2 "+SchedulingTimeUnit+"s starting from specific time";SchedulingTimeMap["3"]="Run every 3 "+SchedulingTimeUnit+"s starting from specific time";SchedulingTimeMap["4"]="Run every 4 "+SchedulingTimeUnit+"s starting from specific time";SchedulingTimeMap["5"]="Run every 5 "+SchedulingTimeUnit+"s starting from specific time";
SchedulingTimeMap["6"]="Run every 6 "+SchedulingTimeUnit+"s starting from specific time";SchedulingTimeMap["7"]="Run every 7 "+SchedulingTimeUnit+"s starting from specific time";SchedulingTimeMap["8"]="Run every 8 "+SchedulingTimeUnit+"s starting from specific time";SchedulingTimeMap["9"]="Run every 9 "+SchedulingTimeUnit+"s starting from specific time";SchedulingTimeMap["10"]="Run every 10 "+SchedulingTimeUnit+"s starting from specific time";
SchedulingTimeMap["12"]="Run every 12 "+SchedulingTimeUnit+"s starting from specific time";SchedulingTimeMap["15"]="Run every 15 "+SchedulingTimeUnit+"s starting from specific time";SchedulingTimeMap["20"]="Run every 20 "+SchedulingTimeUnit+"s starting from specific time";SchedulingTimeMap["24"]="Run every 24 "+SchedulingTimeUnit+"s starting from specific time";SchedulingTimeMap["48"]="Run every 48 "+SchedulingTimeUnit+"s starting from specific time";
SchedulingTimeMap["72"]="Run every 72 "+SchedulingTimeUnit+"s starting from specific time";SchedulingTimeMap["168"]="Run every week starting from specific time";SchedulingTimeMap["336"]="Run every 2 weeks starting from specific time";SchedulingTimeMap["672"]="Run every 4 weeks starting from specific time";function ServiceSchedulingTime(b){jsGrid.Field.call(this,b)}
ServiceSchedulingTime.prototype=new jsGrid.Field({sorter:function(b,a){return 0},itemTemplate:function(b){var a=SchedulingTimeMap[""+b.schedulingTime];""!==b.timeToStart&&(a="string"===typeof a?a+' \x3cb class\x3d"highlight_text"\x3e'+b.timeToStart+"\x3c/b\x3e":"");return'\x3cdiv style\x3d"font-size:14px;" target\x3d"_blank" \x3e'+a+"\x3c/div\x3e"},insertTemplate:function(b){return this._insertCode=b},editTemplate:function(b){return this._editCode=b},insertValue:function(){return this._insertCode},
editValue:function(){return this._editCode}});jsGrid.fields.ServiceSchedulingTime=ServiceSchedulingTime;
const initActivationJsGridPlugin=function(){function b(a){jsGrid.Field.call(this,a)}b.prototype=new jsGrid.Field({sorter:function(a,c){return 0},itemTemplate:function(a){var c=a.id,d=a.dataServiceName;a=a.active;console.log("activationRuleId ",c);console.log("active ",a);var f='\x3cdiv class\x3d"col-lg-12" \x3e\x3cbutton type\x3d"button" class\x3d"activation-btn btn btn-do-now btn-sm" onclick\x3d"manuallyRunActivationOfSegment(this)" data-activation-rule-id\x3d"'+(c+'"  data-activation-service-name\x3d"')+
(d+'" \x3e\x3ci class\x3d"fa fa-play" style\x3d"font-size:1.2em" aria-hidden\x3d"true"\x3e\x3c/i\x3e Manually Run \x3c/button\x3e\x3c/div\x3e');a?(f+='\x3cdiv class\x3d"col-lg-12" \x3e\x3cbutton type\x3d"button" class\x3d"activation-btn btn btn-warning btn-sm" onclick\x3d"stopActivationForSegment(this)"',f=f+(' data-activation-rule-id\x3d"'+c+'"  data-activation-service-name\x3d"')+(d+'" \x3e\x3ci class\x3d"fa fa-stop" style\x3d"font-size:1.2em" aria-hidden\x3d"true"\x3e\x3c/i\x3e Stop Scheduler \x3c/button\x3e\x3c/div\x3e')):
(f+='\x3cdiv class\x3d"col-lg-12" \x3e\x3cbutton type\x3d"button" class\x3d"activation-btn btn btn-goto-router btn-sm" onclick\x3d"startActivationForSegment(this)"',f=f+(' data-activation-rule-id\x3d"'+c+'"  data-activation-service-name\x3d"')+(d+'" \x3e\x3ci class\x3d"fa fa-play" style\x3d"font-size:1.2em" aria-hidden\x3d"true"\x3e\x3c/i\x3e Start Scheduler \x3c/button\x3e\x3c/div\x3e'),f+='\x3cdiv class\x3d"col-lg-12" \x3e\x3cbutton type\x3d"button" class\x3d"activation-btn btn btn-danger btn-sm" onclick\x3d"removeActivationForSegment(this)"',
f=f+(' data-activation-rule-id\x3d"'+c+'"  data-activation-service-name\x3d"')+(d+'" \x3e\x3ci class\x3d"fa fa-trash-o" style\x3d"font-size:1.2em" aria-hidden\x3d"true"\x3e\x3c/i\x3e Remove \x3c/button\x3e\x3c/div\x3e'));return f},insertTemplate:function(a){return this._insertCode=a},editTemplate:function(a){return this._editCode=a},insertValue:function(){return this._insertCode},editValue:function(){return this._editCode}});jsGrid.fields.ActivationButtons=b},loadActivationRules=function(b){var a=
function(e,g){$(e).jsGrid({width:"100%",height:"auto",autoload:!1,inserting:!1,editing:!1,sorting:!0,paging:!1,data:g,fields:[{name:"updatedAt",title:'\x3ci class\x3d"fa fa-info-circle" aria-hidden\x3d"true"\x3e\x3c/i\x3e Updated at',type:"JsGridLocalTime",align:"center",width:56,sorting:!0},{name:"schedulingTime",title:'\x3ci class\x3d"fa fa-bolt" aria-hidden\x3d"true"\x3e\x3c/i\x3e Rule to trigger',type:"ServiceSchedulingTime",align:"center",sorting:!1},{name:"dataServiceName",title:'\x3ci class\x3d"fa fa-info-circle" aria-hidden\x3d"true"\x3e\x3c/i\x3e Data Service Name',
type:"BoldText",align:"center",sorting:!1},{name:"active",title:'\x3ci class\x3d"fa fa-info-circle" aria-hidden\x3d"true"\x3e\x3c/i\x3e Active',type:"CheckBoxIcon",align:"center",width:28,sorting:!1},{name:"ownerUsername",title:'\x3ci class\x3d"fa fa-info-circle" aria-hidden\x3d"true"\x3e\x3c/i\x3e Created by',type:"BoldText",align:"center",width:56,sorting:!1},{name:"buttonState",title:"Actions",type:"ActivationButtons",width:40,align:"center"}]})},c=[],d=[],f=[];b.forEach(function(e){e.buttonState=
{id:e.id,active:e.active,dataServiceName:e.dataServiceName};e.schedulingTime={schedulingTime:e.schedulingTime,timeToStart:e.timeToStart};"personalization"===e.purpose?c.push(e):"data_enrichment"===e.purpose?d.push(e):"synchronization"===e.purpose&&f.push(e)});b=function(e,g){return e.updatedAt>g.updatedAt?-1:e.updatedAt<g.updatedAt?1:0};c.sort(b);d.sort(b);f.sort(b);initActivationJsGridPlugin();a("#segment_personalization_services",c);a("#segment_enrichment_services",d);a("#segment_synchronization_services",
f)},loadSchedulingTimeSelect=function(){var b=$("#dataServiceSchedulingTime");_.forOwn(SchedulingTimeMap,function(a,c){a=$('\x3coption value\x3d"'+c+'" \x3e'+a+"\x3c/option\x3e");b.append(a)})},showDataPersonalizationDialog=function(b,a,c){$("#dialogSelectDataService").modal({backdrop:"static",keyboard:!1});$("#purpose_activation_name").text("data personalization");$("#btnOkActivateSegment").data("purpose","personalization");c=$("#dataServiceSelector");c.data("forSynchronization","false");c.data("forDataEnrichment",
"false");c.data("forPersonalization","true");loadDataServiceSelection(b,a)},showDataEnrichmentDialog=function(b,a,c){$("#dialogSelectDataService").modal({backdrop:"static",keyboard:!1});$("#purpose_activation_name").text("data enrichment");$("#btnOkActivateSegment").data("purpose","data_enrichment");c=$("#dataServiceSelector");c.data("forSynchronization","false");c.data("forDataEnrichment","true");c.data("forPersonalization","false");loadDataServiceSelection(b,a)},showDataSynchronizationDialog=function(b,
a,c){$("#dialogSelectDataService").modal({backdrop:"static",keyboard:!1});$("#purpose_activation_name").text("data synchronization");$("#btnOkActivateSegment").data("purpose","synchronization");c=$("#dataServiceSelector");c.data("forSynchronization","true");c.data("forDataEnrichment","false");c.data("forPersonalization","false");loadDataServiceSelection(b,a)},showAutomatedCampaignsDialog=function(b,a,c){$("#dialogSelectDataService").modal({backdrop:"static",keyboard:!1});$("#purpose_activation_name").text("data personalization");
$("#btnOkActivateSegment").data("purpose","personalization")},activateDataService=function(b){var a=$(b).data("purpose"),c=$("#dataServiceSelector").val(),d=$(b).data("segmentId"),f=$(b).data("segmentName");b=parseInt($("#dataServiceSchedulingTime").val());var e=$("#dataServiceDateTimeStart").val();"string"===typeof c&&""!==c?($("#dialogSelectDataService").modal("hide"),d={purpose:a,segmentId:d,dataServiceId:c},d.schedulingTime=b,d.timeToStart=e,LeoAdminApiUtil.callPostAdminApi("/cdp/data-service/create-activation",
d,function(g){""!==g.data?(g="The segment ["+f+"] is successfully activated for "+a.replace("_"," "),notifySuccessMessage(g,function(){refreshSegmentDetails()})):notifyErrorMessage("Data activation for ["+f+"], is failed, please set valid configs for the service: "+c)})):iziToast.error({title:"Error",message:"Please select an active service"})},stopActivationForSegment=function(b){var a=$(b).data("activation-rule-id"),c=$(b).data("activation-service-name");LeoAdminApiUtil.callPostAdminApi("/cdp/data-service/stop-activation",
{activationRuleId:a},function(d){!0===d.data?(d="The activation rule of service ["+c+"] is successfully stopped ! ",notifySuccessMessage(d,function(){refreshSegmentDetails()})):(d="There is an error when stop the activation rule of service ["+c+"] ! ",notifyErrorMessage(d))})},startActivationForSegment=function(b){var a=$(b).data("activation-rule-id"),c=$(b).data("activation-service-name");LeoAdminApiUtil.callPostAdminApi("/cdp/data-service/start-activation",{activationRuleId:a},function(d){!0===
d.data?(d="The activation rule of service ["+c+"] is successfully started ! ",notifySuccessMessage(d,function(){refreshSegmentDetails()})):(d="There is an error when start the activation rule of service ["+c+"] ! ",notifyErrorMessage(d))})},removeActivationForSegment=function(b){var a=$(b).data("activation-rule-id"),c=$(b).data("activation-service-name");LeoAdminApiUtil.callPostAdminApi("/cdp/data-service/remove-activation",{activationRuleId:a},function(d){!0===d.data?(d="The activation rule of service ["+
c+"] is successfully removed ! ",notifySuccessMessage(d,function(){refreshSegmentDetails()})):(d="There is an error when remove the activation rule of service ["+c+"] ! ",notifyErrorMessage(d))})},loadActivationLogsOfSegment=function(b){b=$(b).data("activation-rule-id");console.log("load Action Logs of ActivationRule ID: "+b);loadSystemEventsTable("Activation Rule","activationEventLogsHolder","ActivationRule",b,"leocdp",function(){$("#activationEventLogsDialog").modal({backdrop:"static",keyboard:!1})},
[6])},manuallyRunActivationOfSegment=function(b){var a=$(b).data("activation-rule-id"),c=$(b).data("activation-service-name");LeoAdminApiUtil.callPostAdminApi("/cdp/data-service/manually-run-activation",{activationRuleId:a},function(d){!0===d.data?(d="The activation rule of service ["+c+"] is manually run ! ",notifySuccessMessage(d,function(){refreshSegmentDetails()})):(d="There is an error when start the activation rule of service ["+c+"] ! ",notifyErrorMessage(d))})};