'use strict';const setupImageUrlInput=function(a,b,c){c=null==c||""===c?"https://cdn-icons-png.flaticon.com/512/3875/3875148.png":c;$(b).attr("src",c).error(function(){notifyErrorMessage($(this).attr("src")+" is not a valid image URL");$(this).attr("src","https://cdn-icons-png.flaticon.com/512/3875/3875148.png")});$(a).val(c).change(function(){var d=$(this).val().trim();d=""===d?"https://cdn-icons-png.flaticon.com/512/3875/3875148.png":d;$(b).attr("src",d)})};
function insertTextAtCursorInCodeMirror(a,b){a=a.getDoc();var c=a.getCursor();a.replaceRange(b,c)}function getHeadLinesImagsObject(){var a={};$("#headline_images .thumbnail").each(function(){var b=$(this).find("img").attr("src"),c="",d=$(this).find("p.editable");d.hasClass("editable-empty")||(c=d.text().trim());a[b]=c});return a}
const setupImageInputForContent=function(a,b){b=null==b||""===b?"https://cdn-icons-png.flaticon.com/512/3875/3875148.png":b;$(a).val(b).change(function(){var c=$(this).val().trim();c=""===c?"https://cdn-icons-png.flaticon.com/512/3875/3875148.png":c;if(0===$("#headline_images").find('img[src\x3d"'+c+'"]').length){var d={};d[c]="";loadHeadLineImageObjectToView(d,!1,!0)}});setTimeout(function(){if(0===$("#headline_images").show().find("img").length){var c={};c[b]="";loadHeadLineImageObjectToView(c,
!1,!0)}},1200)},updateBreadcrumbInAssetGroup=function(a,b){for(var c in a){var d=a[c],e=d.name;d=leoCdpRouterParams([c,d.assetType,d.name]);$("#tnv_Asset_Groups").attr("href","#calljs-leoCdpRouter('Asset_Groups','"+d+"')").text(e).attr("title",e)}$("#tnv_Asset_Group_Details").text(b)},updateBreadcrumbInAssetPost=function(a,b,c){for(var d in a){var e=a[d],g=e.name;e=leoCdpRouterParams([d,e.assetType,e.name]);$("#tnv_Asset_Groups").attr("href","#calljs-leoCdpRouter('Asset_Groups','"+e+"')").text(g).attr("title",
g)}for(var h in b)a=b[h].title,$("#tnv_Asset_Group_Details").attr("href","#calljs-leoCdpRouter('Asset_Group_Details','"+h+"')").text(a).attr("title",a);$("#tnv_Content_Post").text(c).attr("title",c)},getAssetEditorCallJs=function(a,b){return 2===a?"calljs-leoCdpRouter('Asset_Product_Item_Editor','"+b+"')":3===a?"calljs-leoCdpRouter('Asset_Service_Item_Editor','"+b+"')":4===a||6===a||7===a?"calljs-leoCdpRouter('Asset_Template_Editor','"+b+"')":13===a?"calljs-leoCdpRouter('Asset_Feedback_Form_Editor','"+
b+"')":15===a?"calljs-leoCdpRouter('Asset_Short_Link_Editor','"+b+"')":16===a?"calljs-leoCdpRouter('Asset_Presentation_Editor','"+b+"')":"calljs-leoCdpRouter('Asset_Content_Editor','"+b+"')"};function getYouTubeVideoId(a){var b,c="";if(b=a.match(/(\?|&)v=([^&#]+)/))c=b.pop();else if(b=a.match(/(\.be\/)+([^\/]+)/))c=b.pop();else if(b=a.match(/(embed\/)+([^\/]+)/))c=b.pop().replace("?rel\x3d0","");return c.split("\x26")[0]}
function checkPostTypeAndSetupMediaEditor(a,b){console.log("checkPostTypeAndSetupMediaEditor postType "+a);if(1===a||2===a||6===a||8===a||9===a)$("#content_div").html(editorViewTpl),window.trixElement=document.querySelector('trix-editor[input\x3d"mediaInfo"]'),trixElement.editor.insertHTML(b),$(trixElement).focus(function(){trixElement=$(this)[0]}),trixElement.addEventListener("trix-attachment-add",function(d){}),addEventListener("trix-initialize",function(d){0===$("#trix_btn_md_to_html").length&&
(d=$('\x3cbutton id\x3d"trix_btn_md_to_html" type\x3d"button" \x3e\x3ci class\x3d"fa fa-code"\x3e\x3c/i\x3e Process Markdown Code\x3c/button\x3e'),$(".trix-button-group--text-tools").append(d),d.click(function(){var e=trixElement.editor.getDocument().toString();trixElement.editor.loadHTML(marked.parse(e.replaceAll("\n","\x3cbr\x3e")))}))});else{var c=$(documentUrlViewTpl).val(b);$("#content_div").html(c);c.change(function(){renderPostMediaInfo(c.val().trim())})}}
function normalizeMediaHtml(a){a=$("\x3cdiv/\x3e").html(a);a.find("img").each(function(){320<parseInt($(this).attr("width"))&&$(this).attr("style","height:100%!important;width:100%!important;object-fit:contain!important")});return a.html()}
function showRawTextHtmlEditor(){if(trixElement&&rawHtmlEditor){var a=$("#raw_media_container").show().width()-10,b=$("#mediaInfo").val();rawHtmlEditor.setValue(b);rawHtmlEditor.setSize(a,600);CodeMirrorAutoFormat(rawHtmlEditor)}else alert("trixElement or rawHtmlEditor is NULL !")}function showTextHtmlEditor(){if(trixElement&&rawHtmlEditor){var a=rawHtmlEditor.getValue();trixElement.editor.loadHTML(a)}else alert("trixElement or rawHtmlEditor is NULL !")}
function newAssetItemEditor(a,b,c){b=leoCdpRouterParams(["",b,c]);location.hash=getAssetEditorCallJs(a,b)}
function createAssetItemFromLeoBot(a,b,c){console.log(c);LeoAdminApiUtil.getSecuredData(baseLeoAdminUrl+"/cdp/asset-group/get-default",{context:a},function(d){0===d.httpCode&&""===d.errorMessage?(d=d.data,newAssetItemEditor(d.assetType,d.id,d.categoryIds[0]),setTimeout(function(){$("#asset_item_title").val(b).focus();"object"===typeof trixElement&&"content"===a?trixElement.editor.loadHTML(c):"presentation"===a&&"function"===typeof formatMarkdownToPresentation&&formatMarkdownToPresentation(c)},1500)):
LeoAdminApiUtil.logErrorPayload(d)})}function gotoAssetItemView(a,b,c){a=leoCdpRouterParams([a,b,c]);location.hash="calljs-leoCdpRouter('Asset_Content_View','"+a+"')"}function getFeedbackFormTypeAsString(a){return 0===a?"SURVEY":1===a?"CONTACT":2===a?"RATING":3===a?"CES":4===a?"CSAT":5===a?"NPS":""}function refreshCodeMirrorEditor(){$(".CodeMirror").each(function(a,b){b.CodeMirror.refresh();b.CodeMirror.execCommand("selectAll")})}
function initEmbeddedFeedbackForm(a,b,c,d){d="number"===typeof d?d:350;var e=$("#leo_survey_in_shared_devices").is(":checked"),g=c.title,h="leoFeedbackForm_"+c.id;e=e?"shared-devices\x3d1\x26tplid\x3d":"tplid\x3d";var r="https://"+baseLeoObserverDomain+"/webform?"+e,p=getFeedbackFormTypeAsString(c.templateType),q=p+" Form",l=$("#feedback_form_code_holder");l.css("visibility","hidden");$("#feedback_form_code_holder .CodeMirror").remove();var m=l.find("textarea.code"),k=CodeMirror.fromTextArea(m[0],
{mode:"htmlmixed",lineNumbers:!0,styleActiveLine:!0,matchBrackets:!0,readOnly:!1});k.setSize(null,430);setTimeout(function(){$("#"+b+" .eventName").text(q);var t=0<g.indexOf("Rating")?100:800,f=m.val().trim().replaceAll("__feedbackFormTitle__",g);f=f.replaceAll("__eventName__",q);f=f.replaceAll("__scriptNodeId__",h);f=f.replaceAll("__tplFeedbackType__",p);f=f.replaceAll("__feedbackFormFullUrl__",r);f=f.replaceAll("__iFrameHeight__",d);f=f.replaceAll("__observerId__",a);f=f.replaceAll("__iframeHeight__",
t);f=f.replaceAll("__templateId__",c.id);k.getDoc().setValue('\x3cscript id\x3d"'+h+'" \x3e\n'+f+"\n\x3c/script\x3e");k.refresh();k.execCommand("selectAll");addHandlerCopyCodeButton(m,"#"+b+" button.btn-copy-code");l.css("visibility","visible")},300);var n="https://"+window.baseUploadDomain+c.qrCodeUrl.replace("./","/");$("#cx_qrHrefUrl").attr("href",n);$("#cx_qrImgSrc").attr("src",n);$("#cx_qrCodeImageURL").val(n);e="https://"+baseLeoObserverDomain+"/webform?"+e+c.id+"\x26obsid\x3d"+a;$("#cx_qrFormURL").val(e)}
;