'use strict';const setupImageUrlInput=function(a,c,b){b=null==b||""===b?"https://cdn-icons-png.flaticon.com/512/3875/3875148.png":b;$(c).attr("src",b).error(function(){notifyErrorMessage($(this).attr("src")+" is not a valid image URL");$(this).attr("src","https://cdn-icons-png.flaticon.com/512/3875/3875148.png")});$(a).val(b).change(function(){var d=$(this).val().trim();d=""===d?"https://cdn-icons-png.flaticon.com/512/3875/3875148.png":d;$(c).attr("src",d)})};
function getHeadLinesImagsObject(){var a={};$("#headline_images .thumbnail").each(function(){var c=$(this).find("img").attr("src"),b="",d=$(this).find("p.editable");d.hasClass("editable-empty")||(b=d.text().trim());a[c]=b});return a}
const setupImageInputForContent=function(a,c){c=null==c||""===c?"https://cdn-icons-png.flaticon.com/512/3875/3875148.png":c;$(a).val(c).change(function(){var b=$(this).val().trim();b=""===b?"https://cdn-icons-png.flaticon.com/512/3875/3875148.png":b;if(0===$("#headline_images").find('img[src\x3d"'+b+'"]').length){var d={};d[b]="";loadHeadLineImageObjectToView(d,!1,!0)}});setTimeout(function(){if(0===$("#headline_images").show().find("img").length){var b={};b[c]="";loadHeadLineImageObjectToView(b,
!1,!0)}},1200)},updateBreadcrumbInAssetGroup=function(a,c){for(var b in a){var d=a[b],f=d.name;d=leoCdpRouterParams([b,d.assetType,d.name]);$("#tnv_Asset_Groups").attr("href","#calljs-leoCdpRouter('Asset_Groups','"+d+"')").text(f).attr("title",f)}$("#tnv_Asset_Group_Details").text(c)},updateBreadcrumbInAssetPost=function(a,c,b){for(var d in a){var f=a[d],g=f.name;f=leoCdpRouterParams([d,f.assetType,f.name]);$("#tnv_Asset_Groups").attr("href","#calljs-leoCdpRouter('Asset_Groups','"+f+"')").text(g).attr("title",
g)}for(var h in c)a=c[h].title,$("#tnv_Asset_Group_Details").attr("href","#calljs-leoCdpRouter('Asset_Group_Details','"+h+"')").text(a).attr("title",a);$("#tnv_Content_Post").text(b).attr("title",b)},getAssetEditorCallJs=function(a,c){return 2===a?"calljs-leoCdpRouter('Asset_Product_Item_Editor','"+c+"')":3===a?"calljs-leoCdpRouter('Asset_Service_Item_Editor','"+c+"')":4===a||6===a||7===a?"calljs-leoCdpRouter('Asset_Template_Editor','"+c+"')":13===a?"calljs-leoCdpRouter('Asset_Feedback_Form_Editor','"+
c+"')":15===a?"calljs-leoCdpRouter('Asset_Short_Link_Editor','"+c+"')":"calljs-leoCdpRouter('Asset_Content_Editor','"+c+"')"};function getYouTubeVideoId(a){var c,b="";if(c=a.match(/(\?|&)v=([^&#]+)/))b=c.pop();else if(c=a.match(/(\.be\/)+([^\/]+)/))b=c.pop();else if(c=a.match(/(embed\/)+([^\/]+)/))b=c.pop().replace("?rel\x3d0","");return b.split("\x26")[0]}
function checkPostTypeAndSetupMediaEditor(a,c){console.log("checkPostTypeAndSetupMediaEditor postType "+a);if(1===a||2===a||6===a||8===a||9===a)$("#content_div").html(editorViewTpl),window.trixElement=document.querySelector('trix-editor[input\x3d"mediaInfo"]'),trixElement.editor.insertHTML(c),$(trixElement).focus(function(){trixElement=$(this)[0]}),trixElement.addEventListener("trix-attachment-add",function(d){});else{var b=$(documentUrlViewTpl).val(c);$("#content_div").html(b);b.change(function(){renderPostMediaInfo(b.val().trim())})}}
function normalizeMediaHtml(a){a=$("\x3cdiv/\x3e").html(a);a.find("img").each(function(){320<parseInt($(this).attr("width"))&&$(this).attr("style","height:100%!important;width:100%!important;object-fit:contain!important")});return a.html()}
function toggleRawHtmlEditor(a){if("hidden"===$(a).data("visibilty")){var c=$("#raw_media_container").show().width()-10;$("#content_div").hide();var b=$("#mediaInfo").val();rawHtmlEditor.setValue(b);CodeMirrorAutoFormat(rawHtmlEditor);$(a).data("visibilty","visible");rawHtmlEditor.setSize(c,800);$(a).html('\x3ci class\x3d"fa fa-fw fa-code"\x3e\x3c/i\x3e Hide HTML Editor')}else $("#raw_media_container").hide(),$("#content_div").show(),trixElement.editor.loadHTML(rawHtmlEditor.getValue()),$(a).data("visibilty",
"hidden"),rawHtmlEditor.setSize(null,1),$(a).html('\x3ci class\x3d"fa fa-fw fa-code"\x3e\x3c/i\x3e Show HTML Editor')}function newAssetItemEditor(a,c,b){c=leoCdpRouterParams(["",c,b]);location.hash=getAssetEditorCallJs(a,c)}
function createAssetItemFromLeoBot(a,c){console.log(c);LeoAdminApiUtil.getSecuredData(baseLeoAdminUrl+"/cdp/asset-group/get-default-for-content",{},function(b){0===b.httpCode&&""===b.errorMessage?(b=b.data,newAssetItemEditor(b.assetType,b.id,b.categoryIds[0]),setTimeout(function(){$("#asset_item_title").val(a).focus();trixElement&&trixElement.editor.loadHTML(c)},1500)):LeoAdminApiUtil.logErrorPayload(b)})}
function gotoAssetItemView(a,c,b){a=leoCdpRouterParams([a,c,b]);location.hash="calljs-leoCdpRouter('Asset_Content_View','"+a+"')"}function getFeedbackFormTypeAsString(a){return 0===a?"SURVEY":1===a?"CONTACT":2===a?"RATING":3===a?"CES":4===a?"CSAT":5===a?"NPS":""}function refreshCodeMirrorEditor(){$(".CodeMirror").each(function(a,c){c.CodeMirror.refresh();c.CodeMirror.execCommand("selectAll")})}
function initEmbeddedFeedbackForm(a,c,b,d){d="number"===typeof d?d:350;var f=b.title,g="leoFeedbackForm_"+b.id,h="https://"+baseLeoObserverDomain+"/webform?tplid\x3d",n=getFeedbackFormTypeAsString(b.templateType),p=n+" Form",l=$("#feedback_form_code_holder");l.css("visibility","hidden");$("#feedback_form_code_holder .CodeMirror").remove();var m=l.find("textarea.code"),k=CodeMirror.fromTextArea(m[0],{mode:"htmlmixed",lineNumbers:!0,styleActiveLine:!0,matchBrackets:!0,readOnly:!1});k.setSize(null,460);
setTimeout(function(){$("#"+c+" .eventName").text(p);var q=0<f.indexOf("Rating")?100:800,e=m.val().trim().replaceAll("__feedbackFormTitle__",f);e=e.replaceAll("__eventName__",p);e=e.replaceAll("__scriptNodeId__",g);e=e.replaceAll("__tplFeedbackType__",n);e=e.replaceAll("__feedbackFormFullUrl__",h);e=e.replaceAll("__iFrameHeight__",d);e=e.replaceAll("__observerId__",a);e=e.replaceAll("__iframeHeight__",q);e=e.replaceAll("__templateId__",b.id);k.getDoc().setValue('\x3cscript id\x3d"'+g+'" \x3e\n'+e+
"\n\x3c/script\x3e");k.refresh();k.execCommand("selectAll");addHandlerCopyCodeButton(m,"#"+c+" button.btn-copy-code");l.css("visibility","visible")},300)};