'use strict';const EXPIRED_AFTER_21_DAYS=30240,loadSystemUserLoginSession=function(){LeoAdminApiUtil.callPostApi(baseLeoAdminUrl+"/user/login-session",{},function(c){0===c.httpCode&&""===c.errorMessage?(loginFormHandler(c.data.userSession),c="data:image/png;base64,"+c.data.captchaImage,$("#captcha_img").show().attr("src",c),$("#system_user_login_loader").hide(),$("#system_user_login_div").show()):LeoAdminApiUtil.logErrorPayload(c)})},loginFormHandler=function(c){var a=function(){var b=baseLeoAdminUrl+
"/user/check-login",d=$("#username").val(),g=$("#password").val(),h=$("#captcha").val();d={userlogin:d,userpass:g,usersession:c,captcha:h};$("#info-login").html("\x3cb\x3eSending data ...\x3c/b\x3e").show();LeoAdminApiUtil.callPostApi(b,d,function(f){if(""===f.errorMessage){var k=f.data;lscache.set("usersession",c,EXPIRED_AFTER_21_DAYS);lscache.set("encryptionkey",k,EXPIRED_AFTER_21_DAYS);$("#system_user_login_form, #btn_system_login").hide();$("#info-login").html('\x3ci class\x3d"fa fa-check-circle fa-2" aria-hidden\x3d"true"\x3e\x3c/i\x3e \x3cb\x3e Login successfully ! \x3c/b\x3e ');
setTimeout(function(){window.location.reload(!0)},2500)}else $("#info-login").hide(),$("#error-login").html('\x3ci class\x3d"fa fa-exclamation-circle" aria-hidden\x3d"true"\x3e\x3c/i\x3e '+f.errorMessage).show().delay(5E3).fadeOut(),setTimeout(function(){LeoAdminApiUtil.logErrorPayload(f)},2500)})};$("#btn_system_login").click(a);$("#username").on("keyup",function(b){13===b.keyCode&&$("#password").focus()});$("#password").on("keyup",function(b){13===b.keyCode&&$("#captcha").focus()});$("#captcha").on("keyup",
function(b){13===b.keyCode&&a()})},initSystemUserLogin=function(){$("#login_logo").attr("src",window.pageHeaderLogo).show();var c=lscache.get("usersession"),a=lscache.get("encryptionkey");"string"===typeof c&&"string"===typeof a?console.log("You login OK with session "+c):(loadSystemUserLoginSession(),console.log("loadSystemUserLoginSession is called "))},loadSystemEventsTable=function(c,a,b,d,g,h,f){var k=getUserSession();if(k){c=_.template($("#system-event-table-tpl").html())({eventObjectName:c});
$("#"+a).empty().html(c);var n=[{data:"createdAt"},{data:"action"},{data:"accessIp"},{data:"userAgent"},{data:"data"}];f="object"===typeof f?f:[20,30,40];return $("#system_event_table").DataTable({lengthMenu:[f,f],lengthChange:1<f.length?!0:!1,processing:!0,serverSide:!0,searching:!1,search:{return:!1},ordering:!0,serverMethod:"POST",ajax:{url:baseLeoAdminUrl+"/cdp/system-control/action-logs",contentType:"application/json",beforeSend:function(e){$("#system_event_loader").show();$("#system_event_list").hide();
e.setRequestHeader("leouss",k)},data:function(e){e.objectName=b;e.objectId=d;e.action="";e.accessIp="";e.requestUserLogin=g;var l=e.order[0];e.sortField=n[l.column].data;e.sortAsc="asc"===l.dir;e.searchValue=e.search.value;delete e.order;delete e.search;return JSON.stringify(e)},dataSrc:function(e){var l=e.canInsertData,m=e.canEditData,p=e.canDeleteData;$("#system_event_table").data("canInsertData",l);$("#system_event_table").data("canEditData",m);$("#system_event_table").data("canDeleteData",p);
$("#system_event_loader").hide();$("#system_event_list").show();"function"===typeof h&&h();return e.data}},columnDefs:[{render:function(e,l,m){return'\x3cdiv class\x3d"text-center" style\x3d"color:#3300ff; width:78px; margin: auto;" \x3e\x3cmark\x3e'+toLocalDateTime(e)+"\x3c/mark\x3e\x3c/div\x3e"},targets:0},{render:function(e,l,m){return'\x3cdiv style\x3d"font-size:0.9em; width:180px; text-align:center; margin: auto;word-wrap: break-word;" \x3e\x3cmark\x3e'+e+"\x3c/mark\x3e\x3c/div\x3e"},targets:1,
orderable:!1},{render:function(e,l,m){return'\x3cdiv style\x3d"font-size:0.9em; text-align:center; margin: auto; word-wrap: break-word;"\x3e\x3cmark\x3e'+e+"\x3c/mark\x3e\x3c/div\x3e"},targets:2,orderable:!1},{render:function(e,l,m){return'\x3cdiv style\x3d"font-size:0.8em; text-align:center; width:260px; margin: auto; word-wrap: break-word;" \x3e'+e+"\x3c/div\x3e"},targets:3,orderable:!1},{render:function(e,l,m){return'\x3cdiv style\x3d"font-size:0.78em; word-wrap: break-word; width:400px; margin: auto;" \x3e'+
textTruncate(e,300)+"\x3c/div\x3e"},targets:4,orderable:!1}],columns:n,order:[[0,"desc"]]})}},loadSystemEventsFromLoginUser=function(c){return loadSystemEventsTable("User Login","panel_login_account_view_logs","SystemUser","",c)};
var loadSystemInfoConfigs=function(){LeoAdminApiUtil.getSecuredData("/cdp/system-config/list-all",{},function(c){var a=$("#system_configs_holder");_.forEach(c.data,function(b,d){d=b.id;systemConfigMap[d]=b;b.disabledText=b.configs.read_only?"disabled":"";if("string"===typeof b.description&&"string"===typeof b.configs.service_api_url){var g=_.template($("#tpl_system_config_box").html());a.append(g(b));"local-system"===b.configs.service_api_url&&$("#"+d+"_buttons_div").find("button").attr("disabled",
"disabled");1===b.status&&$("#"+d+"_api_url_div").addClass("highlight_text")}});a.find("div.active_false button").attr("class","btn btn-default").attr("disabled","disabled");a.find("div.panel_active_false").find("input").attr("disabled","disabled");a.find("i.config_description").tooltip();c=_.map(systemConfigMap.profile_data_fields.coreFieldConfigs,function(b,d){return 0<b.dataQualityScore?(b.coreAttribute=!0,b):!1});c=_.filter(c,function(b){return!1!==b});c=_.sortBy(c,[function(b){return b.identityResolution?
1E3*b.dataQualityScore:b.dataQualityScore}]).reverse();$("#profileAttributeCount").text(c.length);renderProfileMetaDataTable(c)})};
function renderProfileMetaDataTable(c){$("#profile_metadata_table").jsGrid({data:c,width:"100%",height:"auto",inserting:!1,editing:!0,sorting:!0,paging:!1,confirmDeleting:!0,deleteConfirm:function(a){return a.coreAttribute?"The attribute \x3cb\x3e["+a.attributeName+"]\x3c/b\x3e is the \x3cb\x3eattribute of system\x3c/b\x3e. You can not delete this attribute.":"The attribute ["+a.attributeName+"] will be removed. Are you sure ? "},onItemInserting:function(a){},onItemInserted:function(a){},onItemEditing:function(a){},
onItemUpdated:function(a){var b=a.item;console.log(b);a=systemConfigMap.profile_data_fields;var d=a.coreFieldConfigs[b.attributeName];d&&(d.dataQualityScore=b.dataQualityScore,a={objectJson:JSON.stringify(a)},LeoAdminApiUtil.callPostAdminApi("/cdp/system-config/save",a,function(g){0===g.httpCode&&""===g.errorMessage?notifySuccessMessage("The attribute \x3cb\x3e["+b.attributeName+"]\x3c/b\x3e is saved successfully !"):LeoAdminApiUtil.logErrorPayload(g)}))},onItemDeleting:function(a){},onRefreshed:function(a){},
fields:[{name:"identityResolution",title:"Identity Resolution Key",align:"center",type:"CheckBoxIcon",width:64,sorter:"string",editTemplate:function(a){return'\x3cdiv class\x3d"text-center"\x3e'+getCheckedBoxIcon(a)+"\x3c/div\x3e"}},{name:"attributeName",title:"Attribute Name",align:"center",type:"text",validate:"required",validate:"required",editing:!1},{name:"label",title:"Label",align:"center",type:"text",validate:"required",width:120,editing:!1},{name:"type",title:"Data Type",align:"center",type:"text",
validate:"required",editing:!1,itemTemplate:function(a,b){b=a.lastIndexOf(".")+1;a=0<b?a.substr(b):a;return'\x3cdiv class\x3d"profile_field_type"\x3e '+a+" \x3c/div\x3e"}},{name:"dataQualityScore",title:"Data Quality Score",type:"number",align:"center",width:76,validate:"required",itemTemplate:function(a,b){return 0<a?'\x3cdiv class\x3d"highlight_text positive_dqs"\x3e '+a+" \x3c/div\x3e":0>a?'\x3cdiv class\x3d"highlight_text negative_dqs"\x3e '+a+" \x3c/div\x3e":a}},{name:"synchronizable",title:"Synchronizable ",
align:"center",type:"CustomCheckBox",width:64,validate:"required",sorter:"string"},{title:"Controls",type:"control",width:80,editButton:!0,deleteButton:!1,itemTemplate:function(a,b){jsGrid.fields.control.prototype.itemTemplate.apply(this,arguments);var d=b.coreAttribute,g=b.attributeName;var h="Edit Event Name: "+g;$("\x3cbutton\x3e").data("attributeName",g).attr({class:"jsgrid-custom-button",title:h}).html('\x3ci class\x3d"fa fa-cogs event-set-rules" style\x3d"" aria-hidden\x3d"true"\x3e\x3c/i\x3e').click(function(k){console.log("setRules button ",
$(this).data("attributeName"));underDevelopment(this);k.stopPropagation()});var f="customGridEditbutton jsgrid-button jsgrid-edit-button";h=$("\x3cbutton\x3e").data("attributeName",g).attr({class:f,title:"Edit Attribute"}).click(function(k){console.log("Edit button ",$(this).data("attributeName"))});f="customGridDeletebutton jsgrid-button jsgrid-delete-button";g=$("\x3cbutton\x3e").data("attributeName",g).attr({class:f,title:"Delete Attribute"}).click(function(k){var n=$(this).data("attributeName");
d?notifyErrorMessage("The attribute \x3cb\x3e["+n+"]\x3c/b\x3e is the \x3cb\x3eattribute of system\x3c/b\x3e. You can not delete this attribute."):deleteEventMetricMetaData(n);k.stopPropagation()});f=$("\x3cdiv\x3e");d?f.attr("title","The attribute of system"):(f.addClass("editable_profile_attribute"),f.attr("title","Click to edit or delete"));f.append(h).append(g);return f}}]})}
function callDataQualityComputeJob(){LeoAdminApiUtil.callPostAdminApi("/cdp/system-config/call-data-quality-compute-job",{},function(c){0===c.httpCode&&""===c.errorMessage?notifySuccessMessage("\x3cb\x3eCall Data Quality Compute Job\x3c/b\x3e is called successfully!"):LeoAdminApiUtil.logErrorPayload(c)})}
function callSystemControlUpgrade(){notifySuccessMessage("The process to upgrade system is started");LeoAdminApiUtil.callPostAdminApi("/cdp/system-control/upgrade",{},function(c){0===c.httpCode&&""===c.errorMessage?($("#upgrade_system_logs").val(c.data),notifySuccessMessage("upgrade system is done, please wait for 10 seconds and reload page",function(){setTimeout(function(){location.reload(!0)},9999)})):LeoAdminApiUtil.logErrorPayload(c)})}
function resetSystemServiceInfo(c){var a=systemConfigMap[c];a.status=0;_.forOwn(a.configs,function(d,g){"string"===typeof d&&(a.configs[g]="")});$("#"+c+"_api_url").val("");$("#"+c+"_api_url_div").removeClass("highlight_text");$("#systemServiceStatus").prop("checked",!1);var b=function(d){null!=d?iziToast.success({title:"System Config",message:"The config of \x3cb\x3e"+a.name+"\x3c/b\x3e is reset successfully !",timeout:3E3}):console.error("saveSystemServiceInfo ",d)};c={objectJson:JSON.stringify(a)};
LeoAdminApiUtil.callPostAdminApi("/cdp/system-config/save",c,function(d){0===d.httpCode&&""===d.errorMessage?b(d.data):LeoAdminApiUtil.logErrorPayload(d)},b)}
function saveSystemServiceInfo(c){var a=$(c).data("id"),b=systemConfigMap[a],d={};$("#systemServiceConfigList input").each(function(){var h=$(this).attr("name"),f=$(this).attr("type");d[h]="number"===f?parseInt($(this).val()):"checkbox"===f?$(this).prop("checked"):$(this).val()});b.configs=d;b.status=$("#systemServiceStatus").prop("checked")?1:0;c={objectJson:JSON.stringify(b)};var g=function(h){null!=h?($("#dialogSetSystemConfigs").modal("hide"),iziToast.success({title:"System Config",message:"The config of \x3cb\x3e"+
b.name+"\x3c/b\x3e is saved OK!",timeout:3E3}),h=d.service_api_url,$("#"+a+"_api_url").val(h)):console.error("saveSystemServiceInfo ",h)};LeoAdminApiUtil.callPostAdminApi("/cdp/system-config/save",c,function(h){0===h.httpCode&&""===h.errorMessage?g(h.data):LeoAdminApiUtil.logErrorPayload(h)},g)}
function setSystemServiceInfo(c){var a=systemConfigMap[c];$("#dialogSetSystemConfigs").modal({backdrop:"static",keyboard:!1});$("#systemServiceName").text(a.name);$("#systemServiceDescription").text(a.description);$("#systemServiceSaveButton").data("id",c);$("#systemServiceStatus").prop("checked",a.status);var b=$("#systemServiceConfigList");b.empty();_.forOwn(a.configs,function(d,g){var h={inputName:g};h.inputType="number"===typeof d?"number":"boolean"===typeof d?"checkbox":"text";var f=_.template($("#tpl_config_row_item").html());
b.append(f(h));"checkbox"===h.inputType?b.find('input[name\x3d"'+g+'"]').prop("checked",d):b.find('input[name\x3d"'+g+'"]').val(d)})};