'use strict';const setupImageUrlInput=function(a,b,c){c=null==c||""===c?"https://cdn-icons-png.flaticon.com/512/3875/3875148.png":c;$(b).attr("src",c).error(function(){notifyErrorMessage($(this).attr("src")+" is not a valid image URL");$(this).attr("src","https://cdn-icons-png.flaticon.com/512/3875/3875148.png")});$(a).val(c).change(function(){var d=$(this).val().trim();d=""===d?"https://cdn-icons-png.flaticon.com/512/3875/3875148.png":d;$(b).attr("src",d)})};
function insertTextAtCursorInCodeMirror(a,b){a=a.getDoc();var c=a.getCursor();a.replaceRange(b,c)}function getHeadLinesImagsObject(){var a={};$("#headline_images .thumbnail").each(function(){var b=$(this).find("img").attr("src"),c="",d=$(this).find("p.editable");d.hasClass("editable-empty")||(c=d.text().trim());a[b]=c});return a}
const setupImageInputForContent=function(a,b){b=null==b||""===b?"https://cdn-icons-png.flaticon.com/512/3875/3875148.png":b;$(a).val(b).change(function(){var c=$(this).val().trim();c=""===c?"https://cdn-icons-png.flaticon.com/512/3875/3875148.png":c;if(0===$("#headline_images").find('img[src\x3d"'+c+'"]').length){var d={};d[c]="";loadHeadLineImageObjectToView(d,!1,!0)}});setTimeout(function(){if(0===$("#headline_images").show().find("img").length){var c={};c[b]="";loadHeadLineImageObjectToView(c,
!1,!0)}},1200)},updateBreadcrumbInAssetGroup=function(a,b){for(var c in a){var d=a[c],f=d.name;d=leoCdpRouterParams([c,d.assetType,d.name]);$("#tnv_Asset_Groups").attr("href","#calljs-leoCdpRouter('Asset_Groups','"+d+"')").text(f).attr("title",f)}$("#tnv_Asset_Group_Details").text(b)},updateBreadcrumbInAssetPost=function(a,b,c){for(var d in a){var f=a[d],g=f.name;f=leoCdpRouterParams([d,f.assetType,f.name]);$("#tnv_Asset_Groups").attr("href","#calljs-leoCdpRouter('Asset_Groups','"+f+"')").text(g).attr("title",
g)}for(var h in b)a=b[h].title,$("#tnv_Asset_Group_Details").attr("href","#calljs-leoCdpRouter('Asset_Group_Details','"+h+"')").text(a).attr("title",a);$("#tnv_Content_Post").text(c).attr("title",c)},getAssetEditorCallJs=function(a,b){return 2===a?"calljs-leoCdpRouter('Asset_Product_Item_Editor','"+b+"')":3===a?"calljs-leoCdpRouter('Asset_Service_Item_Editor','"+b+"')":4===a||6===a||7===a?"calljs-leoCdpRouter('Asset_Template_Editor','"+b+"')":13===a?"calljs-leoCdpRouter('Asset_Feedback_Form_Editor','"+
b+"')":15===a?"calljs-leoCdpRouter('Asset_Short_Link_Editor','"+b+"')":16===a?"calljs-leoCdpRouter('Asset_Presentation_Editor','"+b+"')":"calljs-leoCdpRouter('Asset_Content_Editor','"+b+"')"};function getYouTubeVideoId(a){var b,c="";if(b=a.match(/(\?|&)v=([^&#]+)/))c=b.pop();else if(b=a.match(/(\.be\/)+([^\/]+)/))c=b.pop();else if(b=a.match(/(embed\/)+([^\/]+)/))c=b.pop().replace("?rel\x3d0","");return c.split("\x26")[0]}
function checkPostTypeAndSetupMediaEditor(a,b){console.log("checkPostTypeAndSetupMediaEditor postType "+a);if(1===a||2===a||6===a||8===a||9===a)$("#content_div").html(editorViewTpl),window.trixElement=document.querySelector('trix-editor[input\x3d"mediaInfo"]'),trixElement.editor.insertHTML(b),$(trixElement).focus(function(){trixElement=$(this)[0]}),trixElement.addEventListener("trix-attachment-add",function(d){});else{var c=$(documentUrlViewTpl).val(b);$("#content_div").html(c);c.change(function(){renderPostMediaInfo(c.val().trim())})}}
function normalizeMediaHtml(a){a=$("\x3cdiv/\x3e").html(a);a.find("img").each(function(){320<parseInt($(this).attr("width"))&&$(this).attr("style","height:100%!important;width:100%!important;object-fit:contain!important")});return a.html()}
function toggleRawHtmlEditor(a){if("hidden"===$(a).data("visibilty")){var b=$("#raw_media_container").show().width()-10;$("#content_div").hide();var c=$("#mediaInfo").val();rawHtmlEditor.setValue(c);CodeMirrorAutoFormat(rawHtmlEditor);$(a).data("visibilty","visible");rawHtmlEditor.setSize(b,800);$(a).html('\x3ci class\x3d"fa fa-fw fa-code"\x3e\x3c/i\x3e Hide HTML Editor')}else $("#raw_media_container").hide(),$("#content_div").show(),trixElement.editor.loadHTML(rawHtmlEditor.getValue()),$(a).data("visibilty",
"hidden"),rawHtmlEditor.setSize(null,1),$(a).html('\x3ci class\x3d"fa fa-fw fa-code"\x3e\x3c/i\x3e Show HTML Editor')}function newAssetItemEditor(a,b,c){b=leoCdpRouterParams(["",b,c]);location.hash=getAssetEditorCallJs(a,b)}
function createAssetItemFromLeoBot(a,b,c){console.log(c);LeoAdminApiUtil.getSecuredData(baseLeoAdminUrl+"/cdp/asset-group/get-default",{context:a},function(d){0===d.httpCode&&""===d.errorMessage?(d=d.data,newAssetItemEditor(d.assetType,d.id,d.categoryIds[0]),setTimeout(function(){$("#asset_item_title").val(b).focus();"object"===typeof trixElement&&"content"===a?trixElement.editor.loadHTML(c):"presentation"===a&&"function"===typeof formatMarkdownToPresentation&&formatMarkdownToPresentation(c)},1500)):
LeoAdminApiUtil.logErrorPayload(d)})}function gotoAssetItemView(a,b,c){a=leoCdpRouterParams([a,b,c]);location.hash="calljs-leoCdpRouter('Asset_Content_View','"+a+"')"}function getFeedbackFormTypeAsString(a){return 0===a?"SURVEY":1===a?"CONTACT":2===a?"RATING":3===a?"CES":4===a?"CSAT":5===a?"NPS":""}function refreshCodeMirrorEditor(){$(".CodeMirror").each(function(a,b){b.CodeMirror.refresh();b.CodeMirror.execCommand("selectAll")})}
function initEmbeddedFeedbackForm(a,b,c,d){d="number"===typeof d?d:350;var f=c.title,g="leoFeedbackForm_"+c.id,h="https://"+baseLeoObserverDomain+"/webform?tplid\x3d",n=getFeedbackFormTypeAsString(c.templateType),p=n+" Form",l=$("#feedback_form_code_holder");l.css("visibility","hidden");$("#feedback_form_code_holder .CodeMirror").remove();var m=l.find("textarea.code"),k=CodeMirror.fromTextArea(m[0],{mode:"htmlmixed",lineNumbers:!0,styleActiveLine:!0,matchBrackets:!0,readOnly:!1});k.setSize(null,460);
setTimeout(function(){$("#"+b+" .eventName").text(p);var q=0<f.indexOf("Rating")?100:800,e=m.val().trim().replaceAll("__feedbackFormTitle__",f);e=e.replaceAll("__eventName__",p);e=e.replaceAll("__scriptNodeId__",g);e=e.replaceAll("__tplFeedbackType__",n);e=e.replaceAll("__feedbackFormFullUrl__",h);e=e.replaceAll("__iFrameHeight__",d);e=e.replaceAll("__observerId__",a);e=e.replaceAll("__iframeHeight__",q);e=e.replaceAll("__templateId__",c.id);k.getDoc().setValue('\x3cscript id\x3d"'+g+'" \x3e\n'+e+
"\n\x3c/script\x3e");k.refresh();k.execCommand("selectAll");addHandlerCopyCodeButton(m,"#"+b+" button.btn-copy-code");l.css("visibility","visible")},300)};