'use strict';const BASE_URL_LEOBOT=baseLeoBotUrl+"/ask",IS_LEO_BOT_READY=""!==dnsDomainLeoBot;var leoBotActionList=[];leoBotActionList.push({text:"Create short URL",value:"Create short URL"});leoBotActionList.push({text:"Show segments",value:"Show segments"});leoBotActionList.push({text:"Search profile",value:"Search profile"});
IS_LEO_BOT_READY&&(leoBotActionList.push({text:"Ask question",value:"Ask question"}),leoBotActionList.push({text:"Write content",value:"Write content"}),leoBotActionList.push({text:"Create presentation",value:"Create presentation"}));window.leoBotUI=!1;function getBotUI(){!1===window.leoBotUI&&(window.leoBotUI=new BotUI("LEO_ChatBot_Container"));return window.leoBotUI}
function initLeoChatBot(a){$("#leoChatBotDialog").modal({backdrop:"static",keyboard:!1});getBotUI().action.hide();getBotUI().message.removeAll();leoBotSayHello()}
var closeLeoChatBotDialog=function(){getBotUI().action.hide();getBotUI().message.removeAll().then(function(){$("#leoChatBotDialog").modal("hide")})},leoBotDoAction=function(a){getBotUI().message.add({human:!0,content:a}).then(function(){"Create short URL"===a?setTimeout(leoBotCreateShortUrl,2E3):"Show segments"===a?setTimeout(leoBotBuildSegment,2E3):"Search profile"===a?leoBotSearchProfiles():"Write content"===a?leoBotWriteContent():"Create presentation"===a?leoBotCreatePresentation():leoBotPromptQuestion()})},
leoBotSayHello=function(){var a="Hello "+currentUserProfile.displayName+", how can LEO help you ?";getBotUI().message.bot(a).then(function(){return getBotUI().action.button({delay:1E3,addMessage:!1,action:leoBotActionList})}).then(function(b){leoBotDoAction(b.value)})},leoBotPromptQuestion=function(a){getBotUI().action.text({delay:"number"===typeof a?a:800,action:{icon:"question-circle",cssClass:"leobot-question-input",value:"",placeholder:"Give me a question"}}).then(function(b){b=b.value;leoBotAskServer("ask",
b,b)})},leoBotWriteContent=function(){var a=function(b){getBotUI().action.text({delay:500,action:{icon:"question-circle",cssClass:"leobot-question-input",value:"",placeholder:"Give me the purpose of content"}}).then(function(c){leoBotAskServer("content",b,"Write a blog post about "+b,", the purpose of blog post is "+c.value)})};getBotUI().action.text({delay:500,action:{icon:"question-circle",cssClass:"leobot-question-input",value:"",placeholder:"Give me the title of content"}}).then(function(b){a(b.value)})},
leoBotCreatePresentation=function(){var a=function(b){getBotUI().action.text({delay:500,action:{icon:"question-circle",cssClass:"leobot-question-input",value:"",placeholder:"Give me the number of slides in presentation"}}).then(function(c){c=parseInt(c.value);isNaN(c)?(notifyErrorMessage(c+" is not a number !"),a(b)):leoBotAskServer("presentation",b,'Create a presentation about "'+b+'" '," in "+c+' slides,  the heading of each slide must begin with "##" ',"markdown")})};getBotUI().action.text({delay:500,
action:{icon:"question-circle",cssClass:"leobot-question-input",value:"",placeholder:"Give me a title of presentation"}}).then(function(b){a(b.value)})},leoBotBuildSegment=function(){location.hash="calljs-leoCdpRouter('Segment_Management')";closeLeoChatBotDialog()},leoBotSearchProfiles=function(){getBotUI().action.text({delay:500,action:{icon:"question-circle",cssClass:"leobot-question-input",placeholder:"Give me a name, email or phone of customer"}}).then(function(a){a=Base64.encode(a.value);location.hash=
"calljs-leoCdpRouter('Customer_Profile_Search','"+a+"')";closeLeoChatBotDialog()})},leoBotCreateShortUrl=function(){LeoAdminApiUtil.getSecuredData(window.baseLeoAdminUrl+"/cdp/asset-group/list-by-asset-type",{assetType:"15"},function(a){"object"===typeof a.data[0]?(a=a.data[0],a=leoCdpRouterParams(["",a.id,a.categoryIds[0]]),location.hash="calljs-leoCdpRouter('Asset_Short_Link_Editor','"+a+"')",closeLeoChatBotDialog()):LeoAdminApiUtil.logErrorPayload(a)})},leoBotCreateNewItem=function(a,b,c){var e=
function(){$("#asset_item_title").val(b).focus();var d=window.trixElement;"object"===typeof d&&"content"===a?d.editor.loadHTML(c):"presentation"===a&&"function"===typeof formatMarkdownToPresentation&&formatMarkdownToPresentation(c)};LeoAdminApiUtil.getSecuredData(baseLeoAdminUrl+"/cdp/asset-group/get-default",{context:a},function(d){0===d.httpCode&&""===d.errorMessage?(d=d.data,newAssetItemEditor(d.assetType,d.id,d.categoryIds[0]),setTimeout(e,2E3)):LeoAdminApiUtil.logErrorPayload(d)})},leoBotShowAnswer=
function(a,b){getBotUI().message.add({human:!1,cssClass:"leobot-answer",content:a,type:"html"}).then(function(){$("div.botui-message").find("a").attr("target","_blank");b()})},leoBotAskServer=function(a,b,c,e,d){"string"===typeof e&&(c+=e);d="string"===typeof d?d:"html";if(1<b.length&&"exit"!==b){var l=function(f){"ask"===a?leoBotShowAnswer(f,function(){leoBotPromptQuestion(120<f.length?6E3:2E3)}):leoBotShowAnswer(f,function(){var h="Would you like to write a blog post?";"presentation"===a&&(h="Would you like to create a presentation ?");
getBotUI().message.bot(h).then(function(){return getBotUI().action.button({delay:1E3,action:[{text:"Yes",value:"yes"},{text:"No",value:"no"}]})}).then(function(g){"yes"===g.value?getBotUI().message.bot("Okay").then(function(){closeLeoChatBotDialog();leoBotCreateNewItem(a,b,f)}):closeLeoChatBotDialog()})})};showChatBotLoader().then(function(f){var h=currentUserProfile.userLogin,g={prompt:c,question:b,usersession:getUserSession()};g.userlogin=h;g.answer_in_format=d;g.answer_in_language=$("#leobot_answer_in_language").val();
LeoAdminApiUtil.callPostApi(BASE_URL_LEOBOT,g,function(k){getBotUI().message.remove(f);"string"===typeof k.answer?l(k.answer):k.error?(notifyErrorMessage(k.answer),closeLeoChatBotDialog()):notifyErrorMessage("LEO BOT is getting a system error !")},closeLeoChatBotDialog)})}else closeLeoChatBotDialog()},showChatBotLoader=function(){return getBotUI().message.add({loading:!0,content:""})},recommendContentIdeas=function(a){a=document.getElementById("suggestedVideoTpl").innerHTML;a=Handlebars.compile(a)({title:"My New Post",
body:"This is my first post!"});getBotUI().message.bot({delay:500,content:a});setTimeout(function(){$("#suggestedVideoCarousel").on("slid.bs.carousel",function(){var b=getActiveVideoInfo();console.log(b);$("#playlist_holder").empty();leoPlayVideoReport(b.video)})},500)};function getRandomInt(a,b){a=Math.ceil(a);b=Math.floor(b);return Math.floor(Math.random()*(b-a+1))+a}
function leoPlayVideoReport(a){var b=getRandomInt(1,1E5)+"_"+(new Date).getTime(),c=document.createElement("div");c.setAttribute("id",b);c.setAttribute("class","videoholder");document.getElementById("playlist_holder").appendChild(c);MediaPlayerOne.create(!0,b,a,"",[],3,[],function(e){setTimeout(function(){e.muted(!1)},1E3)})}function getActiveVideoInfo(){var a=$("#suggestedVideoCarousel .active"),b=a.data("title");a=a.data("video");return{title:b,video:a}};