'use strict';const eventDataTypes=[{name:"First-party Data",id:1},{name:"Second-party Data",id:2},{name:"Third-party Data",id:3}],journeyStages=[{name:"AWARENESS",id:1},{name:"ATTRACTION",id:2},{name:"ASK",id:3},{name:"ACTION",id:4},{name:"ADVOCACY",id:5}],journeyStagesMap={1:"AWARENESS",2:"ATTRACTION",3:"ASK",4:"ACTION",5:"ADVOCACY"},scoringModels=[{name:"LEAD",id:1},{name:"PROSPECT",id:2},{name:"ENGAGEMENT",id:3},{name:"DATA_QUALITY",id:4},{name:"ACQUISITION",id:5},{name:"LIFETIME_VALUE",id:6},
{name:"CX_EFFORT",id:7},{name:"CX_SATISFACTION",id:8},{name:"CX_FEEDBACK",id:9},{name:"CX_PROMOTER",id:10},{name:"CREDIT_SCORING",id:11},{name:"CX_LOYALTY",id:12},{name:"CX_DETRACTOR",id:13}],CheckBoxIcon=function(a){jsGrid.Field.call(this,a)};
CheckBoxIcon.prototype=new jsGrid.Field({sorter:function(a,b){return 0},itemTemplate:function(a){return getCheckedBoxIcon(a)},insertTemplate:function(a){return this._insertCode=a},editTemplate:function(a){return this._editCode=a},insertValue:function(){return this._insertCode},editValue:function(){return this._editCode}});jsGrid.fields.CheckBoxIcon=CheckBoxIcon;var CustomCheckBox=function(a){jsGrid.Field.call(this,a)};
CustomCheckBox.prototype=new jsGrid.Field({sorter:function(a,b){return 0},itemTemplate:function(a){return'\x3cdiv class\x3d"text-center"\x3e'+getCheckedBoxIcon(a)+"\x3c/div\x3e"},insertTemplate:function(a){var b=$('\x3cinput type\x3d"checkbox" \x3e');a&&b.attr("checked","checked");return this._insertCheckbox=$('\x3cdiv class\x3d"text-center"\x3e'+b[0].outerHTML+"\x3c/div\x3e")},editTemplate:function(a){var b=$('\x3cinput type\x3d"checkbox" \x3e');a&&b.attr("checked","checked");return this._editCheckbox=
$('\x3cdiv class\x3d"text-center"\x3e'+b[0].outerHTML+"\x3c/div\x3e")},insertValue:function(){return 0<this._insertCheckbox.find("input:checked").length},editValue:function(){return 0<this._editCheckbox.find("input:checked").length}});jsGrid.fields.CustomCheckBox=CustomCheckBox;const UrlLink=function(a){jsGrid.Field.call(this,a)};
UrlLink.prototype=new jsGrid.Field({sorter:function(a,b){return 0},itemTemplate:function(a){var b=45<a.length?a.substring(0,45)+"...":a;return 0===a.indexOf("https://plus.codes/")?'\x3ca href\x3d"javascript:" style\x3d"font-size:11.5px" data-url\x3d"'+a+'" onclick\x3d"openLocationUrl(this)" \x3e'+b+"\x3c/a\x3e":'\x3ca href\x3d"'+a+'"  style\x3d"font-size:11.5px" target\x3d"_blank" \x3e'+b+"\x3c/a\x3e"},insertTemplate:function(a){return this._insertCode=a},editTemplate:function(a){return this._editCode=
a},insertValue:function(){return this._insertCode},editValue:function(){return this._editCode}});jsGrid.fields.UrlLink=UrlLink;const BoldText=function(a){jsGrid.Field.call(this,a)};BoldText.prototype=new jsGrid.Field({sorter:function(a,b){return 0},itemTemplate:function(a){return"\x3cb\x3e"+a+"\x3c/b\x3e"},insertTemplate:function(a){return this._insertCode=a},editTemplate:function(a){return this._editCode=a},insertValue:function(){return this._insertCode},editValue:function(){return this._editCode}});
jsGrid.fields.BoldText=BoldText;
const refreshJourneyMapView=function(){currentJourneyMapId&&(location.hash="#calljs-leoCdpRouter('Data_Journey_Map','"+currentJourneyMapId+"','_refresh_"+(new Date).getTime()+"')")},updateJourneyMap=function(a){a={touchpointHubJson:JSON.stringify($("#touchpoint_hub_table").jsGrid("option","data")),journeyMapId:currentJourneyMapId};LeoAdminApiUtil.callPostAdminApi("/cdp/journeymap/save",a,function(b){0===b.httpCode&&""===b.errorMessage?""!=b.data?refreshJourneyMapView():console.error("updateJourneyMap ",
rs):LeoAdminApiUtil.logErrorPayload(b)})},loadFeedbackTemplateItems=function(a,b){LeoAdminApiUtil.getSecuredData("/cdp/asset-item/asset-templates",{obsid:a},function(e){cxFeedbackTemplates=e.data.cxFeedbackTemplates;landingPageTemplates=e.data.landingPageTemplates;b()})},loadEventMetrics=function(){LeoAdminApiUtil.getSecuredData("/cdp/funnel/event-metrics",{},function(a){eventMetrics=a.data})};
var loadJourneyTemplate=function(){iziToast.info({title:"Information",message:"This function is under development and is not yet available"})},jsGridItemUrlTemplate=function(a){a=a.trim();a=$("\x3ca\x3e").attr("href","javascript:").attr("title",a).attr("onclick","openUrlInNewTab(event,this)").text(a);return $('\x3cdiv class\x3d"long_url_holder" \x3e\x3c/div\x3e').append(a)};
function initJourneyMapNameEditor(){var a="Journey Map: "+(new Date).toDateString(),b=function(d){LeoAdminApiUtil.callPostAdminApi("/cdp/journeymap/update-name",{journeyMapName:d,journeyMapId:currentJourneyMapId},function(c){0===c.httpCode&&""===c.errorMessage?(iziToast.success({title:"Data Journey Map",message:"\x3cb\x3e"+d+"\x3c/b\x3e is updated successfully!",timeout:2500}),loadJourneyMapList(!0)):LeoAdminApiUtil.logErrorPayload(c)})},e=$("#journeyMapName");$("#journeyMapNameEditor").blur(function(){var d=
$(this).val().trim();d=""===d?a:d;$("#journeyMapNameEditor").hide();e.text()!==d?(e.text(d).show(),b(d)):e.show()});$("#journeyMapNameEditor").keyup(function(d){"13"==(d.keyCode?d.keyCode:d.which)&&(d=$(this).val().trim(),d=""===d?a:d,$("#journeyMapNameEditor").hide(),e.text()!==d?(e.text(d).show(),b(d)):e.show())})}
function saveJourneyDataAuthorization(){var a=$("#authorizedJourneyViewers").val()||[],b=$("#authorizedJourneyEditors").val()||[];a={authorizedViewers:a,authorizedEditors:b,journeyMapId:currentJourneyMapId};a.updateAllProfilesInJourney=!0===$("#updateAllProfilesInJourney").prop("checked");LeoAdminApiUtil.callPostAdminApi("/cdp/journeymap/update-data-authorization",a,function(e){e.data===currentJourneyMapId?iziToast.success({title:"Data Journey Map",message:"\x3cb\x3eThe Data Journey Authorization of "+
$("#journeyMapName").text()+"\x3c/b\x3e is updated successfully!",timeout:3E3}):LeoAdminApiUtil.logErrorPayload(e)})}function loadJourneyStagesList(a){var b=$("#journeyStagesList");journeyStages.forEach(function(e){b.append('\x3coption value\x3d"'+e.id+'" \x3e'+e.name+"\x3c/option\x3e")});b.val("1").change();b.chosen({width:"100%",no_results_text:"Oops, nothing found!"}).trigger("chosen:updated").change(function(){"function"===typeof a&&a($(this).val())})}
function loadJourneyMapList(a,b,e,d){var c=$("#journeyMapList");!0===a&&c.find("option").remove().trigger("chosen:updated");LeoAdminApiUtil.getSecuredData("/cdp/journeymap/list-all",{},function(f){0===f.httpCode&&""===f.errorMessage?(f=f.data,!0===e&&c.append('\x3coption value\x3d"" \x3e All Data from All Journeys\x3c/option\x3e'),f.forEach(function(l){c.append('\x3coption value\x3d"'+l.id+'" \x3e'+l.name+"\x3c/option\x3e")}),"string"===typeof currentJourneyMapId?c.val(currentJourneyMapId).change():
c.val("").change(),"function"===typeof d&&d(c.val(),c.find("option:selected").text()),c.chosen({width:"100%",no_results_text:"Oops, nothing found!"}).trigger("chosen:updated").change(function(){if("function"===typeof b){var l=$(this).val(),n=$(this).find("option:selected").text();b(l,n);"string"===typeof currentJourneyMapId&&(currentJourneyMapId=l)}else window.currentJourneyMapId=$(this).val(),refreshJourneyMapView()})):LeoAdminApiUtil.logErrorPayload(f)})}
function editJourneyMapName(){var a=$("#journeyMapName");$("#journeyMapNameEditor").val(a.text()).show().focus();a.hide()}function createNewJourneyMap(){$("#dialogCreateNewJourneyMap").modal({backdrop:"static",keyboard:!1})}
function saveNewJourneyMap(){var a=$("#newJourneyMapName").val();5>=a.length?iziToast.error({title:"Journey Map Creation",message:"The journey map \x3cb\x3e"+a+"\x3c/b\x3e is too short, please enter at least 6 characters !",timeout:3E3}):($("#dialogCreateNewJourneyMap").modal("hide"),setTimeout(function(){LeoAdminApiUtil.callPostAdminApi("/cdp/journeymap/create-new",{journeyMapName:a},function(b){0===b.httpCode&&""===b.errorMessage?"string"===typeof b.data&&(currentJourneyMapId=b.data,iziToast.success({title:"Journey Map Creation",
message:"The journey map \x3cb\x3e"+a+"\x3c/b\x3e has been created created successfully !",timeout:3E3}),refreshJourneyMapView()):LeoAdminApiUtil.logErrorPayload(b)})},1E3))}
function deleteCurrentJourneyMap(){if("string"===typeof currentJourneyMapId&&"id_default_journey"!=currentJourneyMapId){var a=$("#journeyMapList").find("option:checked").text();$("#delete_callback").val("");$("#confirmDeleteParentChildDialog").modal({focus:!0});$("#deleteChildItemMsg").text("Delete all touchpoint hubs and related data in this journey map!");$("#deleteChildItemCheckbox").prop("checked",!0);$("#deleteChildItem").show();var b="deleteJourneyMap"+currentJourneyMapId;window[b]=function(){var e=
baseLeoAdminUrl+"/cdp/journeymap/delete";$("#deleteChildItemCheckbox").is(":checked");LeoAdminApiUtil.callPostAdminApi(e,{journeyMapId:currentJourneyMapId},function(d){0===d.httpCode?!0===d.data?($("#deleteChildItem").hide(),$("#deleteChildItemMsg").text(""),iziToast.success({title:"OK",message:'Successfully deleted the journey map "'+a+'"',onClosing:function(c,f,l){currentJourneyMapId="id_default_journey";refreshJourneyMapView()}})):iziToast.error({title:"Error",message:d.data,onClosing:function(c,
f,l){locatio.href="/admin"}}):($("#error-on-save").html(d.errorMessage).show().delay(5E3).fadeOut("slow"),LeoAdminApiUtil.logErrorPayload(d))})};$("#delete_parent_callback").val(b);$("#deletedParentInfoTitle").text(a);$("#deletedParentInfoMsg").text("Do you want to delete the journey map ?")}}
var loadJourneyMap=function(a,b,e){LeoAdminApiUtil.getSecuredData("/cdp/journeymap/get",{id:a},function(d){if(0<d.errorCode)iziToast.error({title:"Data Journey Map",message:d.errorMessage});else{var c=d.data.journeyMap;d=c.defaultMetricName;var f=c.name,l=c.journeyStages,n=c.journeyLinks,q=c.journeyNodes;c=c.touchpointHubMap;$(e).text(f);renderJourneyFlowChart(b,d,l,q,n,c)}})},loadJourneyMapAndTouchpointHubs=function(a,b,e,d,c){LeoAdminApiUtil.getSecuredData("/cdp/journeymap/get",{id:a},function(f){if(0<
f.errorCode)iziToast.error({title:"Data Journey Map",message:f.errorMessage});else{var l=f.data.touchpointHubTypes,n=f.data.journeyMap,q=n.defaultMetricName,g=n.name,k=n.journeyStages,m=n.journeyLinks,w=n.journeyNodes,r=n.touchpointHubIndex,u=n.touchpointHubMap;$(e).text(g);loadSystemUsersForDataAuthorization(n,$("#authorizedJourneyViewers"),$("#authorizedJourneyEditors"));"function"===typeof c&&c(w.length);renderJourneyFlowChart(b,q,k,w,m,u);n=[];for(g in u)q=r[g],k=u[g],k.index=q+1,n[q]=k;g=[];
for(r=1;30>=r;r++)g.push({Name:"[ "+r+" ]",Id:r});var x=[];Object.keys(l).forEach(h=>{var p=parseInt(h);0<p&&x.push({typeName:l[h].replaceAll("_"," "),type:p})});r=f.canInsertData;q=f.canEditData;f=f.canDeleteData;var v=-1;$(d).jsGrid({width:"100%",height:"auto",inserting:r,editing:q,sorting:!0,paging:!1,deleteConfirm:function(h){return"The touchpoint hub ["+h.name+"] will be removed. Are you sure?"},data:n,onItemInserting:function(h){console.log(h.item);var p=h.item.url,t=h.item.type;null!=u[h.item.name]?
(h.cancel=!0,iziToast.error({title:"Data Journey Map",message:h.item.name+" is duplicated, please enter a different name !"})):!isValidURL(p)&&30>=t?(h.cancel=!0,iziToast.error({title:"Data Journey Map",message:p+" is not valid URL !"})):30==t?(h.cancel=!0,iziToast.error({title:"Data Journey Map",message:"Can not have more than one data observer !"})):0<v&&(h.item.index=v,v=-1)},onItemUpdating:function(h){console.log(h.item);var p=h.item,t=p.type,y=p.name;p=p.url;30!=t?isValidURL(p)||31==t||(h.cancel=
!0,iziToast.error({title:"Data Journey Map",message:p+" is not valid URL !"})):(h.cancel=!0,iziToast.error({title:"Data Journey Map",message:y+" is read-only touchpoint, you can not update it !"}))},onItemInserted:function(h){iziToast.success({title:"Data Journey Map",message:h.item.name+" is inserted successfully!",timeout:2500,onClosed:function(){updateJourneyMap(!0)}})},onItemUpdated:function(h){iziToast.success({title:"Data Journey Map",message:h.item.name+" is updated successfully!",timeout:2500,
onClosed:function(){updateJourneyMap(!1)}})},onItemDeleting:function(h){var p=h.item,t=p.name;0<p.type&&30>p.type||(h.cancel=!0,iziToast.error({title:"Data Journey Map",message:t+" is read-only touchpoint hub, you can not delete it !"}))},onItemDeleted:function(h){u[h.item.name]=null;LeoAdminApiUtil.callPostAdminApi("/cdp/touchpointhub/delete",{id:h.item.id},function(p){0===p.httpCode&&""===p.errorMessage?iziToast.success({title:"Data Journey Map",message:h.item.name+" is deleted successfully!",timeout:2500,
onClosed:function(){updateJourneyMap(!1)}}):LeoAdminApiUtil.logErrorPayload(p)})},onRefreshed:function(h){var p=h.grid._insertRow;h=h.grid._bodyGrid;console.log(p);v=parseInt($(".jsgrid-grid-body tbody tr:last td:first").text())+1;$(p).find("td:first").text(v);$("\x3ctfoot\x3e\x3c/tfoot\x3e").appendTo(h).append(p)},fields:[{name:"index",title:"",type:"number",width:15,editing:!1,align:"center"},{name:"name",title:"Name",type:"text",width:60,validate:"required",align:"center",css:"touchpoint_hub_name"},
{name:"type",title:"Type",type:"select",items:x,valueField:"type",textField:"typeName",width:58,css:"datatable_text",insertTemplate:function(){var h=jsGrid.fields.select.prototype.insertTemplate.call(this);h.change(function(){30==$(this).val()&&(iziToast.error({title:"Data Journey Map",message:"Can not have more than one data observer !"}),$("#touchpoint_hub_table").jsGrid("cancelEdit"))});return h},editTemplate:function(h){var p=jsGrid.fields.select.prototype.editTemplate.call(this,h);return 30==
h?"CUSTOMER DATA HUB":p}},{name:"journeyLevel",title:"Level",type:"select",items:g,valueField:"Id",textField:"Name",width:24},{name:"firstPartyData",title:"First-party Data",type:"CustomCheckBox",validate:"required",width:34,align:"center"},{name:"url",title:"URL",type:"text",itemTemplate:jsGridItemUrlTemplate,validate:"required",align:"center"},{type:"control",deleteButton:f,width:30}]});r&&q||$("#touchpoint_hub_table").find(".jsgrid-button").click(errorNoAuthorization)}})};
const getJsCodeEventTrackingFunctions=function(a){var b="",e=0;eventMetrics.forEach(function(c){if(!0===c.showInObserverJS){e++;var f="#leo-tracking-view-event-code-tpl";3===c.journeyStage||4===c.journeyStage||5===c.journeyStage?f=6===c.scoreModel?"#leo-tracking-conversion-event-code-tpl":"#leo-tracking-action-event-code-tpl":6===c.journeyStage&&(f="#leo-tracking-feedback-event-code-tpl");f=_.template($(f).html());c={counter:e,eventMetricId:c.id,eventMetricName:c.eventLabel.replaceAll(" ","")};b+=
f(c)}});if(a&&(a=$("#measurement_id_GA4").val().trim(),""!==a)){var d=_.template($("#google-analytics-javascript-tpl").html());b+="\n"+d({measurementId:a})+"\n"}return b},getTrackingJsCode=function(a){a=JSON.parse(decodeURIComponent($(a).data("json")));var b=a.id,e=a.name,d=a.type;a=a.dataSourceUrl;var c=window.baseLeoObserverDomain,f=window.baseStaticDomain;if(0<d&&12>d){$("#webDataObserverCodeDialog").modal({backdrop:"static",keyboard:!1});$("#code_holder .CodeMirror").remove();d=$("#webDataObserverCodeDialog .code")[0];
var l=CodeMirror.fromTextArea(d,{mode:"htmlmixed",lineNumbers:!0,styleActiveLine:!0,matchBrackets:!0,readOnly:!1});l.setSize(null,474);setTimeout(function(){var n=function(){var q=$("#leo_observer_auto_track").is(":checked"),g=$("#leo_observer_auto_collect_UTM").is(":checked"),k=$("#leo_observer_auto_collect_GA4").is(":checked");k=getJsCodeEventTrackingFunctions(k);var m=$("#webDataObserverCodeDialog .code").val().trim().replace("__leoObserverId__",b);m=m.replace("__tpHubName__",e);m=m.replace("__leoObserverDomain__",
c);m=m.replace("__staticFileDomain__",f);m=m.replace("__eventTrackingFunctions__",k);m=q?g?m.replace("__autoTrackingFunctions__","LeoObserver.recordEventPageView(parseDataUTM())"):m.replace("__autoTrackingFunctions__","LeoObserver.recordEventPageView()"):m.replace("__autoTrackingFunctions__","// No auto tracking, please call it yourself");l.getDoc().setValue("\x3cscript\x3e\n"+m+"\n\x3c/script\x3e");l.refresh();l.execCommand("selectAll")};$("#leo_observer_auto_track, #leo_observer_auto_collect_UTM").change(function(){n()});
$("#btn_ok_auto_collect_GA4").click(function(){n()});n();addHandlerCopyCodeButton("#webDataObserverCodeDialog .code","#webDataObserverCodeDialog button.btn-copy-code")},350);d=$("#testObserverChromeExtBtn");d.attr({leoObserverId:b,leoObserverDomain:c,staticFileDomain:f,dataSourceUrl:a});d.click(function(){var n=$(this).attr("leoObserverId"),q=$(this).attr("leoObserverDomain"),g=$(this).attr("staticFileDomain"),k=$(this).attr("dataSourceUrl");k=0<k.indexOf("?")?k:k+"?";window.open(k+"_leoObserverLogDomain\x3d"+
q+"\x26_leoObserverId\x3d"+n+"\x26_leoObserverCdnDomain\x3d"+g,"_blank")})}else notifyErrorMessage("Can not get tracking code of offline touchpoint, please use QR code")},getCxFeedbackJsCode=function(a){a=JSON.parse(decodeURIComponent($(a).data("json")));var b=a.id;a=a.type;30>a?loadFeedbackTemplateItems(b,function(){var e=function(f){var l="https://"+baseUploadDomain+f.qrCodeUrl.replace("./","/");$("#cx_qrHrefUrl").attr("href",l);$("#cx_qrImgSrc").attr("src",l);$("#cx_qrCodeImageURL").val(l);f="https://"+
baseLeoObserverDomain+"/webform?tplid\x3d"+f.id+"\x26obsid\x3d"+b;$("#cx_qrFormURL").val(f)};if(0===$("#feedbackTemplateSelector option").length&&0<cxFeedbackTemplates.length)for(var d in cxFeedbackTemplates){var c='\x3coption value\x3d"'+d+'" \x3e'+cxFeedbackTemplates[d].title+"\x3c/option\x3e";$("#feedbackTemplateSelector").append(c)}$("#dialogEmbeddedCxFeedbackForm").modal({backdrop:"static",keyboard:!1});$("#feedbackTemplateSelector").val("0").change();initEmbeddedFeedbackForm(b,"dialogEmbeddedCxFeedbackForm",
cxFeedbackTemplates[0]);e(cxFeedbackTemplates[0]);$("#feedbackTemplateSelector").chosen({width:"100%",no_results_text:"Oops, nothing found!"}).trigger("chosen:updated").change(function(){var f=parseInt($(this).val());f=cxFeedbackTemplates[f];initEmbeddedFeedbackForm(b,"dialogEmbeddedCxFeedbackForm",f);e(f)})}):notifyErrorMessage("Can not get feedback code for the touchpoint hub type \x3d "+a)},getWebLeadFormJsCode=function(a){a=JSON.parse(decodeURIComponent($(a).data("json")));var b=a.id,e=a.name;
a=a.type;if(0<a&&12>a){$("#webLeadFormCodeDialog").modal({backdrop:"static",keyboard:!1});$("#code_holder .CodeMirror").remove();a=$("#webLeadFormCodeDialog .code")[0];var d=CodeMirror.fromTextArea(a,{mode:"htmlmixed",lineNumbers:!0,styleActiveLine:!0,matchBrackets:!0,readOnly:!0});d.setSize(null,480);setTimeout(function(){var c=$("#webLeadFormCodeDialog .code").val().trim().replace("__leoObserverId__",b);c=c.replace("__tpHubName__",e);c=c.replace("__LeoObserverDomain__",baseLeoObserverDomain);d.getDoc().setValue("\x3cscript\x3e\n"+
c+"\n\x3c/script\x3e");d.refresh();d.execCommand("selectAll")},350)}},getQrImageFormCode=function(a){a=decodeURIComponent($(a).data("json"));a=JSON.parse(a);console.log("getQrImageFormCode ",a);var b=a.qrCodeData,e=window.baseUploadDomain;$("#qrImageFormCodeDialog").modal({backdrop:"static",keyboard:!1});a=b.landingPageUrl;var d=b.trackingUrl;b="https://"+e+b.qrCodeImage.replace("./","/");$("#qrHrefUrl").attr("href",b);$("#qrImgSrc").attr("src",b);$("#qrTouchpointHubURL").val(a);$("#qrTrackingURL").val(d);
$("#qrCodeImageURL").val(b)},getRecommenderJsCode=function(a){a=JSON.parse(decodeURIComponent($(a).data("json")));console.log("getRecommenderJsCode ",a);var b=a.id,e=a.name;a=a.type;if(0<a&&12>a){$("#dialogEmbeddedRecomender").modal({backdrop:"static",keyboard:!1});$("#dialogEmbeddedRecomender .CodeMirror").remove();a=$("#dialogEmbeddedRecomender .code")[0];var d=CodeMirror.fromTextArea(a,{mode:"htmlmixed",lineNumbers:!0,styleActiveLine:!0,matchBrackets:!0,readOnly:!1});d.setSize(null,480);setTimeout(function(){var c=
$("#dialogEmbeddedRecomender .code").val().trim().replace("__observerId__",b);c=c.replace("__tpHubName__",e);c=c.replace("__LeoObserverDomain__",baseLeoObserverDomain);var f="leo_recommender_"+b;d.getDoc().setValue('\x3cscript id\x3d"'+f+'"\x3e\n'+c+"\n\x3c/script\x3e");d.refresh();d.execCommand("selectAll");addHandlerCopyCodeButton("#dialogEmbeddedRecomender .code","#dialogEmbeddedRecomender button.btn-copy-code")},350)}},showRedisSourceInfo=function(a){a=decodeURIComponent($(a).data("json"));var b=
JSON.parse(a).dataSourceUrl.split("/");a=b[2];b=b[3];$("#dataSourceConfigHostAndPort").text(a);$("#dataSourceConfigTouchpointName").text(b);$("#redisSourceInfoDialog").modal({backdrop:"static",keyboard:!1})},showObserverApiInfo=function(a){a=decodeURIComponent($(a).data("json"));a=JSON.parse(a);console.log("showObserverApiInfo",a);a="string"===typeof a.accessTokens.default_access_key?a.accessTokens.default_access_key:"";$("#leoCdpApiTokenKey").val("default_access_key");$("#leoCdpApiTokenValue").val(a);
$("#leoCdpApiJourneyMapIdValue").val(currentJourneyMapId);$("#leoCdpGetProfileApiUrl").val(baseLeoAdminUrl+"/api/profile/save");$("#leoCdpTrackEventApiUrl").val(baseLeoAdminUrl+"/api/event/save");$("#leoCdpListEventsApiUrl").val(baseLeoAdminUrl+"/api/event/list?startIndex\x3d0\x26numberResult\x3d10\x26profileId\x3d{profile_ID}");$("#observerApiInfoDialog").modal({backdrop:"static",keyboard:!1})},resetAccessTokenForLeoObserverApi=function(){LeoAdminApiUtil.callPostAdminApi(baseLeoAdminUrl+"/cdp/touchpointhub/reset-access-token",
{},function(a){0===a.httpCode&&""===a.errorMessage&&(a=a.data,$("#leoCdpApiTokenKey").val(a.tokenKey),$("#leoCdpApiTokenValue").val(a.tokenValue),iziToast.success({title:"Reset Access Token",message:"The new access token is generated successfully!"}))})},initDataObserverJsGridPlugin=function(){var a=function(b){jsGrid.Field.call(this,b)};a.prototype=new jsGrid.Field({sorter:function(b,e){return 0},itemTemplate:function(b){if(""!==b.data){console.log("observerModel ",b);var e=b.data,d=b.type;b=b.firstPartyData;
var c="";30===d?c=c+'\x3cbutton type\x3d"button" class\x3d"btn btn-success  btn-sm btn-do-now btn-get-code" onclick\x3d"showObserverApiInfo(this)"  data-json\x3d"'+(e+'" \x3e\x3ci class\x3d"fa fa-info-circle" style\x3d"font-size:1.1em" aria-hidden\x3d"true"\x3e\x3c/i\x3e API Information \x3c/button\x3e'):31===d?c=c+'\x3cbutton type\x3d"button" class\x3d"btn btn-success  btn-sm btn-do-now btn-get-code" onclick\x3d"showRedisSourceInfo(this)"  data-json\x3d"'+(e+'" \x3e\x3ci class\x3d"fa fa-info-circle" style\x3d"font-size:1.1em" aria-hidden\x3d"true"\x3e\x3c/i\x3e Redis Information \x3c/button\x3e'):
32===d?c=c+'\x3cbutton type\x3d"button" class\x3d"btn btn-success  btn-sm btn-do-now btn-get-code" onclick\x3d"showKafkaSourceInfo(this)"  data-json\x3d"'+(e+'" \x3e\x3ci class\x3d"fa fa-info-circle" style\x3d"font-size:1.1em" aria-hidden\x3d"true"\x3e\x3c/i\x3e Kafka Information \x3c/button\x3e'):b?30>d&&(c='\x3cbutton type\x3d"button" class\x3d"btn btn-primary btn-sm btn-get-code" onclick\x3d"getQrImageFormCode(this)" data-json\x3d"'+(e+'" \x3e\x3ci class\x3d"fa fa-qrcode" style\x3d"font-size:1.1em" aria-hidden\x3d"true"\x3e\x3c/i\x3e  QR Image Code \x3c/button\x3e'),
0<d&&12>d?(c=c+'\x3cbutton type\x3d"button" class\x3d"btn btn-goto-router  btn-sm btn-get-code" onclick\x3d"getTrackingJsCode(this)"  data-json\x3d"'+(e+'" \x3e\x3ci class\x3d"fa fa-code" style\x3d"font-size:1.1em" aria-hidden\x3d"true"\x3e\x3c/i\x3e Event Tracking Code \x3c/button\x3e\x3cbutton type\x3d"button" class\x3d"btn btn-success btn-sm btn-get-code" onclick\x3d"getCxFeedbackJsCode(this)" '),c+=' data-json\x3d"'+e+'" \x3e\x3ci class\x3d"fa fa-code" style\x3d"font-size:1.1em" aria-hidden\x3d"true"\x3e\x3c/i\x3e Survey Rating Forms \x3c/button\x3e\x3cbutton type\x3d"button" class\x3d"btn btn-info  btn-sm btn-get-code" onclick\x3d"getRecommenderJsCode(this)" ',
c+=' data-json\x3d"'+e+'" \x3e\x3ci class\x3d"fa fa-code" style\x3d"font-size:1.1em" aria-hidden\x3d"true"\x3e\x3c/i\x3e Personalized Widget \x3c/button\x3e'):(c+='\x3cbutton type\x3d"button" class\x3d"btn btn-success btn-sm btn-get-code" onclick\x3d"getCxFeedbackJsCode(this)" ',c+=' data-json\x3d"'+e+'" \x3e\x3ci class\x3d"fa fa-code" style\x3d"font-size:1.1em" aria-hidden\x3d"true"\x3e\x3c/i\x3e Survey Rating Forms \x3c/button\x3e')):c='\x3cbutton type\x3d"button" class\x3d"btn btn-primary btn-sm btn-get-code" onclick\x3d"getQrImageFormCode(this)" data-json\x3d"'+
(e+'" \x3e\x3ci class\x3d"fa fa-qrcode" style\x3d"font-size:1.1em" aria-hidden\x3d"true"\x3e\x3c/i\x3e QR Image Code \x3c/button\x3e');return c}return""},insertTemplate:function(b){return this._insertCode=b},editTemplate:function(b){return this._editCode=b},insertValue:function(){return this._insertCode},editValue:function(){return this._editCode}});jsGrid.fields.LeoDataObserver=a},loadDataObserverList=function(a){initDataObserverJsGridPlugin();LeoAdminApiUtil.getSecuredData("/cdp/observers",{journeyMapId:currentJourneyMapId},
function(b){var e=b.data.eventObservers;b=b.data.touchpointHubTypes;for(var d=0;d<e.length;d++){var c=e[d];c.index=d+1;var f=b[c.type];c.typeName=f;var l=c.firstPartyData,n=c.type;f={id:c.id,name:c.name,type:n,typeName:f};f.collectDirectly=c.collectDirectly;f.qrCodeData=c.qrCodeData;f.accessTokens=c.accessTokens;f.securityCode=c.securityCode;f.dataSourceUrl=c.dataSourceUrl;f=JSON.stringify(f);c.observerModel={type:n,data:encodeURIComponent(f),firstPartyData:l}}$(a).jsGrid({width:"100%",height:"auto",
inserting:!1,editing:!1,sorting:!1,paging:!1,data:e,fields:[{name:"index",title:"",type:"number",width:20,align:"center"},{name:"name",title:"Name",type:"string",align:"center",css:"observer_name"},{name:"id",title:"Unique ID",type:"string",width:68,align:"center",css:"observer_id"},{name:"firstPartyData",title:"First-party Data",type:"CheckBoxIcon",width:40,align:"center"},{name:"collectDirectly",title:"Tracking directly",type:"CheckBoxIcon",width:40,align:"center"},{name:"dataSourceUrl",title:"URL",
type:"UrlLink",width:120,align:"center",css:"observer_url"},{name:"observerModel",title:"Actions",type:"LeoDataObserver",width:72,align:"center"}]})})},loadDataJourneyMapsByFilter=function(a,b,e,d,c,f,l){var n=[{data:"name"},{data:"authorizedViewers"},{data:"authorizedEditors"},{data:"createdAt"},{data:"updatedAt"},{data:"defaultMetricName"}],q=getUserSession();if(q)return $(d).DataTable({lengthMenu:[[20,30,40],[20,30,40]],processing:!0,serverSide:!0,searching:!0,search:{return:!0},ordering:!0,serverMethod:"POST",
ajax:{url:baseLeoAdminUrl+"/cdp/journeymaps/filter",contentType:"application/json",beforeSend:function(g){$(e).show();$(b).hide();g.setRequestHeader("leouss",q)},data:function(g){var k=g.order[0];g.sortField=n[k.column].data;g.sortAsc="asc"===k.dir;g.searchValue=g.search.value;delete g.order;delete g.search;"function"===typeof c&&(g=c(g),$(d).data("authorizedViewer",g.authorizedViewer),$(d).data("authorizedEditor",g.authorizedEditor));return JSON.stringify(g)},dataSrc:function(g){var k=g.canInsertData,
m=g.canEditData,w=g.canDeleteData;$(d).data("canInsertData",k);$(d).data("canEditData",m);$(d).data("canDeleteData",w);"function"===typeof loadDataCallback&&loadDataCallback(g);$(e).hide();$(b).show();return g.data}},columnDefs:[{render:function(g,k,m){return'\x3cdiv class\x3d"highlight_text text-center" title\x3d"'+g+'" \x3e'+textTruncate(g,150)+"\x3c/div\x3e"},targets:0,orderable:!1},{render:function(g,k,m){k=$(d).data("authorizedViewer");g=g.includes(k);k=m.id+"-viewer";"object"===typeof f&&(f[m.id]=
g);return getTableRowCheckedBox(a,d,k,g)},targets:1},{render:function(g,k,m){k=$(d).data("authorizedEditor");g=g.includes(k);k=m.id+"-editor";"object"===typeof l&&(l[m.id]=g);return getTableRowCheckedBox(a,d,k,g)},targets:2},{render:function(g,k,m){return'\x3cdiv class\x3d"small text-center" style\x3d"color:#3300ff;" \x3e'+moment.utc(g).local().format("YYYY-MM-DD HH:mm:ss")+"\x3c/div\x3e"},targets:3},{render:function(g,k,m){return'\x3cdiv class\x3d"small text-center" style\x3d"color:#3300ff;" \x3e'+
moment.utc(g).local().format("YYYY-MM-DD HH:mm:ss")+"\x3c/div\x3e"},targets:4},{render:function(g,k,m){return'\x3cdiv class\x3d" text-center"  \x3e'+g+"\x3c/div\x3e"},targets:5},{render:function(g,k,m){return'\x3ca class\x3d"control" title\x3d"Segment Report" href\x3d"#calljs-leoCdpRouter(\'Data_Journey_Map\',\''+(m.id+'\')" \x3e \x3ci class\x3d"fa fa-info-circle" aria-hidden\x3d"true"\x3e\x3c/i\x3e View\x3c/a\x3e')},targets:6}],columns:n})};
var loadJourneyMapEventMatrix=function(a,b,e,d,c){LeoAdminApiUtil.getSecuredData(baseLeoAdminUrl+"/cdp/analytics360/event-matrix",{journeyMapId:a,beginFilterDate:e||"",endFilterDate:d||""},function(f){var l=f.data;"object"===typeof l?(renderMatrixChart("Event Matrix Report",b,l.xLabels,l.yLabels,l.dataList),"function"===typeof c&&c(l)):console.error(f)})};
const loadJourneyTouchpointHubReport=function(a,b){$("#journeyObserverChart").html('\x3cdiv class\x3d"loader"\x3e\x3c/div\x3e');LeoAdminApiUtil.getSecuredData(baseLeoAdminUrl+"/cdp/analytics360/touchpoint-hub-report",{journeyMapId:a,maxTouchpointHubSize:b},function(e){if(0===e.httpCode&&""===e.errorMessage)if(e=e.data,0<e.length){var d=[],c=[];e.forEach(function(f){d.push(f.name);c.push(f.eventCount)});renderHorizontalBarChart("journeyObserverChart",d,c)}else $("#journeyObserverChart").html("\x3ch4\x3e No data available \x3c/h4\x3e");
else LeoAdminApiUtil.logErrorPayload(e)})};function showJourneyFlowReport(a,b){var e=$("#"+b).empty().html('\x3cdiv class\x3d"loader"\x3e\x3c/div\x3e'),d=baseLeoAdminUrl+"/cdp/analytics360/touchpoint-flow-report";a.startIndex=0;a.numberFlow=150;LeoAdminApiUtil.getSecuredData(d,a,function(c){0===c.httpCode&&""===c.errorMessage?(e.empty(),flowNetworkGraph=renderDirectedGraph(b,{nodes:c.data.nodes,edges:c.data.edges},c.data.rootNodeId)):LeoAdminApiUtil.logErrorPayload(c)})}
function setJourneyFlowGraphView(){"object"===typeof flowNetworkGraph&&setTimeout(function(){flowNetworkGraph.fit(!0)},300)};