'use strict';const loadSegmentData=function(b){LeoAdminApiUtil.callPostAdminApi(baseLeoAdminUrl+"/cdp/segment/load",{id:b},function(a){if(0===a.httpCode&&""===a.errorMessage){var c=a.data.behavioralEventMap,d=a.data.assetGroups,e=a.data.touchpointHubs;segmentDataModel=a.data.segmentData;segmentDataStats=a.data.segmentStats;var f=segmentDataModel.managedBySystem,g=JSON.parse(segmentDataModel.jsonQueryRules);f?($("button.data-control-delete").attr("disabled","disabled"),$("button.data-control-delete").attr("title",
"Can not delete this segment, which is managed by system")):a.canDeleteData?$("button.data-control-delete").click(deleteSegment):$("button.data-control-delete").attr("disabled","disabled");a.canEditData?$("button.data-control-edit").click(function(){location.hash="calljs-leoCdpRouter('Segment_Builder','"+b+"')"}):$("button.data-control-edit").attr("disabled","disabled");loadSegmentEventReport();setupSegmentDataAndReports(segmentDataModel);initSegmentActivationButtons(segmentDataModel);$("#segment_details_div").show();
$("#segment_details_loader").hide();loadSegmentStatistics(segmentDataStats);loadSegmentBuilder(e,c,d,g,function(){loadProfilesInSegment();var h=$("#segment-builder-holder");h.find("input,select").attr("disabled","disabled");h.find("button").hide();$("#profilelist_holder").show()});loadActivationRules(segmentDataModel.activationRules);document.title="Segment Details - "+segmentDataModel.name}else LeoAdminApiUtil.logErrorPayload(a)})},createSegmentJsonDataConnection=function(){var b=function(){iziToast.info({timeout:3E3,
message:'LEO CDP is processing data for the segment "'+segmentDataModel.name+'"'});LeoAdminApiUtil.getSecuredData(window.baseLeoAdminUrl+"/cdp/segment/export-json",{segmentId:segmentDataModel.id},function(a){0===a.httpCode&&""===a.errorMessage&&a.data&&(a=window.baseLeoAdminUrl+a.data,$("#segment_json_url").val(a),$("#btn_segment_json_url").data("url",a),setTimeout(function(){$("#btn_segment_json_url").data("init-done",!0).trigger("click")},800))})};null==mapClipboardJS["#btn_segment_json_url"]&&
(mapClipboardJS["#btn_segment_json_url"]=!0,b(),new ClipboardJS("#btn_segment_json_url",{text:function(a){$("#btn_segment_json_url").data("init-done")&&notifySuccessMessage("Successfully copied URL into clipboard!");return $("#btn_segment_json_url").data("url")}}))},createSegmentCsvDataConnection=function(){var b=function(){iziToast.info({timeout:2E3,message:'LEO CDP is processing data for the segment "'+segmentDataModel.name+'"'});LeoAdminApiUtil.getSecuredData(window.baseLeoAdminUrl+"/cdp/segment/export-csv",
{segmentId:segmentDataModel.id,csvType:0},function(a){0===a.httpCode&&""===a.errorMessage&&a.data&&(a=window.baseLeoAdminUrl+a.data,$("#segment_csv_url").val(a),$("#btn_segment_csv_url").data("url",a),setTimeout(function(){$("#btn_segment_csv_url").data("init-done",!0).trigger("click")},800))})};null==mapClipboardJS["#btn_segment_csv_url"]&&(mapClipboardJS["#btn_segment_csv_url"]=!0,b(),new ClipboardJS("#btn_segment_csv_url",{text:function(a){$("#btn_segment_csv_url").data("init-done")&&notifySuccessMessage("Successfully copied URL into clipboard!");
return $("#btn_segment_csv_url").data("url")}}))},getSegmentDownloadUrl=function(b,a){var c="#"+$(b).attr("id"),d=0,e="";"txt_exported_excel_csv"===a?(d=0,e="#ahref_exported_excel_csv"):"txt_exported_facebook_csv"===a&&(d=1,e="#ahref_exported_facebook_csv");b=function(){LeoAdminApiUtil.getSecuredData(window.baseLeoAdminUrl+"/cdp/segment/export-csv",{segmentId:segmentDataModel.id,csvType:d},function(f){0===f.httpCode&&""===f.errorMessage&&f.data&&(f=window.baseLeoAdminUrl+f.data,$("#"+a).val(f),$(c).data("url",
f),$(e).attr("href",f).show(),setTimeout(function(){$(c).data("init-done",!0).trigger("click")},800))})};null==mapClipboardJS[c]&&(mapClipboardJS[c]=!0,b(),iziToast.info({timeout:2E3,message:'LEO CDP is processing data for the segment "'+segmentDataModel.name+'"'}),new ClipboardJS(c,{text:function(f){$(c).data("init-done")&&notifySuccessMessage("Successfully copied URL into clipboard!");return $(c).data("url")}}))};window.segmentEventChart=!1;
const loadSegmentEventReport=function(b){var a=getDateFilterValues();a.segmentId=segmentDataModel.id;var c=a.beginFilterDate;$("#eventDataFromDate").text((new moment(c)).format("YYYY-MM-DD HH:mm:ss"));c=a.endFilterDate;$("#eventDataToDate").text((new moment(c)).format("YYYY-MM-DD HH:mm:ss"));c=baseLeoAdminUrl+"/cdp/analytics360/event-report/segment";$("#segment_report_loader").show();$("#segmentEventChart").css("visibility","hidden");LeoAdminApiUtil.getSecuredData(c,a,function(d){$("#segment_report_loader").hide();
$("#segmentEventChart").css("visibility","visible");0===d.httpCode&&""===d.errorMessage?!0===b&&!1!==segmentEventChart?renderTimeseriesChart("segmentEventChart",d.data,!0,segmentEventChart):window.segmentEventChart=renderTimeseriesChart("segmentEventChart",d.data,!1):LeoAdminApiUtil.logErrorPayload(d)})},initSegmentActivationButtons=function(b){var a=b.id,c=b.name,d=b.totalCount;$("button[data-purpose]").click(function(){var e=$(this).data("purpose");"forPersonalization"===e?showDataPersonalizationDialog(a,
c,d):"forDataEnrichment"===e?showDataEnrichmentDialog(a,c,d):"forSynchronization"===e&&showDataSynchronizationDialog(a,c,d)})},getHtmlForAuthorizedUserLogin=function(b){var a="";b.forEach(function(c){a=6===currentUserProfile.role?a+("\x3ca title\x3d\"User Login Report\" href\x3d\"#calljs-leoCdpRouter('User_Login_Report','"+(c+"')\" \x3e")+c+"\x3c/a\x3e, "):a+(c+", ")});return a},setupSegmentDataAndReports=function(b){var a=b.name,c=b.totalCount.toLocaleString(),d=4<=currentUserProfile.role;$("#sm_indexScore").text(b.indexScore);
$("#sm_name").text(a);$("#sm_size").text(c);$("b.segment_size").text(c);$("#sm_description").text(b.description);$("#sm_authorizedViewers").html(getHtmlForAuthorizedUserLogin(b.authorizedViewers));$("#sm_authorizedEditors").html(getHtmlForAuthorizedUserLogin(b.authorizedEditors));a=$("#segment_data_personalization");b.forPersonalization&&d?(a.show(),setTimeout(loadPersonalizationTabForSegment,1E3)):a.hide();a=$("#segment_data_enrichment");(b.forDeepAnalytics||b.forPredictiveAnalytics)&&d?a.show():
a.hide();a=$("#segment_data_synchronization");(b.for3rdSynchronization||b.forEmailMarketing)&&d?a.show():a.hide()};function handleSegmentPersonalizationTabs(){$("#personalizationPlan li.active a").click()}
const loadPersonalizationTabForSegment=function(){var b=function(a,c){var d=$(a);c.forEach(function(e,f){d.append('\x3coption value\x3d"'+e.id+'" \x3e'+e.title+"\x3c/option\x3e")});d.chosen({width:"100%",no_results_text:"Oops, nothing found!"}).trigger("chosen:updated")};LeoAdminApiUtil.getSecuredData(window.baseLeoAdminUrl+"/cdp/asset-group/list-by-asset-types",{assetTypes:"1,2,15,16"},function(a){if(0===a.httpCode&&""===a.errorMessage){a=a.data;$("#productGroupSelector option").remove();$("#contentGroupSelector option").remove();
for(var c in a){var d=a[c];2===parseInt(c)?b("#productGroupSelector",d):b("#contentGroupSelector",d)}}else LeoAdminApiUtil.logErrorPayload(a)})},initPersonalizationInSegment=function(b){!1===window.segmentFirstProfileId&&(window.segmentFirstProfileId=b,loadRecommendedContentsForProfile(segmentFirstProfileId,!1,function(a){$("#max_recommended_contents").html(a)}),loadRecommendedProductsForProfile(segmentFirstProfileId,!1,function(a){$("#max_recommended_products").html(a)}))},setContentPersonalizationInSegment=
function(){var b=$("#contentGroupSelector").val();b&&""!==b&&segmentDataModel&&(iziToast.info({title:"Information Box",color:"green",message:"Starting content personalization..."}),LeoAdminApiUtil.callPostAdminApi(baseLeoAdminUrl+"/cdp/segment/set-recommended-items",{assetGroupId:b,segmentId:segmentDataModel.id,isProductGroup:!1},function(a){0===a.httpCode&&""===a.errorMessage&&(iziToast.info({title:"Information Box",color:"green",message:"Finished the process to set recommended contents, total graph connections: "+
a.data}),!1!==segmentFirstProfileId&&loadRecommendedContentsForProfile(segmentFirstProfileId,!1,function(c){$("#max_recommended_contents").html(c)}))}))},setProductPersonalizationInSegment=function(){var b=$("#productGroupSelector").val();b&&""!==b&&segmentDataModel&&(iziToast.info({title:"Information Box",color:"green",message:"Starting product personalization..."}),LeoAdminApiUtil.callPostAdminApi(baseLeoAdminUrl+"/cdp/segment/set-recommended-items",{assetGroupId:b,segmentId:segmentDataModel.id,
isProductGroup:!0},function(a){0===a.httpCode&&""===a.errorMessage&&(iziToast.info({title:"Information Box",color:"green",message:"Finished the process to set recommended products, total graph connections: "+a.data}),!1!==segmentFirstProfileId&&loadRecommendedProductsForProfile(segmentFirstProfileId,!1,function(c){$("#max_recommended_products").html(c)}))}))},removeRecommendedItemsInSegment=function(b,a,c){a&&""!==a&&segmentDataModel&&(iziToast.info({title:"Information Box",color:"yellow",message:"Starting to remove recommended items"}),
LeoAdminApiUtil.callPostAdminApi(baseLeoAdminUrl+"/cdp/segment/remove-recommended-items",{assetGroupId:a,segmentId:segmentDataModel.id,isProductGroup:b},function(d){0===d.httpCode&&""===d.errorMessage&&(iziToast.info({title:"Information Box",color:"green",message:"Successfully remove recommended items in the segment"}),c())}))},removeRecommendedContentsInSegment=function(b){b=!0===b?"remove_all":$("#contentGroupSelector").val();removeRecommendedItemsInSegment(!1,b,function(){!1!==window.segmentFirstProfileId&&
loadRecommendedContentsForProfile(window.segmentFirstProfileId,!1,function(a){$("#max_recommended_contents").html(a)})})},removeRecommendedProductsInSegment=function(b){b=!0===b?"remove_all":$("#productGroupSelector").val();removeRecommendedItemsInSegment(!0,b,function(){!1!==window.segmentFirstProfileId&&loadRecommendedProductsForProfile(window.segmentFirstProfileId,!1,function(a){$("#max_recommended_products").html(a)})})},loadDataConnectorSelection=function(b,a){var c=$("#btnOkActivateSegment");
c.data("segmentId",b).data("segmentName",a).hide();$("#dataConnectorSelector_loader").show();$("#dataConnectorSelector_holder").hide();var d=$("#dataConnectorSelector");d.find("option").remove().trigger("chosen:updated");b="true"===d.data("forSynchronization");a="true"===d.data("forDataEnrichment");var e="true"===d.data("forPersonalization");dataConnectorLoader("",!0,e,a,b,0,1E4,function(f){c.show();$("#dataConnectorSelector_loader").hide();$("#dataConnectorSelector_holder").show();0<f.length?_.forEach(f,
function(g,h){d.append('\x3coption value\x3d"'+g.id+'" \x3e'+g.name+"\x3c/option\x3e")}):d.append('\x3coption value\x3d"" \x3e No available connector for data enrichment\x3c/option\x3e');d.chosen({width:"100%"}).trigger("chosen:updated")})},updateSpecificTimeToRunConnector=function(){var b=$("#connectorSchedulingTime").val(),a=$("#box_everyday_at_time");0<b?(a.show(),$("#connector_run_specific_time").val("23:01")):a.hide()};var SchedulingTimeUnit="hour";const SchedulingTimeMap={0:"Run connector immediately and only once"};
SchedulingTimeMap["1"]="Every 1 "+SchedulingTimeUnit+" starting from specific time";SchedulingTimeMap["2"]="Every 2 "+SchedulingTimeUnit+"s starting from specific time";SchedulingTimeMap["3"]="Every 3 "+SchedulingTimeUnit+"s starting from specific time";SchedulingTimeMap["4"]="Every 4 "+SchedulingTimeUnit+"s starting from specific time";SchedulingTimeMap["5"]="Every 5 "+SchedulingTimeUnit+"s starting from specific time";SchedulingTimeMap["6"]="Every 6 "+SchedulingTimeUnit+"s starting from specific time";
SchedulingTimeMap["7"]="Every 7 "+SchedulingTimeUnit+"s starting from specific time";SchedulingTimeMap["8"]="Every 8 "+SchedulingTimeUnit+"s starting from specific time";SchedulingTimeMap["9"]="Every 9 "+SchedulingTimeUnit+"s starting from specific time";SchedulingTimeMap["10"]="Every 10 "+SchedulingTimeUnit+"s starting from specific time";SchedulingTimeMap["12"]="Every 12 "+SchedulingTimeUnit+"s starting from specific time";SchedulingTimeMap["15"]="Every 15 "+SchedulingTimeUnit+"s starting from specific time";
SchedulingTimeMap["20"]="Every 20 "+SchedulingTimeUnit+"s starting from specific time";SchedulingTimeMap["24"]="Every 24 "+SchedulingTimeUnit+"s starting from specific time";SchedulingTimeMap["48"]="Every 48 "+SchedulingTimeUnit+"s starting from specific time";SchedulingTimeMap["72"]="Every 72 "+SchedulingTimeUnit+"s starting from specific time";const ConnectorSchedulingTime=function(b){jsGrid.Field.call(this,b)};
ConnectorSchedulingTime.prototype=new jsGrid.Field({sorter:function(b,a){return 0},itemTemplate:function(b){b=SchedulingTimeMap[""+b];return'\x3cdiv style\x3d"font-size:13px" target\x3d"_blank" \x3e'+("string"===typeof b?b:"")+"\x3c/div\x3e"},insertTemplate:function(b){return this._insertCode=b},editTemplate:function(b){return this._editCode=b},insertValue:function(){return this._insertCode},editValue:function(){return this._editCode}});jsGrid.fields.ConnectorSchedulingTime=ConnectorSchedulingTime;
const initActivationJsGridPlugin=function(){var b=function(a){jsGrid.Field.call(this,a)};b.prototype=new jsGrid.Field({sorter:function(a,c){return 0},itemTemplate:function(a){var c=a.id,d=a.dataConnectorName;a=a.active;console.log("activationRuleId ",c);console.log("active ",a);var e='\x3cdiv class\x3d"col-lg-12" \x3e\x3cbutton type\x3d"button" class\x3d"activation-btn btn btn-do-now btn-sm" onclick\x3d"loadActivationLogsOfSegment(this)" data-activation-rule-id\x3d"'+(c+'"  data-activation-connector-name\x3d"')+
(d+'" \x3e\x3ci class\x3d"fa fa-info-circle" style\x3d"font-size:1.2em" aria-hidden\x3d"true"\x3e\x3c/i\x3e View Logs \x3c/button\x3e\x3c/div\x3e');a?(e+='\x3cdiv class\x3d"col-lg-12" \x3e\x3cbutton type\x3d"button" class\x3d"activation-btn btn btn-warning btn-sm" onclick\x3d"stopActivationForSegment(this)"',e=e+(' data-activation-rule-id\x3d"'+c+'"  data-activation-connector-name\x3d"')+(d+'" \x3e\x3ci class\x3d"fa fa-stop" style\x3d"font-size:1.2em" aria-hidden\x3d"true"\x3e\x3c/i\x3e Stop \x3c/button\x3e\x3c/div\x3e')):
(e+='\x3cdiv class\x3d"col-lg-12" \x3e\x3cbutton type\x3d"button" class\x3d"activation-btn btn btn-goto-router btn-sm" onclick\x3d"startActivationForSegment(this)"',e=e+(' data-activation-rule-id\x3d"'+c+'"  data-activation-connector-name\x3d"')+(d+'" \x3e\x3ci class\x3d"fa fa-play" style\x3d"font-size:1.2em" aria-hidden\x3d"true"\x3e\x3c/i\x3e Start \x3c/button\x3e\x3c/div\x3e'),e+='\x3cdiv class\x3d"col-lg-12" \x3e\x3cbutton type\x3d"button" class\x3d"activation-btn btn btn-danger btn-sm" onclick\x3d"removeActivationForSegment(this)"',
e=e+(' data-activation-rule-id\x3d"'+c+'"  data-activation-connector-name\x3d"')+(d+'" \x3e\x3ci class\x3d"fa fa-trash-o" style\x3d"font-size:1.2em" aria-hidden\x3d"true"\x3e\x3c/i\x3e Remove \x3c/button\x3e\x3c/div\x3e'));return e},insertTemplate:function(a){return this._insertCode=a},editTemplate:function(a){return this._editCode=a},insertValue:function(){return this._insertCode},editValue:function(){return this._editCode}});jsGrid.fields.ActivationButtons=b},loadActivationRules=function(b){var a=
function(f,g){$(f).jsGrid({width:"100%",height:"auto",inserting:!1,editing:!1,sorting:!1,paging:!1,data:g,fields:[{name:"active",title:'\x3ci class\x3d"fa fa-info-circle" aria-hidden\x3d"true"\x3e\x3c/i\x3e Active',type:"CheckBoxIcon",align:"center",width:30},{name:"dataConnectorName",title:'\x3ci class\x3d"fa fa-info-circle" aria-hidden\x3d"true"\x3e\x3c/i\x3e Data Connector Name',type:"BoldText",align:"center"},{name:"schedulingTime",title:'\x3ci class\x3d"fa fa-bolt" aria-hidden\x3d"true"\x3e\x3c/i\x3e Rule to trigger',
type:"ConnectorSchedulingTime",align:"center"},{name:"createdAt",title:'\x3ci class\x3d"fa fa-info-circle" aria-hidden\x3d"true"\x3e\x3c/i\x3e Created at',type:"JsGridLocalTime",align:"center",width:60},{name:"ownerUsername",title:'\x3ci class\x3d"fa fa-info-circle" aria-hidden\x3d"true"\x3e\x3c/i\x3e Created by',type:"BoldText",align:"center",width:60},{name:"buttonState",title:"Actions",type:"ActivationButtons",width:50,align:"center"}]})},c=[],d=[],e=[];b.forEach(function(f){f.buttonState={id:f.id,
active:f.active,dataConnectorName:f.dataConnectorName};"personalization"===f.purpose?c.push(f):"data_enrichment"===f.purpose?d.push(f):"synchronization"===f.purpose&&e.push(f)});initActivationJsGridPlugin();a("#segment_personalization_connectors",c);a("#segment_enrichment_connectors",d);a("#segment_synchronization_connectors",e)},loadSchedulingTimeSelect=function(){var b=$("#connectorSchedulingTime");_.forOwn(SchedulingTimeMap,function(a,c){a=$('\x3coption value\x3d"'+c+'" \x3e'+a+"\x3c/option\x3e");
b.append(a)})},showDataPersonalizationDialog=function(b,a,c){$("#dialogSelectDataConnector").modal({backdrop:"static",keyboard:!1});$("#purpose_activation_name").text("data personalization");$("#btnOkActivateSegment").data("purpose","personalization");c=$("#dataConnectorSelector");c.data("forSynchronization","false");c.data("forDataEnrichment","false");c.data("forPersonalization","true");loadDataConnectorSelection(b,a)},showDataEnrichmentDialog=function(b,a,c){$("#dialogSelectDataConnector").modal({backdrop:"static",
keyboard:!1});$("#purpose_activation_name").text("data enrichment");$("#btnOkActivateSegment").data("purpose","data_enrichment");c=$("#dataConnectorSelector");c.data("forSynchronization","false");c.data("forDataEnrichment","true");c.data("forPersonalization","false");loadDataConnectorSelection(b,a)},showDataSynchronizationDialog=function(b,a,c){$("#dialogSelectDataConnector").modal({backdrop:"static",keyboard:!1});$("#purpose_activation_name").text("data synchronization");$("#btnOkActivateSegment").data("purpose",
"synchronization");c=$("#dataConnectorSelector");c.data("forSynchronization","true");c.data("forDataEnrichment","false");c.data("forPersonalization","false");loadDataConnectorSelection(b,a)},activateDataConnector=function(b){var a=$(b).data("purpose"),c=$("#dataConnectorSelector").val(),d=$(b).data("segmentId"),e=$(b).data("segmentName");b=parseInt($("#connectorSchedulingTime").val());var f=$("#connector_run_specific_time").val();"string"===typeof c&&""!==c?($("#dialogSelectDataConnector").modal("hide"),
d={purpose:a,segmentId:d,connectorId:c},d.schedulingTime=b,d.timeToStart=f,LeoAdminApiUtil.callPostAdminApi("/cdp/data-connector/create-activation",d,function(g){""!==g.data?(g="The segment ["+e+"] is successfully activated for "+a.replace("_"," "),notifySuccessMessage(g,function(){refreshSegmentDetails()})):notifyErrorMessage("Data activation for ["+e+"], is failed, please set valid configs for the connector: "+c)})):iziToast.error({title:"Error",message:"Please select an active connector"})},stopActivationForSegment=
function(b){var a=$(b).data("activation-rule-id"),c=$(b).data("activation-connector-name");LeoAdminApiUtil.callPostAdminApi("/cdp/data-connector/stop-activation",{activationRuleId:a},function(d){!0===d.data?(d="The activation rule of connector ["+c+"] is successfully stopped ! ",notifySuccessMessage(d,function(){refreshSegmentDetails()})):(d="There is an error when stop the activation rule of connector ["+c+"] ! ",notifyErrorMessage(d))})},removeActivationForSegment=function(b){var a=$(b).data("activation-rule-id"),
c=$(b).data("activation-connector-name");LeoAdminApiUtil.callPostAdminApi("/cdp/data-connector/remove-activation",{activationRuleId:a},function(d){!0===d.data?(d="The activation rule of connector ["+c+"] is successfully removed ! ",notifySuccessMessage(d,function(){refreshSegmentDetails()})):(d="There is an error when remove the activation rule of connector ["+c+"] ! ",notifyErrorMessage(d))})},startActivationForSegment=function(b){var a=$(b).data("activation-rule-id"),c=$(b).data("activation-connector-name");
LeoAdminApiUtil.callPostAdminApi("/cdp/data-connector/start-activation",{activationRuleId:a},function(d){!0===d.data?(d="The activation rule of connector ["+c+"] is successfully started ! ",notifySuccessMessage(d,function(){refreshSegmentDetails()})):(d="There is an error when start the activation rule of connector ["+c+"] ! ",notifyErrorMessage(d))})},loadActivationLogsOfSegment=function(b){b=$(b).data("activation-rule-id");console.log("load Action Logs of ActivationRule ID: "+b);loadSystemEventsTable("Activation Rule",
"activationEventLogsHolder","ActivationRule",b,"leocdp",function(){$("#activationEventLogsDialog").modal({backdrop:"static",keyboard:!1})},[5])};