'use strict';function profileAddNewTextHashSet(b){var d=$('\x3cli class\x3d"list-group-item" \x3e\x3cdiv class\x3d"row" \x3e\x3cdiv class\x3d"col-md-11" \x3e\x3cinput class\x3d"form-control" type\x3d"text" placeholder\x3d"Value" data-fieldholder\x3d"hashset" data-fieldtype\x3d"string" autocomplete\x3d"off"\x3e\x3c/div\x3e\x3cdiv class\x3d"col-md-1" \x3e\x3ch4 onclick\x3d"$(this).parent().parent().parent().remove()" \x3e\x3ci class\x3d"fa fa-times-circle delete-item-btn" aria-hidden\x3d"true"\x3e\x3c/i\x3e\x3c/h4\x3e \x3c/div\x3e\x3c/div\x3e\x3c/li\x3e');
$('p[data-field\x3d"'+b+'"] \x3e ul').append(d);d.effect("highlight",{},4E3)}function profileAddNewCustomField(b){var d=$(loadCustomFieldEditor(b,"",""));$('p[data-field\x3d"'+b+'"] \x3e ul').append(d);d.effect("highlight",{},4E3)}
var addNewHashMapItem=function(b,d){var a=b+"_"+(new Date).getTime(),c=$("#"+b),f=Object.assign({},d);c.find("option:selected").each(function(){var g=$(this).val();delete f[g]});b=$(loadHashMapSelector(a,b,f,"",""));c.find("ul.list-group").append(b);b.effect("highlight",{},4E3)};function removeHashMapItem(b){$(b).parent().parent().remove()}
function loadHashMapSelector(b,d,a,c,f){var g='\x3cdiv class\x3d"col-md-3" \x3e \x3cselect class\x3d"form-control" id\x3d"key_'+b+'" name\x3d"'+d+'" \x3e';_.forOwn(a,function(l,h){l='\x3coption name\x3d"'+d+'" value\x3d"'+h+'"\x3e '+h.toUpperCase()+" \x3c/option\x3e";h===c&&(l='\x3coption name\x3d"'+d+'" selected value\x3d"'+h+'"\x3e '+h.toUpperCase()+" \x3c/option\x3e");g+=l});g+=" \x3c/select\x3e \x3c/div\x3e";""===c&&$("#key_"+b).find("option:first").attr("selected","selected");return'\x3cli id\x3d"item_'+
b+'" class\x3d"list-group-item" \x3e\x3cdiv class\x3d"row" \x3e '+g+('\x3cdiv class\x3d"col-md-8" \x3e\x3cinput id\x3d"value_'+b+'" value\x3d"'+(f?f:"")+'" class\x3d"form-control" type\x3d"text" placeholder\x3d"Value" data-fieldholder\x3d"hashmap" data-fieldtype\x3d"string" autocomplete\x3d"off"\x3e\x3c/div\x3e\x3cdiv title\x3d"Delete" class\x3d"col-md-1" onclick\x3d"removeHashMapItem(this)" \x3e \x3ch4\x3e\x3ci class\x3d"fa fa-times-circle delete-item-btn" aria-hidden\x3d"true"\x3e\x3c/i\x3e\x3c/h4\x3e \x3c/div\x3e \x3c/div\x3e\x3c/li\x3e')}
function loadCustomFieldEditor(b,d,a){return'\x3cli class\x3d"list-group-item" \x3e\x3cdiv class\x3d"row" \x3e \x3cdiv class\x3d"col-md-3" \x3e \x3cinput type\x3d"text" class\x3d"form-control custom_field_name" placeholder\x3d"Field Name" value\x3d"'+(d+'"\x3e \x3c/div\x3e\x3cdiv class\x3d"col-md-8" \x3e\x3cinput class\x3d"form-control custom_field_value" type\x3d"text" value\x3d"')+((a?a:"")+'" placeholder\x3d"Field Value" data-fieldholder\x3d"hashmap" data-fieldtype\x3d"string" autocomplete\x3d"off"\x3e\x3c/div\x3e\x3cdiv title\x3d"Delete" class\x3d"col-md-1" onclick\x3d"removeHashMapItem(this)" \x3e \x3ch4\x3e\x3ci class\x3d"fa fa-times-circle delete-item-btn" aria-hidden\x3d"true"\x3e\x3c/i\x3e\x3c/h4\x3e \x3c/div\x3e \x3c/div\x3e\x3c/li\x3e')}
const loadProfileDataIntoDOM=function(b,d,a,c,f){var g=!1,l={};"string"===typeof d?(g="/cdp/profile/get",l.id=d):"string"===typeof a&&(g="/cdp/profile/get-by-crm-id",l.crmRefId=a);!1===g?(console.error("loadProfileDataIntoDOM is failed, profileId or crmRefId must be a valid string! "),console.log("urlStr "+g),console.log("params "+l)):LeoAdminApiUtil.callPostAdminApi(baseLeoAdminUrl+g,l,function(h){if(0===h.httpCode&&""===h.errorMessage){var r=h.canInsertData,x=h.canDeleteData;h.canEditData||$("button.data-control-edit").attr("disabled",
"disabled");x||$("button.data-control-delete").attr("disabled","disabled");r||$("button.data-control-insert").attr("disabled","disabled");LeoCdpAdmin.routerContext.dataObject="function"===typeof c?c(h.data):h.data;$("#data_model_holder").find("*[data-field]").each(function(){$(this).prop("tagName");var q=$(this).attr("type"),p=$(this).data("fieldholder"),t=$(this).data("fieldtype"),v=$(this).data("field"),u=v.split(".");if(1===u.length){var e=LeoCdpAdmin.routerContext.dataObject[u[0]];if("html"===
p){if("int"===t||"float"===t)if(void 0===e||null==e)e="-";else{if(e=(new Number(e)).toLocaleString(),NaN==e||"NaN"==e)e="-"}else"date"===t?e=e?moment.utc(e).local().format("YYYY-MM-DD"):"-":"date_time"===t?e=e?moment.utc(e).local().format("YYYY-MM-DD HH:mm:ss"):"-":"phone"===t&&(e=e?e.replace(/\D/g,""):"-");$(this).html(e)}else if("percentage"===p)$(this).html(e).parent().attr("aria-valuenow",e).css("width",e+"%"),q=$(this).parent(),q.attr("title",e+"% "+q.attr("title"));else if("url"===p)$(this).html(checkToAddUrlValueToDOM(e));
else if("locationcode"===p)q=$("\x3ca/\x3e").attr("href","javascript:").html(textTruncate(e,80)).click(function(){var k=LeoCdpAdmin.routerContext.dataObject.locationCode;0===k.indexOf("http")?eModal.iframe(k,"Location"):k&&""!=k.trim()&&eModal.iframe("https://plus.codes/"+k,e)}),$(this).html(q);else if("inputvalue"===p)"radio"===q||"checkbox"===q?e==$(this).val()&&$(this).attr("checked","checked"):$(this).val(e);else if("html_hashmap"===p){var m=' \x3cul class\x3d"list-group" \x3e ';_.forOwn(e,function(k,
n){n=n.trim();b?(k=loadHashMapSelector(v+"_"+n,v,"socialMediaProfiles"===v?SocialMediaIconMap:"personalContacts"===v?PersonalContactIconsMap:ContactIconsMap,n,k),m+=k):(n="socialMediaProfiles"===v?SocialMediaIconMap[n]?SocialMediaIconMap[n]:!1:"personalContacts"===v?PersonalContactIconsMap[n]?PersonalContactIconsMap[n]:!1:ContactIconsMap[n]?ContactIconsMap[n]:!1,!1===n&&(n=' \x3ci class\x3d"fa fa-info-circle" aria-hidden\x3d"true"\x3e\x3c/i\x3e '),m=m+'\x3cli class\x3d"list-group-item" \x3e '+n+checkToAddUrlValueToDOM(k)+
"\x3c/li\x3e")});m+=" \x3c/ul\x3e ";$(this).html(m)}else"html_hashset"===p?(m='\x3cul class\x3d"list-group" \x3e',_.forOwn(e,function(k,n){k=b?'\x3cdiv class\x3d"col-md-11" \x3e\x3cinput value\x3d"'+k+'" class\x3d"form-control" type\x3d"text" placeholder\x3d"Value" data-fieldholder\x3d"hashset" data-fieldtype\x3d"string" autocomplete\x3d"off"\x3e\x3c/div\x3e\x3cdiv class\x3d"col-md-1" \x3e\x3ch4 onclick\x3d"$(this).parent().parent().parent().remove()" \x3e\x3ci class\x3d"fa fa-times-circle delete-item-btn" aria-hidden\x3d"true"\x3e\x3c/i\x3e\x3c/h4\x3e\x3c/div\x3e':
"system_user"===t?' \x3cdiv class\x3d"col-md-12" \x3e \x3cb\x3e \x3ci class\x3d"fa fa-info-circle" aria-hidden\x3d"true"\x3e\x3c/i\x3e\x3c/b\x3e '+buildSystemUserInfoLink(k)+"\x3c/div\x3e":' \x3cdiv class\x3d"col-md-12" \x3e \x3cb\x3e \x3ci class\x3d"fa fa-info-circle" aria-hidden\x3d"true"\x3e\x3c/i\x3e\x3c/b\x3e '+checkToAddUrlValueToDOM(k)+"\x3c/div\x3e";m=m+'\x3cli class\x3d"list-group-item" \x3e \x3cdiv class\x3d"row" \x3e '+k+"\x3c/div\x3e\x3c/li\x3e"}),m+="\x3c/ul\x3e",$(this).html(m)):"html_list_key_value"===
p?(m='\x3cul class\x3d"list-group" \x3e',q=Object.keys(e),q.sort(),q.forEach(function(k){m=m+'\x3cli class\x3d"list-group-item" \x3e '+k+'  \x3ci class\x3d"fa fa-arrow-right" aria-hidden\x3d"true"\x3e\x3c/i\x3e  '+e[k]+"\x3c/li\x3e"}),m+="\x3c/ul\x3e",$(this).html(m)):"html_custom_field"===p&&(m=' \x3cul class\x3d"list-group" \x3e ',_.forOwn(e,function(k,n){n=n.trim();b?(k=loadCustomFieldEditor(v+"_"+n,n,k),m+=k):(m+='\x3cli class\x3d"list-group-item" \x3e',m+='\x3cdiv class\x3d"row" \x3e \x3cdiv class\x3d"col-md-3"\x3e \x3cb\x3e '+
n+'\x3c/b\x3e \x3ci  style\x3d"font-size:20px" class\x3d"fa fa-equals" aria-hidden\x3d"true"\x3e\x3c/i\x3e \x3c/div\x3e',m+='\x3cdiv class\x3d"col-md-9"\x3e'+k+"\x3c/div\x3e \x3c/div\x3e\x3c/li\x3e")}),m+=" \x3c/ul\x3e ",$(this).html(m))}else if(2===u.length){var w=LeoCdpAdmin.routerContext.dataObject[u[0]]||{};e=w[u[1]]||"";"html"===p?$(this).html(e):"date"===t?(e=moment.utc(e).local().format("YYYY-MM-DD"),$(this).html(e)):"date_time"===t?(e=moment.utc(e).local().format("YYYY-MM-DD HH:mm:ss"),$(this).html(e)):
"inputvalue"===p?$(this).val(e):"url"===p?$(this).html(checkToAddUrlValueToDOM(e)):"eventlocation"===p&&(q=$("\x3ca/\x3e").attr("href","javascript:").html(e).click(function(){var k=w.locationCode||"";k&&""!=k.trim()&&eModal.iframe("https://plus.codes/"+k,e)}),$(this).html(q))}else 3===u.length&&(w=LeoCdpAdmin.routerContext.dataObject[u[0]]||{},e=(w[u[1]]||{})[u[2]]||"","html"===p?$(this).html(e):"date"===t?(e=moment.utc(e).local().format("YYYY-MM-DD"),$(this).html(e)):"date_time"===t?(e=moment.utc(e).local().format("YYYY-MM-DD HH:mm:ss"),
$(this).html(e)):"inputvalue"===p?$(this).val(e):"url"===p?$(this).html(checkToAddUrlValueToDOM(e)):"eventlocation"===p&&(q=$("\x3ca/\x3e").attr("href","javascript:").html(e).click(function(){var k=w.locationCode||"";k&&""!=k.trim()&&eModal.iframe("https://plus.codes/"+k,e)}),$(this).html(q)))}).promise().done(function(){"function"===typeof f&&f()})}else LeoAdminApiUtil.logErrorPayload(h)})};
var updateProfileDataToModel=function(b,d,a){$("#data_model_holder").find("*[data-field]").each(function(){var c=$(this).data("field"),f=$(this).data("fieldholder"),g=$(this).data("fieldtype");f="html"===f?$(this).html().trim():$(this).val();"int"===g?f=parseInt(f.replace(/,/g,"")):"float"===g?f=parseFloat(f.replace(/,/g,"")):"date"===g?f=new Date(f):"tel"===g&&(f=f.replace(/\D/g,""));c=c.split(".");1===c.length?LeoCdpAdmin.routerContext.dataObject[c[0]]=f:2===c.length&&(LeoCdpAdmin.routerContext.dataObject[c[0]][c[1]]=
f)}).promise().done(function(){LeoAdminApiUtil.callPostAdminApi(b,d,function(c){0===c.httpCode&&""===c.errorMessage?"function"===typeof a&&a(c):LeoAdminApiUtil.logErrorPayload(c)})})};window.profileTimeseriesChart=!1;
var loadProfileEventDailyReportUnit=function(b,d){var a=getDateFilterValues();a.profileId=b;b=a.beginFilterDate;$("#eventDataFromDate").text((new moment(b)).format("YYYY-MM-DD HH:mm:ss"));b=a.endFilterDate;$("#eventDataToDate").text((new moment(b)).format("YYYY-MM-DD HH:mm:ss"));LeoAdminApiUtil.getSecuredData(baseLeoAdminUrl+"/cdp/analytics360/event-report/profile",a,function(c){0===c.httpCode&&""===c.errorMessage?!0===d&&"object"===typeof window.profileTimeseriesChart?renderTimeseriesChart("timeseriesProfileEventChart",
c.data,!0,profileTimeseriesChart,!0):window.profileTimeseriesChart=renderTimeseriesChart("timeseriesProfileEventChart",c.data,!1,!1,!0):LeoAdminApiUtil.logErrorPayload(c)})};function handleProfileTabBehavioralInfo(){$("#event_flow_tabs a:first").click();$("#event_flow_vertital_tabs div:first").addClass("active")}function handleProfileTabExtInfo(){$("#profile_ext_info_tabs a:first").click();$("#profile_ext_info_vertital_tabs div:first").addClass("active")}
var renderEngagedTouchpoints=function(b){var d=$("#engaged_touchpoint_list");0<b.length&&d.empty();_.forEach(b,function(a){var c=_.template($("#engaged-touchpoint-tpl").html());a.updatedAt=moment.utc(a.updatedAt).local().format("YYYY-MM-DD HH:mm:ss");a.truncatedUrl=textTruncate(a.url,120);a.cssStyleDisplay="none";a.faIcon="fa-internet-explorer";a=c(a);d.append(a)})},loadRecommendedContents=function(){LeoAdminApiUtil.getSecuredData("/cdp/profile/recommended-contents",{profileId:viewProfileId,startIndex:0,
numberResult:systemConfig.leo_recommender.service_max_item_for_profile},function(b){var d=$("#recommended_content_list");b=b.data;0<b.length&&d.empty();_.forEach(b,function(a){var c=_.template($("#recommended-content-tpl").html());a.indexScore=d.find("\x3e div").length+1;a.updatedAt=moment.utc(a.updatedAt).local().format("YYYY-MM-DD HH:mm:ss");a=c(a);d.append(a)});new Sortable(d[0],{swap:!0,swapClass:"sortable_highlighted_item",animation:150,onEnd:function(a){var c=a.newIndex,f=a.swapItem;a=$(a.item).data("key");
f=$(f).data("key");var g=parseInt($("#rank_content_"+a).text());c+=1;$("#rank_content_"+a).text(c);$("#rank_content_"+f).text(g);var l={};$("#recommended_content_list span.rank_info").each(function(h){h=$(this).data("key");var r=parseInt($(this).text());l[h]=r;console.log(l)}).promise().done(function(){var h={rankingInfoList:JSON.stringify(l),graphName:"cdp_content_graph",profileId:viewProfileId,recommendationModel:1};LeoAdminApiUtil.callPostAdminApi("/cdp/profile/update-item-ranking",h,function(r){r.data?
iziToast.success({title:"Update Content Content Ranking",timeout:3E3,message:"Data is saved successfully!"}):LeoAdminApiUtil.logErrorPayload(r)})})}})})},loadRecommendedProducts=function(){LeoAdminApiUtil.getSecuredData("/cdp/profile/recommended-products",{profileId:viewProfileId,startIndex:0,numberResult:systemConfig.leo_recommender.service_max_item_for_profile},function(b){var d=$("#recommended_product_list");b=b.data;0<b.length&&d.empty();_.forEach(b,function(a){if(a.product){var c=_.template($("#recommended-product-tpl").html());
a.indexScore=d.find("\x3e div").length+1;a.updatedAt=moment.utc(a.updatedAt).local().format("YYYY-MM-DD HH:mm:ss");a=c(a);d.append(a)}});new Sortable(d[0],{swap:!0,swapClass:"sortable_highlighted_item",animation:150,onEnd:function(a){var c=a.newIndex,f=a.swapItem;a=$(a.item).data("key");f=$(f).data("key");var g=parseInt($("#rank_product_"+a).text());c+=1;$("#rank_product_"+a).text(c);$("#rank_product_"+f).text(g);var l={};$("#recommended_product_list span.rank_info").each(function(h){h=$(this).data("key");
var r=parseInt($(this).text());l[h]=r;console.log(l)}).promise().done(function(){var h={rankingInfoList:JSON.stringify(l),graphName:"cdp_product_graph",profileId:viewProfileId,recommendationModel:1};LeoAdminApiUtil.callPostAdminApi("/cdp/profile/update-item-ranking",h,function(r){r.data?iziToast.success({title:"Product Item Ranking",timeout:2200,message:"Data is saved successfully!"}):LeoAdminApiUtil.logErrorPayload(r)})})}});$("input.autoselectall").on("click",function(){$(this).select()})})},loadPurchasedItems=
function(){LeoAdminApiUtil.getSecuredData("/cdp/profile/get-purchased-items",{profileId:viewProfileId,startIndex:0,numberResult:100},function(b){var d=$("#purchased_items_list");b=b.data;0<b.length&&d.empty();_.forEach(b,function(a){var c=_.template($("#purchased-product-tpl").html());a.indexScore=d.find("\x3e div").length+1;a.createdAt=moment.utc(a.createdAt).local().format("YYYY-MM-DD HH:mm:ss");a=c(a);d.append(a)})})},loadFinancialEventList=function(){var b=$("#financial_event_list"),d=LeoCdpAdmin.routerContext.dataObject.financeCreditEvents;
0<d.length&&b.empty();_.forEach(d,function(a){var c=_.template($("#financial-event-tpl").html());"good"===a.risk?(a.riskIcon="fa-thumbs-o-up",a.riskIconColor="#45D50F"):(a.riskIcon="fa-thumbs-o-down",a.riskIconColor="#F40209");a.risk=a.risk.toUpperCase();a=c(a);b.append(a)})},emptyInfo='\x3cbr\x3e \x3cdiv style\x3d"font-size:24px;" class\x3d"text-center" \x3e No data available \x3ci class\x3d"fa fa-exclamation" aria-hidden\x3d"true"\x3e\x3c/i\x3e \x3c/div\x3e \x3cbr\x3e',loadEventsInProfileIndex=
0,loadEventsInProfileResult=25,loadEventsInProfile=function(b){$("#keywords_filter_events").val("");var d=$("#profile_activitiy_flow");0<d.find("li.all-loaded").length?console.log("Loaded all data for loadEventsInProfile"):(0===loadEventsInProfileIndex&&(d.empty().css("height","640px"),$("#keywords_filter_events").change(function(){2>$(this).val().trim().toLowerCase().length&&$("#profile_activitiy_flow li").show()})),$("#profile_activitiy_flow_loader").show(),LeoAdminApiUtil.getSecuredData("/cdp/profile/tracking-events",
{id:viewProfileId,startIndex:loadEventsInProfileIndex,numberResult:loadEventsInProfileResult},function(a){$("#profile_activitiy_flow_loader").hide();0===a.data.length&&(0===loadEventsInProfileIndex?(d.html(emptyInfo),$("#profileEventStatistics").html(emptyInfo)):(d.find("li:last-child").addClass("all-loaded"),$("#profile_activitiy_flow_done").show()));_.forEach(a.data,function(c){try{c.srcTouchpoint.name=textTruncate(decodeURI(c.srcTouchpoint.name),120);c.srcTouchpoint.truncatedUrl=textTruncate(c.srcTouchpoint.url,
120);c.createdAt=moment.utc(c.createdAt).local().format("YYYY-MM-DD HH:mm:ss");0<_.size(c.eventData)?c.cssStyleDisplay="block":c.cssStyleDisplay="none";var f=c.metricName,g="view-event-tpl";if("item-view"===f||"survey-view"===f||"course-view"===f||"content-view"===f)g="key-info-view-event-tpl";else if("purchase"===f||"subscribe"===f||"enroll"===f||"pay"===f)g="conversion-event-tpl";else if(0<=f.indexOf("click")||0<=f.indexOf("submit-")||0<=f.indexOf("play-")||0<=f.indexOf("-scan")||"order-checkout"===
f||"add-to-cart"===f||"like"===f||"trial"===f||"user-login"===f)g="action-event-tpl";var l=_.template($("#"+g).html())(c);d.append(l)}catch(h){console.error(h)}});"function"===typeof b?b():$("#profile_activitiy_flow_container").height(d.height()+50)}))};
function loadMoreEventsInProfile(){loadEventsInProfileIndex=$("#profile_activitiy_flow \x3e li").length;loadEventsInProfile(function(){$(document).scrollTop($(document).height()-100);$("#profile_activitiy_flow_container").scrollTop($("#profile_activitiy_flow_container").prop("scrollHeight")+200)})}
var filterEventFlow=function(){var b=$("#keywords_filter_events").val().trim().toLowerCase(),d=$("#profile_activitiy_flow li");2<=b.length&&d.each(function(){0>$(this).find("h5.media-heading").text().toLowerCase().indexOf(b)?$(this).hide():$(this).show()})},loadFeedbacksInProfileIndex=0,loadFeedbacksInProfileResult=120;
function loadFeedbackEventsInProfile(){$("#keyword_filter_feedbacks").val("");var b=$("#profile_feedback_flow");0===loadEventsInProfileIndex&&(b.empty(),$("#keywords_filter_events").change(function(){2>$(this).val().trim().toLowerCase().length&&$("#profile_activitiy_flow li").show()}));$("#profile_feedback_flow_loader").show();LeoAdminApiUtil.getSecuredData("/cdp/profile/feedback-events",{id:viewProfileId,startIndex:loadFeedbacksInProfileIndex,numberResult:loadFeedbacksInProfileResult},function(d){$("#profile_feedback_flow_loader").hide();
d=d.data;0===d.length?b.html('\x3cli class\x3d"list-group-item view" \x3e \x3cdiv class\x3d"list-group-item" \x3e No data available \x3c/div\x3e \x3c/li\x3e'):(b.css("height","650px"),_.forEach(d,function(a,c){a.createdAt=moment.utc(a.createdAt).local().format("YYYY-MM-DD HH:mm:ss");c=baseLeoObserverUrl+"/webform?\x26tplfbt\x3dSURVEY\x26tplid\x3d"+a.refTemplateId;a.previewUrl="SURVEY"===a.feedbackType?c:a.touchpointUrl;c=a.eventName;a.eventIcon="submit-feedback-form"===c?"fa-commenting-o":"submit-rating-form"===
c?"fa-star":"fa-smile-o";c=_.template($("#feedback-event-tpl").html());b.append(c(a))}))});$("#keyword_filter_feedbacks").change(function(){2>$(this).val().trim().toLowerCase().length&&$("#profile_feedback_flow li").show()})}function filterFeedbackEvent(){var b=$("#keyword_filter_feedbacks").val().trim().toLowerCase(),d=$("#profile_feedback_flow li");2<=b.length&&d.each(function(){0>$(this).find("h5.media-heading").text().toLowerCase().indexOf(b)?$(this).hide():$(this).show()})}
var deleteCurrentProfile=function(){var b=LeoCdpAdmin.routerContext.dataObject;b?0<Object.keys(b.eventStatistics).length&&1===b.status?notifyErrorMessage("The system can not delete a profile that has event data stream"):LeoCdpAdmin.navFunctions.deleteCustomerProfile(b.id):notifyErrorMessage("LeoCdpAdmin.routerContext.dataObject is NULL !")},reportJourneyOfSingleProfile=function(b,d){var a=$("#event_journey_funnel").parent().width()-15;$("#event_journey_funnel").parent().width(a);loadJourneyMapList(!1,
function(f){$("#event_journey_funnel").empty();c(f)});var c=function(f){LeoAdminApiUtil.getSecuredData(baseLeoAdminUrl+"/cdp/analytics360/event-report/journey-profile",{profileId:d,journeyMapId:f},function(g){if(0===g.httpCode&&""===g.errorMessage)if(0==g.data.total)$("#event_journey_funnel_nodata").show();else{$("#event_journey_funnel_nodata").hide();(new FunnelGraph({container:b,gradientDirection:"horizontal",data:{labels:journeyLabel5A,subLabels:["Event Data Point"],colors:[["#9ACAEF","#67B0E9",
"#309EF3"]],values:g.data.reportData},displayPercent:!0,direction:"horizontal",width:a,height:330,subLabelValue:"raw"})).draw();var l=0,h=g.data.funnelIndex;g.data.scoreCX&&(l=g.data.scoreCX.sentimentScore);g=$("#profileJourneyFunnel");90<=h?g.attr("class","progress-bar progress-bar-striped active progress-bar-danger"):50<=h&&90>h?g.attr("class","progress-bar progress-bar-striped active progress-bar-success"):g.attr("class","progress-bar progress-bar-striped active progress-bar-primary");$("#profileJourneySentimentScore").text(l);
$("#profileJourneyFunnelValue").text(h);g.attr("aria-valuenow",h).css("width",h+"%");$("#profile_funnel_report \x3e div").removeClass("funnel-stage-active");l=Math.floor(h/10);for(h=1;h<=l;h++)$("#profile_funnel_stage_"+h).addClass("funnel-stage-active")}else LeoAdminApiUtil.logErrorPayload(g)})};c("id_default_journey")};