'use strict';function profileAddNewTextHashSet(a){var d=$('\x3cli class\x3d"list-group-item" \x3e\x3cdiv class\x3d"row" \x3e\x3cdiv class\x3d"col-md-11" \x3e\x3cinput class\x3d"form-control" type\x3d"text" placeholder\x3d"Value" data-fieldholder\x3d"hashset" data-fieldtype\x3d"string" autocomplete\x3d"off"\x3e\x3c/div\x3e\x3cdiv class\x3d"col-md-1" \x3e\x3ch4 onclick\x3d"$(this).parent().parent().parent().remove()" \x3e\x3ci class\x3d"fa fa-times-circle delete-item-btn" aria-hidden\x3d"true"\x3e\x3c/i\x3e\x3c/h4\x3e \x3c/div\x3e\x3c/div\x3e\x3c/li\x3e');
$('p[data-field\x3d"'+a+'"] \x3e ul').append(d);d.effect("highlight",{},4E3)}function profileAddNewCustomField(a){var d=$(loadCustomFieldEditor(a,"",""));$('p[data-field\x3d"'+a+'"] \x3e ul').append(d);d.effect("highlight",{},4E3)}function handleProfileListFiltersBy(a,d){$("#profile_filter_inputs \x3e .form-control").val("").hide();$(d).show();$("#profile_filter_input_label").text($(a).text()).show();$("#main_search_profile").val("");showDeleteNotActiveProfile()}
var addNewHashMapItem=function(a,d){var c=a+"_"+(new Date).getTime(),b=$("#"+a),e=Object.assign({},d);b.find("option:selected").each(function(){var l=$(this).val();delete e[l]});a=$(loadHashMapSelector(c,a,e,"",""));b.find("ul.list-group").append(a);a.effect("highlight",{},4E3)};function removeHashMapItem(a){$(a).parent().parent().remove()}
function loadHashMapSelector(a,d,c,b,e){var l='\x3cdiv class\x3d"col-md-3" \x3e \x3cselect class\x3d"form-control" id\x3d"key_'+a+'" name\x3d"'+d+'" \x3e';_.forOwn(c,function(n,h){n='\x3coption name\x3d"'+d+'" value\x3d"'+h+'"\x3e '+h.toUpperCase()+" \x3c/option\x3e";h===b&&(n='\x3coption name\x3d"'+d+'" selected value\x3d"'+h+'"\x3e '+h.toUpperCase()+" \x3c/option\x3e");l+=n});l+=" \x3c/select\x3e \x3c/div\x3e";""===b&&$("#key_"+a).find("option:first").attr("selected","selected");return'\x3cli id\x3d"item_'+
a+'" class\x3d"list-group-item" \x3e\x3cdiv class\x3d"row" \x3e '+l+('\x3cdiv class\x3d"col-md-8" \x3e\x3cinput id\x3d"value_'+a+'" value\x3d"'+(e?e:"")+'" class\x3d"form-control" type\x3d"text" placeholder\x3d"Value" data-fieldholder\x3d"hashmap" data-fieldtype\x3d"string" autocomplete\x3d"off"\x3e\x3c/div\x3e\x3cdiv title\x3d"Delete" class\x3d"col-md-1" onclick\x3d"removeHashMapItem(this)" \x3e \x3ch4\x3e\x3ci class\x3d"fa fa-times-circle delete-item-btn" aria-hidden\x3d"true"\x3e\x3c/i\x3e\x3c/h4\x3e \x3c/div\x3e \x3c/div\x3e\x3c/li\x3e')}
function loadCustomFieldEditor(a,d,c){return'\x3cli class\x3d"list-group-item" \x3e\x3cdiv class\x3d"row" \x3e \x3cdiv class\x3d"col-md-3" \x3e \x3cinput type\x3d"text" class\x3d"form-control custom_field_name" placeholder\x3d"Field Name" value\x3d"'+(d+'"\x3e \x3c/div\x3e\x3cdiv class\x3d"col-md-8" \x3e\x3cinput class\x3d"form-control custom_field_value" type\x3d"text" value\x3d"')+((c?c:"")+'" placeholder\x3d"Field Value" data-fieldholder\x3d"hashmap" data-fieldtype\x3d"string" autocomplete\x3d"off"\x3e\x3c/div\x3e\x3cdiv title\x3d"Delete" class\x3d"col-md-1" onclick\x3d"removeHashMapItem(this)" \x3e \x3ch4\x3e\x3ci class\x3d"fa fa-times-circle delete-item-btn" aria-hidden\x3d"true"\x3e\x3c/i\x3e\x3c/h4\x3e \x3c/div\x3e \x3c/div\x3e\x3c/li\x3e')}
const loadProfileDataIntoDOM=function(a,d,c,b,e){var l=!1,n={};"string"===typeof d?(l="/cdp/profile/get",n.id=d):"string"===typeof c&&(l="/cdp/profile/get-by-crm-id",n.crmRefId=c);!1===l?(console.error("loadProfileDataIntoDOM is failed, profileId or crmRefId must be a valid string! "),console.log("urlStr "+l),console.log("params "+n)):LeoAdminApiUtil.callPostAdminApi(baseLeoAdminUrl+l,n,function(h){if(0===h.httpCode&&""===h.errorMessage){var f=h.canInsertData,g=h.canDeleteData;h.canEditData||$("button.data-control-edit").attr("disabled",
"disabled");g||$("button.data-control-delete").attr("disabled","disabled");f||$("button.data-control-insert").attr("disabled","disabled");LeoCdpAdmin.routerContext.dataObject="function"===typeof b?b(h.data):h.data;$("#data_model_holder").find("*[data-field]").each(function(){$(this).prop("tagName");var m=$(this).attr("type"),q=$(this).data("fieldholder"),u=$(this).data("fieldtype"),v=$(this).data("field"),w=v.split(".");if(1===w.length){var k=LeoCdpAdmin.routerContext.dataObject[w[0]];if("html"===
q){if("int"===u||"float"===u)if(void 0===k||null==k)k="-";else{if(k=(new Number(k)).toLocaleString(),NaN==k||"NaN"==k)k="-"}else"date"===u?k=k?moment.utc(k).local().format("YYYY-MM-DD"):"-":"date_time"===u?k=k?moment.utc(k).local().format("YYYY-MM-DD HH:mm:ss"):"-":"phone"===u&&(k=k?k.replace(/\D/g,""):"-");$(this).html(k)}else if("percentage"===q)$(this).html(k).parent().attr("aria-valuenow",k).css("width",k+"%"),m=$(this).parent(),m.attr("title",k+"% "+m.attr("title"));else if("url"===q)$(this).html(checkToAddUrlValueToDOM(k));
else if("locationcode"===q)m=$("\x3ca/\x3e").attr("href","javascript:").html(textTruncate(k,80)).click(function(){var p=LeoCdpAdmin.routerContext.dataObject.locationCode;0===p.indexOf("http")?eModal.iframe(p,"Location"):p&&""!=p.trim()&&eModal.iframe("https://plus.codes/"+p,k)}),$(this).html(m);else if("inputvalue"===q)"radio"===m||"checkbox"===m?k==$(this).val()&&$(this).attr("checked","checked"):$(this).val(k);else if("html_hashmap"===q){var r=' \x3cul class\x3d"list-group" \x3e ';_.forOwn(k,function(p,
t){t=t.trim();a?(p=loadHashMapSelector(v+"_"+t,v,"socialMediaProfiles"===v?SocialMediaIconMap:"personalContacts"===v?PersonalContactIconsMap:ContactIconsMap,t,p),r+=p):(t="socialMediaProfiles"===v?SocialMediaIconMap[t]?SocialMediaIconMap[t]:!1:"personalContacts"===v?PersonalContactIconsMap[t]?PersonalContactIconsMap[t]:!1:ContactIconsMap[t]?ContactIconsMap[t]:!1,!1===t&&(t=' \x3ci class\x3d"fa fa-info-circle" aria-hidden\x3d"true"\x3e\x3c/i\x3e '),r=r+'\x3cli class\x3d"list-group-item" \x3e '+t+checkToAddUrlValueToDOM(p)+
"\x3c/li\x3e")});r+=" \x3c/ul\x3e ";$(this).html(r)}else"html_hashset"===q?(r='\x3cul class\x3d"list-group" \x3e',_.forOwn(k,function(p,t){p=a?'\x3cdiv class\x3d"col-md-11" \x3e\x3cinput value\x3d"'+p+'" class\x3d"form-control" type\x3d"text" placeholder\x3d"Value" data-fieldholder\x3d"hashset" data-fieldtype\x3d"string" autocomplete\x3d"off"\x3e\x3c/div\x3e\x3cdiv class\x3d"col-md-1" \x3e\x3ch4 onclick\x3d"$(this).parent().parent().parent().remove()" \x3e\x3ci class\x3d"fa fa-times-circle delete-item-btn" aria-hidden\x3d"true"\x3e\x3c/i\x3e\x3c/h4\x3e\x3c/div\x3e':
"system_user"===u?' \x3cdiv class\x3d"col-md-12" \x3e \x3cb\x3e \x3ci class\x3d"fa fa-info-circle" aria-hidden\x3d"true"\x3e\x3c/i\x3e\x3c/b\x3e '+buildSystemUserInfoLink(p)+"\x3c/div\x3e":' \x3cdiv class\x3d"col-md-12" \x3e \x3cb\x3e \x3ci class\x3d"fa fa-info-circle" aria-hidden\x3d"true"\x3e\x3c/i\x3e\x3c/b\x3e '+checkToAddUrlValueToDOM(p)+"\x3c/div\x3e";r=r+'\x3cli class\x3d"list-group-item" \x3e \x3cdiv class\x3d"row" \x3e '+p+"\x3c/div\x3e\x3c/li\x3e"}),r+="\x3c/ul\x3e",$(this).html(r)):"html_list_key_value"===
q?(r='\x3cul class\x3d"list-group" \x3e',m=Object.keys(k),m.sort(),m.forEach(function(p){r=r+'\x3cli class\x3d"list-group-item" \x3e '+p+'  \x3ci class\x3d"fa fa-arrow-right" aria-hidden\x3d"true"\x3e\x3c/i\x3e  '+k[p]+"\x3c/li\x3e"}),r+="\x3c/ul\x3e",$(this).html(r)):"html_custom_field"===q&&(r=' \x3cul class\x3d"list-group" \x3e ',_.forOwn(k,function(p,t){t=t.trim();a?(p=loadCustomFieldEditor(v+"_"+t,t,p),r+=p):(r+='\x3cli class\x3d"list-group-item" \x3e',r+='\x3cdiv class\x3d"row" \x3e \x3cdiv class\x3d"col-md-3"\x3e \x3cb\x3e '+
t+'\x3c/b\x3e \x3ci  style\x3d"font-size:20px" class\x3d"fa fa-equals" aria-hidden\x3d"true"\x3e\x3c/i\x3e \x3c/div\x3e',r+='\x3cdiv class\x3d"col-md-9"\x3e'+p+"\x3c/div\x3e \x3c/div\x3e\x3c/li\x3e")}),r+=" \x3c/ul\x3e ",$(this).html(r))}else if(2===w.length){var x=LeoCdpAdmin.routerContext.dataObject[w[0]]||{};k=x[w[1]]||"";"html"===q?$(this).html(k):"date"===u?(k=moment.utc(k).local().format("YYYY-MM-DD"),$(this).html(k)):"date_time"===u?(k=moment.utc(k).local().format("YYYY-MM-DD HH:mm:ss"),$(this).html(k)):
"inputvalue"===q?$(this).val(k):"url"===q?$(this).html(checkToAddUrlValueToDOM(k)):"eventlocation"===q&&(m=$("\x3ca/\x3e").attr("href","javascript:").html(k).click(function(){var p=x.locationCode||"";p&&""!=p.trim()&&eModal.iframe("https://plus.codes/"+p,k)}),$(this).html(m))}else 3===w.length&&(x=LeoCdpAdmin.routerContext.dataObject[w[0]]||{},k=(x[w[1]]||{})[w[2]]||"","html"===q?$(this).html(k):"date"===u?(k=moment.utc(k).local().format("YYYY-MM-DD"),$(this).html(k)):"date_time"===u?(k=moment.utc(k).local().format("YYYY-MM-DD HH:mm:ss"),
$(this).html(k)):"inputvalue"===q?$(this).val(k):"url"===q?$(this).html(checkToAddUrlValueToDOM(k)):"eventlocation"===q&&(m=$("\x3ca/\x3e").attr("href","javascript:").html(k).click(function(){var p=x.locationCode||"";p&&""!=p.trim()&&eModal.iframe("https://plus.codes/"+p,k)}),$(this).html(m)))}).promise().done(function(){"function"===typeof e&&e()})}else LeoAdminApiUtil.logErrorPayload(h)})};
var updateProfileDataToModel=function(a,d,c){$("#data_model_holder").find("*[data-field]").each(function(){var b=$(this).data("field"),e=$(this).data("fieldholder"),l=$(this).data("fieldtype");e="html"===e?$(this).html().trim():$(this).val();"int"===l?e=parseInt(e.replace(/,/g,"")):"float"===l?e=parseFloat(e.replace(/,/g,"")):"date"===l?e=new Date(e):"tel"===l&&(e=e.replace(/\D/g,""));b=b.split(".");1===b.length?LeoCdpAdmin.routerContext.dataObject[b[0]]=e:2===b.length&&(LeoCdpAdmin.routerContext.dataObject[b[0]][b[1]]=
e)}).promise().done(function(){LeoAdminApiUtil.callPostAdminApi(a,d,function(b){0===b.httpCode&&""===b.errorMessage?"function"===typeof c&&c(b):LeoAdminApiUtil.logErrorPayload(b)})})};window.profileTimeseriesChart=!1;
var loadProfileEventDailyReportUnit=function(a,d){var c=getDateFilterValues();c.profileId=a;a=c.beginFilterDate;$("#eventDataFromDate").text((new moment(a)).format("YYYY-MM-DD HH:mm:ss"));a=c.endFilterDate;$("#eventDataToDate").text((new moment(a)).format("YYYY-MM-DD HH:mm:ss"));a=baseLeoAdminUrl+"/cdp/analytics360/event-report/profile";$("#profile_event_report_loader").show();LeoAdminApiUtil.getSecuredData(a,c,function(b){$("#profile_event_report_loader").hide();0===b.httpCode&&""===b.errorMessage?
(!0===d&&"object"===typeof window.profileTimeseriesChart?renderTimeseriesChart("timeseriesProfileEventChart",b.data,!0,profileTimeseriesChart,!0):window.profileTimeseriesChart=renderTimeseriesChart("timeseriesProfileEventChart",b.data,!1,!1,!0),loadEventsInProfile()):LeoAdminApiUtil.logErrorPayload(b)})};function handleProfileTabBehavioralInfo(){$("#event_flow_tabs a:first").click();$("#event_flow_vertital_tabs div:first").addClass("active")}
function handleProfileTabExtInfo(){$("#profile_ext_info_tabs a:first").click();$("#profile_ext_info_vertital_tabs div:first").addClass("active")}
var loadRecommendedContentsForProfile=function(a,d,c){var b=systemConfig.leo_recommender.service_max_item_for_profile,e=$("#recommended_content_list").empty().html('\x3cdiv class\x3d"loader"\x3e\x3c/div\x3e');LeoAdminApiUtil.getSecuredData("/cdp/profile/recommended-contents",{profileId:a,startIndex:0,numberResult:b},function(l){l=l.data;var n=l.length;0<n?e.empty():e.empty().html('\x3cdiv class\x3d"text-center" style\x3d"padding: 10px"\x3e No data available \x3c/div\x3e');_.forEach(l,function(h){var f=
_.template($("#recommended-content-tpl").html());h.indexScore=e.find("\x3e div").length+1;h.updatedAt=moment.utc(h.updatedAt).local().format("YYYY-MM-DD HH:mm:ss");h=f(h);e.append(h)});!0===d&&new Sortable(e[0],{swap:!0,swapClass:"sortable_highlighted_item",animation:150,onEnd:function(h){var f=h.newIndex,g=h.swapItem;h=$(h.item).data("key");g=$(g).data("key");var m=parseInt($("#rank_content_"+h).text());f+=1;$("#rank_content_"+h).text(f);$("#rank_content_"+g).text(m);var q={};$("#recommended_content_list span.rank_info").each(function(u){u=
$(this).data("key");var v=parseInt($(this).text());q[u]=v;console.log(q)}).promise().done(function(){var u={rankingInfoList:JSON.stringify(q),graphName:"cdp_content_graph",profileId:a,recommendationModel:1};LeoAdminApiUtil.callPostAdminApi("/cdp/profile/update-item-ranking",u,function(v){v.data?iziToast.success({title:"Update Content Content Ranking",timeout:3E3,message:"Data is saved successfully!"}):LeoAdminApiUtil.logErrorPayload(v)})})}});"function"===typeof c&&c(n)})},loadRecommendedProductsForProfile=
function(a,d,c){var b=systemConfig.leo_recommender.service_max_item_for_profile,e=$("#recommended_product_list").empty().html('\x3cdiv class\x3d"loader"\x3e\x3c/div\x3e');LeoAdminApiUtil.getSecuredData("/cdp/profile/recommended-products",{profileId:a,startIndex:0,numberResult:b},function(l){l=l.data;var n=l.length;0<n?e.empty():e.empty().html('\x3cdiv class\x3d"text-center" style\x3d"padding: 10px"\x3e No data available \x3c/div\x3e');_.forEach(l,function(h){if(h.product){var f=_.template($("#recommended-product-tpl").html());
h.indexScore=e.find("\x3e div").length+1;h.updatedAt=moment.utc(h.updatedAt).local().format("YYYY-MM-DD HH:mm:ss");h=f(h);e.append(h)}});!0===d&&new Sortable(e[0],{swap:!0,swapClass:"sortable_highlighted_item",animation:150,onEnd:function(h){var f=h.newIndex,g=h.swapItem;h=$(h.item).data("key");g=$(g).data("key");var m=parseInt($("#rank_product_"+h).text());f+=1;$("#rank_product_"+h).text(f);$("#rank_product_"+g).text(m);var q={};$("#recommended_product_list span.rank_info").each(function(u){u=$(this).data("key");
var v=parseInt($(this).text());q[u]=v;console.log(q)}).promise().done(function(){var u={rankingInfoList:JSON.stringify(q),graphName:"cdp_product_graph",profileId:a,recommendationModel:1};LeoAdminApiUtil.callPostAdminApi("/cdp/profile/update-item-ranking",u,function(v){v.data?iziToast.success({title:"Product Item Ranking",timeout:2200,message:"Data is saved successfully!"}):LeoAdminApiUtil.logErrorPayload(v)})})}});$("input.autoselectall").on("click",function(){$(this).select()});"function"===typeof c&&
c(n)})},loadPurchasedItems=function(){LeoAdminApiUtil.getSecuredData("/cdp/profile/get-purchased-items",{profileId:viewProfileId,startIndex:0,numberResult:100},function(a){var d=$("#purchased_items_list");a=a.data;0<a.length&&d.empty();_.forEach(a,function(c){var b=_.template($("#purchased-product-tpl").html());c.indexScore=d.find("\x3e div").length+1;c.createdAt=moment.utc(c.createdAt).local().format("YYYY-MM-DD HH:mm:ss");c=b(c);d.append(c)})})},loadFinancialEventList=function(){var a=$("#financial_event_list"),
d=LeoCdpAdmin.routerContext.dataObject.financeCreditEvents;0<d.length&&a.empty();_.forEach(d,function(c){var b=_.template($("#financial-event-tpl").html());"good"===c.risk?(c.riskIcon="fa-thumbs-o-up",c.riskIconColor="#45D50F"):(c.riskIcon="fa-thumbs-o-down",c.riskIconColor="#F40209");c.risk=c.risk.toUpperCase();c=b(c);a.append(c)})},emptyInfo='\x3cbr\x3e \x3cdiv style\x3d"font-size:24px;" class\x3d"text-center" \x3e No data available \x3ci class\x3d"fa fa-exclamation" aria-hidden\x3d"true"\x3e\x3c/i\x3e \x3c/div\x3e \x3cbr\x3e',
loadEventsInProfileIndex=0,loadEventsInProfileResult=25,loadEventsInProfile=function(a){$("#keywords_filter_events").val("");var d=$("#profile_activitiy_flow");0<d.find("li.all-loaded").length?console.log("Loaded all data for loadEventsInProfile"):(0===loadEventsInProfileIndex&&(d.empty().css("height","640px"),$("#keywords_filter_events").change(function(){2>$(this).val().trim().toLowerCase().length&&$("#profile_activitiy_flow li").show()})),$("#profile_activitiy_flow_loader").show(),LeoAdminApiUtil.getSecuredData("/cdp/profile/tracking-events",
{id:viewProfileId,startIndex:loadEventsInProfileIndex,numberResult:loadEventsInProfileResult},function(c){$("#profile_activitiy_flow_loader").hide();0===c.data.length&&(0===loadEventsInProfileIndex?(d.html(emptyInfo),$("#profileEventStatistics").html(emptyInfo)):(d.find("li:last-child").addClass("all-loaded"),$("#profile_activitiy_flow_done").show()));_.forEach(c.data,function(b){try{b.srcTouchpoint.name=textTruncate(decodeURI(b.srcTouchpoint.name),120);b.srcTouchpoint.truncatedUrl=textTruncate(b.srcTouchpoint.url,
120);b.createdAt=moment.utc(b.createdAt).local().format("YYYY-MM-DD HH:mm:ss");0<_.size(b.eventData)?b.cssStyleDisplay="block":b.cssStyleDisplay="none";var e=b.journeyStage,l=b.transactionValue,n=_.template($("#"+(4===e&&0<l?"conversion-event-tpl":3<=e?"action-event-tpl":2===e?"key-info-view-event-tpl":"view-event-tpl")).html())(b);d.append(n)}catch(h){console.error(h)}});"function"===typeof a?a():$("#profile_activitiy_flow_container").height(d.height()+50)}))};
function loadMoreEventsInProfile(){loadEventsInProfileIndex=$("#profile_activitiy_flow \x3e li").length;loadEventsInProfile(function(){$(document).scrollTop($(document).height()-100);$("#profile_activitiy_flow_container").scrollTop($("#profile_activitiy_flow_container").prop("scrollHeight")+200)})}
var filterEventFlow=function(){var a=$("#keywords_filter_events").val().trim().toLowerCase(),d=$("#profile_activitiy_flow li");2<=a.length&&d.each(function(){0>$(this).find("h5.media-heading").text().toLowerCase().indexOf(a)?$(this).hide():$(this).show()})},loadFeedbacksInProfileIndex=0,loadFeedbacksInProfileResult=120;
function loadFeedbackEventsInProfile(){$("#keyword_filter_feedbacks").val("");var a=$("#profile_feedback_flow");0===loadEventsInProfileIndex&&(a.empty(),$("#keywords_filter_events").change(function(){2>$(this).val().trim().toLowerCase().length&&$("#profile_activitiy_flow li").show()}));$("#profile_feedback_flow_loader").show();LeoAdminApiUtil.getSecuredData("/cdp/profile/feedback-events",{id:viewProfileId,startIndex:loadFeedbacksInProfileIndex,numberResult:loadFeedbacksInProfileResult},function(d){$("#profile_feedback_flow_loader").hide();
d=d.data;0===d.length?a.html('\x3cli class\x3d"list-group-item view" \x3e \x3cdiv class\x3d"list-group-item" \x3e No data available \x3c/div\x3e \x3c/li\x3e'):(a.css("height","650px"),_.forEach(d,function(c,b){c.createdAt=moment.utc(c.createdAt).local().format("YYYY-MM-DD HH:mm:ss");b=baseLeoObserverUrl+"/webform?\x26tplfbt\x3dSURVEY\x26tplid\x3d"+c.refTemplateId;c.previewUrl="SURVEY"===c.feedbackType?b:c.touchpointUrl;b=c.eventName;c.eventIcon="submit-feedback-form"===b?"fa-commenting-o":"submit-rating-form"===
b?"fa-star":"fa-smile-o";b=$("RATING"===c.feedbackType?"#feedback-rating-event-tpl":"#feedback-survey-event-tpl").html();b=_.template(b);a.append(b(c))}))});$("#keyword_filter_feedbacks").change(function(){2>$(this).val().trim().toLowerCase().length&&$("#profile_feedback_flow li").show()})}
function filterFeedbackEvent(){var a=$("#keyword_filter_feedbacks").val().trim().toLowerCase(),d=$("#profile_feedback_flow li");2<=a.length&&d.each(function(){0>$(this).find("h5.media-heading").text().toLowerCase().indexOf(a)?$(this).hide():$(this).show()})}
function removeCurrentProfile(){var a=LeoCdpAdmin.routerContext.dataObject;a?0<Object.keys(a.eventStatistics).length&&1===a.status?notifyErrorMessage("The system can not delete a profile that has event data stream"):LeoCdpAdmin.navFunctions.removeCustomerProfile(a.id):notifyErrorMessage("LeoCdpAdmin.routerContext.dataObject is NULL !")}
function deduplicateCurrentProfile(){var a=LeoCdpAdmin.routerContext.dataObject;a&&LeoAdminApiUtil.callPostAdminApi("/cdp/profile/deduplicate",{profileId:a.id},function(d){0===d.httpCode&&""===d.errorMessage?"number"===typeof d.data&&iziToast.info({title:"Merge Duplicate Profile",message:"Total Processed Profile: "+d.data}):LeoAdminApiUtil.logErrorPayload(d)})}
function removeSelectedProfiles(){$("#delete_callback").val("");$("#confirmDeleteDialog").modal({focus:!0});var a=Object.keys(window.selectedProfileIdMap||{}).length;0<a&&""===$("#filterProfileListByStatus").val()&&($("#deletedInfoTitle").text("Total Selected Profile \x3d "+a).show(),$("#deletedInfoMsg").text("Do you want to remove selected profiles?"),window.removeSelectedProfilesConfirmOk=function(){LeoAdminApiUtil.callPostAdminApi("/cdp/profiles/batch-update",selectedProfileIdMap,function(d){0===
d.httpCode&&""===d.errorMessage?(iziToast.info({title:"Customer Profile Management",message:"Total removed profile is "+d.data+" !"}),_.forOwn(selectedProfileIdMap,function(c,b){delete selectedProfileIdMap[b]}),resetProfileSearch()):LeoAdminApiUtil.logErrorPayload(d)})},$("#delete_callback").val("removeSelectedProfilesConfirmOk"))}
function deleteNotActiveProfile(){$("#delete_callback").val("");$("#deletedInfoTitle").empty().hide();var a=$("#filterProfileListByStatus option:selected").text().trim();$("#deletedInfoMsg").text("Do you want to delete ALL "+a+" ?");$("#confirmDeleteDialog").modal({focus:!0});window.deleteNotActiveProfileConfirmOk=function(){var d=$("#filterProfileListByStatus").val(),c=-4;""!=d&&(c=parseInt(d));LeoAdminApiUtil.callPostAdminApi("/cdp/profiles/delete-not-active",{status:c},function(b){0===b.httpCode&&
""===b.errorMessage?(iziToast.info({title:"Profile Data Management",message:"Deleted "+b.data+" profiles"}),resetProfileSearch()):LeoAdminApiUtil.logErrorPayload(b)})};$("#delete_callback").val("deleteNotActiveProfileConfirmOk")}
function loadProfileJourneyFlowReport(a,d){$("#journeyFlowChart").parent().hide();LeoAdminApiUtil.getSecuredData("/cdp/analytics360/journey-flow-report",{journeyMapId:d,profileId:a},function(c){if(0<c.errorCode)iziToast.error({title:"Data Journey Map",message:c.errorMessage});else{var b=c.data;c=b.defaultMetricName;var e=b.journeyStages,l=b.journeyLinks,n=b.journeyNodes;b=b.touchpointHubMap;$("#journeyFlowChart").parent().show();renderJourneyFlowChart("#journeyFlowChart",c,e,n,l,b)}})}
const renderProfileBarChart=function(a,d){if(d){var c=[],b=[];$.each(d,function(e,l){c.push(e);b.push(l)});renderHorizontalBarChart(a,c,b)}else $("#"+a).html("\x3ch4\x3e No data available \x3c/h4\x3e")},loadProfileEventMatrix=function(a,d){var c={};c.profileId=a;c.journeyMapId=d;LeoAdminApiUtil.getSecuredData(baseLeoAdminUrl+"/cdp/analytics360/event-matrix",c,function(b){0===b.httpCode&&""===b.errorMessage?(b=b.data,renderMatrixChart("Event Matrix Report","profile_event_matrix",b.xLabels,b.yLabels,
b.dataList)):LeoAdminApiUtil.logErrorPayload(b)})},loadJourneyReportForProfile=function(a,d){var c=currentJourneyMapId||"id_default_journey",b={};$.each(d.eventStatistics,function(e,l){var n=e.indexOf("-");if(0>n)b[c]="object"===typeof b[c]?b[c]:{},b[c][e]=l;else{var h=e.substring(0,n).trim();e=e.substring(n+1);b[h]="object"===typeof b[h]?b[h]:{};b[h][e]=l;b[""]="object"===typeof b[""]?b[""]:{};b[""][e]="number"===typeof b[""][e]?b[""][e]+l:l}});renderProfileBarChart("profileEventStatsChart",b[c]);
renderProfileBarChart("profileReferrerChannels",d.referrerChannels);loadJourneyMapList(!1,function(e,l){$("#profileJourneyName").text(l);$("#event_journey_funnel").empty();loadEventJourneyProfile(a,e);loadProfileEventMatrix(a,e);setTimeout(function(){loadTouchpointFlowForProfile(a,e);loadTouchpointHubReportForProfile(a,e);renderProfileBarChart("profileEventStatsChart",b[e])},2E3)},!0,function(e,l){$("#profileJourneyName").text(l)});loadEventJourneyProfile(a,c);setTimeout(function(){loadTouchpointHubReportForProfile(a,
c)},800);setTimeout(function(){loadProfileEventMatrix(a,c)},1200);setTimeout(function(){loadTouchpointFlowForProfile(a,c)},1600)},loadTouchpointHubReportForProfile=function(a,d){$("#profileObserverChart").html('\x3cdiv class\x3d"loader"\x3e\x3c/div\x3e');LeoAdminApiUtil.getSecuredData(baseLeoAdminUrl+"/cdp/analytics360/touchpoint-hub-report",{profileId:a,journeyMapId:d},function(c){if(0===c.httpCode&&""===c.errorMessage)if(c=c.data,0<c.length){var b=[],e=[];c.forEach(function(l){b.push(l.name);e.push(l.eventCount)});
renderHorizontalBarChart("profileObserverChart",b,e)}else $("#profileObserverChart").html("\x3ch4\x3e No data available \x3c/h4\x3e");else LeoAdminApiUtil.logErrorPayload(c)})},renderProfileTouchpointChart=function(a,d,c,b){$("#profileTouchpointChart").html('\x3cdiv class\x3d"loader"\x3e\x3c/div\x3e');LeoAdminApiUtil.getSecuredData(baseLeoAdminUrl+"/cdp/analytics360/touchpoint-report",{profileId:a,touchpointType:d,startIndex:c,numberResult:b},function(e){if(0===e.httpCode&&""===e.errorMessage){e=
e.data;var l=$("#engaged_touchpoint_list");if(0<e.length){l.empty();var n=[],h=[];e.forEach(function(f){var g=f.touchpoint,m=textTruncate(g.name,60);n.push(m);h.push(f.eventCount);m=_.template($("#engaged-touchpoint-tpl").html());g.updatedAt=moment.utc(g.updatedAt).local().format("YYYY-MM-DD HH:mm:ss");g.truncatedUrl=textTruncate(g.url,120);""===g.locationCode&&(g.cssShowLocationCode="none");g.eventCount=f.eventCount;l.append(m(g))});renderHorizontalBarChart("profileTouchpointChart",n,h)}else $("#profileTouchpointChart").html("\x3ch4\x3e No data available \x3c/h4\x3e")}else LeoAdminApiUtil.logErrorPayload(e)})},
loadEventJourneyProfile=function(a,d){var c=$("#event_journey_funnel").parent().width()-15;a={profileId:a,journeyMapId:d};d=baseLeoAdminUrl+"/cdp/analytics360/event-report/journey-profile";$("#event_journey_funnel_info").html('\x3cdiv class\x3d"loader"\x3e\x3c/div\x3e');LeoAdminApiUtil.getSecuredData(d,a,function(b){if(0===b.httpCode&&""===b.errorMessage){var e=b.data.total,l=0,n=b.data.funnelIndex;b.data.scoreCX&&(l=b.data.scoreCX.sentimentScore);var h=$("#profileJourneyFunnel");90<=n?h.attr("class",
"progress-bar progress-bar-striped active progress-bar-danger"):50<=n&&90>n?h.attr("class","progress-bar progress-bar-striped active progress-bar-success"):h.attr("class","progress-bar progress-bar-striped active progress-bar-primary");$("#profileJourneySentimentScore").text(l);$("#profileJourneyFunnelValue").text(n);h.attr("aria-valuenow",n).css("width",n+"%");$("#profile_funnel_report \x3e div").removeClass("funnel-stage-active");l=Math.floor(n/10);for(n=1;n<=l;n++)$("#profile_funnel_stage_"+n).addClass("funnel-stage-active");
0==e?($("#event_journey_funnel_info").html("\x3cp\x3eNo data available\x3c/p\x3e").show(),$("#journeyFlowChart").hide()):($("#event_journey_funnel_info").empty().hide(),$("#journeyFlowChart").show(),(new FunnelGraph({container:"#event_journey_funnel",gradientDirection:"horizontal",data:{labels:journeyLabel5A,subLabels:["Event Data Point"],colors:[["#9ACAEF","#67B0E9","#309EF3"]],values:b.data.reportData},displayPercent:!0,direction:"horizontal",width:c,height:330,subLabelValue:"raw"})).draw())}else LeoAdminApiUtil.logErrorPayload(b)})},
loadTouchpointFlowForProfile=function(a,d){var c=$("#profileTouchpointFlow");a={profileId:a,journeyMapId:d,beginFilterDate:"",endFilterDate:""};d=baseLeoAdminUrl+"/cdp/analytics360/touchpoint-flow-report";c.html('\x3cdiv class\x3d"loader"\x3e\x3c/div\x3e');LeoAdminApiUtil.getSecuredData(d,a,function(b){0===b.httpCode&&""===b.errorMessage?(c.empty(),renderDirectedGraph("profileTouchpointFlow",{nodes:b.data.nodes,edges:b.data.edges},b.data.rootNodeId)):LeoAdminApiUtil.logErrorPayload(b)})},profileInfoLoadProcessor=
function(a){viewProfileId=a.id;a.fullName=""!==a.firstName||""!==a.lastName?a.firstName+" "+a.lastName:"Web Visitor";0>=a.age&&(a.age="-");""===a.livingLocation&&(a.livingLocation="_");""===a.primaryPhone&&(a.primaryPhone="-");""===a.firstName&&(a.firstName="-");""===a.lastName&&(a.lastName="-");""===a.primaryEmail&&(a.primaryEmail="-");if("number"===typeof a.jobType){var d=a.jobType;a.jobTypeAsString=0===d?"UNSKILLED AND NON-RESIDENT":1===d?"UNSKILLED AND RESIDENT":2===d?"SKILLED":3===d?"HIGHLY SKILLED":
"-"}a.funnelStage=a.funnelStage?a.funnelStage.toUpperCase():"-";a.lastTrackingEvent?(a.lastTrackingEvent.createdAt=moment.utc(a.lastTrackingEvent.createdAt).local().format("YYYY-MM-DD HH:mm:ss"),a.lastTrackingEvent.fingerprintId=a.lastTrackingEvent.fingerprintId?a.lastTrackingEvent.fingerprintId:"-",a.lastTrackingEvent&&a.lastTrackingEvent.refTouchpoint&&(a.lastTrackingEvent.refTouchpoint.name=decodeURISafe(a.lastTrackingEvent.refTouchpoint.name))):a.lastTrackingEvent.createdAt="-";a.lastTouchpoint.name=
decodeURI(a.lastTouchpoint.name);return a},loadProfileListByFilter=function(a,d,c,b,e,l){var n=[{data:"id"},{data:"firstName"},{data:"primaryEmail"},{data:"primaryPhone"},{data:"lastTouchpoint"},{data:"dataQualityScore"},{data:"totalLeadScore"},{data:"totalCLV"},{data:"updatedAt"},{data:"status"}],h=getUserSession();return h?$(b).DataTable({lengthMenu:[[30,50,60],[30,50,60]],processing:!0,serverSide:!0,searching:!1,ordering:!0,serverMethod:"POST",ajax:{url:baseLeoAdminUrl+"/cdp/profiles/filter",contentType:"application/json",
beforeSend:function(f){$(c).show();$(d).hide();f.setRequestHeader("leouss",h)},data:function(f){f=e(f);f.order.map(function(g){g.field=n[g.column]?n[g.column].data:""});return JSON.stringify(f)},dataSrc:function(f){var g=f.canInsertData,m=f.canEditData,q=f.canDeleteData;$(b).data("canInsertData",g);$(b).data("canEditData",m);$(b).data("canDeleteData",q);"function"===typeof l&&l(f);$(c).hide();$(d).show();return f.data}},columnDefs:[{render:function(f,g,m){g="";"function"===typeof window[a]&&(g=getTableRowCheckedBox(a,
b,f,!1));return g},targets:0,orderable:!1},{render:function(f,g,m){f="Web Visitor";g="datatable_text no_contact";if(0<m.firstName.length||0<m.lastName.length)f=textTruncate(m.firstName+" "+m.lastName,30),g="has_contact";return'\x3ca class\x3d"'+g+'" title\x3d"Profile Report" href\x3d"#calljs-leoCdpRouter(\'Customer_Profile_Info\',\''+(m.id+"')\" \x3e")+f+"\x3c/a\x3e"},targets:1,orderable:!1},{render:function(f,g,m){return"string"===typeof f?'\x3cdiv class\x3d"datatable_text "\x3e\x3ca title\x3d"'+
(f+"\" href\x3d\"#calljs-leoCdpRouter('Customer_Profile_Info','"+(m.id+"')\" \x3e")+textTruncate(f,30)+"\x3c/a\x3e\x3c/div\x3e"):"-"},targets:2,orderable:!1},{render:function(f,g,m){return"string"===typeof f?'\x3cdiv class\x3d"datatable_text"\x3e\x3ca title\x3d"'+(f+"\" href\x3d\"#calljs-leoCdpRouter('Customer_Profile_Info','"+(m.id+"')\" \x3e")+textTruncate(f,30)+"\x3c/a\x3e\x3c/div\x3e"):"-"},targets:3,orderable:!1},{render:function(f,g,m){"object"!==typeof m.lastTouchpoint&&(m.lastTouchpoint={name:"No data"});
return'\x3cdiv style\x3d"font-size:11.4px;" title\x3d"'+m.lastTouchpoint.name+'"\x3e'+textTruncate(m.lastTouchpoint.name,50)+"\x3c/div\x3e"},targets:4,orderable:!1},{render:function(f,g,m){g=(new Number(f)).toLocaleString();return 100>=f?'\x3cdiv class\x3d"datatable_text text-center"\x3e'+g+" \x3c/div\x3e":100<f&&250>f?'\x3cdiv class\x3d"highlight_text text-center profile_medium_score" \x3e'+g+"\x3c/div\x3e":'\x3cdiv class\x3d"highlight_text text-center profile_high_score"  \x3e'+g+"\x3c/div\x3e"},
targets:5},{render:function(f,g,m){g=(new Number(f)).toLocaleString();return 20>f?'\x3cdiv class\x3d"datatable_text text-center"\x3e'+g+" \x3c/div\x3e":20<=f&&100>f?'\x3cdiv class\x3d"highlight_text text-center profile_medium_score" \x3e'+g+"\x3c/div\x3e":100<=f?'\x3cdiv class\x3d"highlight_text text-center profile_high_score" \x3e'+g+"\x3c/div\x3e":'\x3cdiv class\x3d"highlight_text text-center" style\x3d"color:#404040!important;font-size:0.8em!important" \x3e'+g+" \x3c/div\x3e"},targets:6},{render:function(f,
g,m){g=(new Number(f)).toLocaleString();return 20>f?'\x3cdiv class\x3d"datatable_text text-center"\x3e'+g+" \x3c/div\x3e":20<=f&&100>f?'\x3cdiv class\x3d"highlight_text text-center profile_medium_score" \x3e'+g+"\x3c/div\x3e":100<=f?'\x3cdiv class\x3d"highlight_text text-center profile_high_score" \x3e'+g+" \x3c/div\x3e":'\x3cdiv class\x3d"highlight_text text-center" style\x3d"color:#404040!important;font-size:0.8em!important" \x3e'+g+" \x3c/div\x3e"},targets:7},{render:function(f,g,m){return f?'\x3cdiv class\x3d"small text-center" style\x3d"color:#3300ff;width:74px" \x3e'+
moment.utc(f).local().format("YYYY-MM-DD HH:mm:ss")+"\x3c/div\x3e":"-"},targets:8},{render:function(f,g,m){g="ACTIVE";0===f?g="INACTIVE":-1===f?g="INVALID":-4===f&&(g="REMOVED");return'\x3cdiv class\x3d"small text-center" style\x3d"color:#3300ff!important" title\x3d"The profile status is '+g+'"\x3e'+g+"\x3c/div\x3e"},targets:9},{render:function(f,g,m){f='\x3ca class\x3d"control" title\x3d"Profile Report" href\x3d"#calljs-leoCdpRouter(\'Customer_Profile_Info\',\''+(m.id+'\')" \x3e \x3ci class\x3d"fa fa-info-circle" aria-hidden\x3d"true"\x3e\x3c/i\x3e View\x3c/a\x3e');
$(b).data("canEditData")&&(f+=' \x3cbr\x3e\x3ca class\x3d"control" title\x3d"Profile Editor" href\x3d"#calljs-leoCdpRouter(\'Customer_Profile_Editor\',\''+(m.id+'\')" \x3e \x3ci class\x3d"fa fa-pencil-square-o" aria-hidden\x3d"true"\x3e\x3c/i\x3e Edit\x3c/a\x3e'));return f},targets:10}],columns:n,order:[[8,"desc"]]}):!1};