'use strict';var dataServiceStatusReadyHtml='\x3ci class\x3d"fa fa-check-square" aria-hidden\x3d"true" style\x3d"font-size:1.1em"\x3e\x3c/i\x3e The service is active',dataServiceMap={},renderDataService=function(a){var b=$("#data_services_holder").empty().show();dataServiceMap={};_.forEach(a,function(c,e){e=c.id;dataServiceMap[e]=c;var d=!1;c.configs.service_api_key&&""!=c.configs.service_api_key?(c.service_api_key=c.configs.service_api_key.substr(0,5)+"...",d=!0):c.service_api_key="";var f=_.template($("#tpl_data_service_view").html());
b.append(f(c));b.find("i.config_description").tooltip();d&&$("#service_box_"+e).addClass("active_service_box");1===c.status&&(d=dataServiceStatusReadyHtml,null!=c.startedAt&&(d+=" and working "),$("#"+e+"_api_key_label").html(d).addClass("config_ready"))});$("#services_tooltip").tooltip()},dataServiceLoader=function(a,b,c,e,d,f,g,h){a={keywords:a,filterServiceValue:b,startIndex:f,numberResult:g};a.forPersonalization=c;a.forDataEnrichment=e;a.forSynchronization=d;LeoAdminApiUtil.getSecuredData("/cdp/data-service/list",
a,function(k){"function"===typeof h&&"object"===typeof k.data&&h(k.data)})},loadDataServices=function(a,b){$("#data_services_pagination").empty();$("#data_services_loader").show();$("#data_services_holder").hide();$("#filter_data_services_keywords").on("keyup",function(f){13===f.keyCode&&loadAllDataServices()});var c=!0,e=!0,d=!0;"active_for_personalization"===b?d=e=!1:"active_for_enrichment"===b?d=c=!1:"active_for_synchronization"===b&&(c=e=!1);dataServiceLoader(a,b,c,e,d,0,1E4,function(f){$("#data_services_loader").hide();
0<f.length?$("#data_services_pagination").pagination({dataSource:f,className:"paginationjs paginationjs-big",pageSize:6,callback:function(g,h){renderDataService(g)},beforePageOnClick:function(){}}):$("#data_services_holder").show().html('\x3cdiv class\x3d"col-lg-12 row highlight_text"\x3e \x3ch4 style\x3d"text-align: center;" \x3eNo data available !\x3c/h4\x3e \x3c/div\x3e')})};
function resetDataServiceFilter(){$("#filter_data_services_keywords").val("");$("#select_filter_data_services").val("all");loadAllDataServices()}function loadAllDataServices(){var a=$("#filter_data_services_keywords").val(),b=$("#select_filter_data_services").val();loadDataServices(a,b)}
function saveDataServiceInfo(a){a=$(a).data("id");var b=dataServiceMap[a];b.name=$("#dataServiceName").val().trim();b.description=$("#dataServiceDescription").val().trim();b.forDataEnrichment=$("#forDataEnrichment").prop("checked");b.forPersonalization=$("#forPersonalization").prop("checked");b.forSynchronization=$("#forSynchronization").prop("checked");var c=b.configs||{};$("#dataServiceConfigList input").each(function(){var d=$(this).attr("name"),f=$(this).attr("type");c[d]="number"===f?parseInt($(this).val()):
"checkbox"===f?$(this).prop("checked"):$(this).val()});b.configs=c;b.status=b.configs.service_api_key&&""!=b.configs.service_api_key?1:0;if(""===b.name)notifyErrorMessage("Service name is empty, please enter a name");else{a={objectJson:JSON.stringify(b)};var e=function(d){null!=d?(notifySavedOK("Activation Data Service",'The data of "\x3cb\x3e'+b.name+'\x3c/b\x3e" has been saved successfully'),$("#dialogSetDataServiceInfo").modal("hide"),loadDataServices()):console.error("saveDataServiceInfo ",d)};
LeoAdminApiUtil.callPostAdminApi("/cdp/data-service/save",a,function(d){0===d.httpCode&&""===d.errorMessage?e(d.data):LeoAdminApiUtil.logErrorPayload(d)},e)}}function newDataService(){LeoAdminApiUtil.getSecuredData("/cdp/data-service/get",{dataServiceName:"",dataServiceId:""},function(a){a=a.data;showDataServiceDialog(a);dataServiceMap[a.id]=a})}
function loadDataService(a){var b=dataServiceMap[a];"object"===typeof b?showDataServiceDialog(b):notifyErrorMessage("Can not load data for service: "+a)}
function resetDataService(a){var b=function(e){$("#"+e+"_api_key").val("");$("#"+e+"_api_url").val("");var d=dataServiceMap[e];_.forOwn(d.configs,function(g,h){d.configs.service_api_url="";d.configs.service_api_key="";d.startedAt=null});d.status=0;var f=function(g){null!=g?(iziToast.success({title:"Data Service",message:"The config of \x3cb\x3e"+d.name+"\x3c/b\x3e is reset OK!",timeout:3E3}),loadDataServices()):console.error("resetDataService ",g)};e={objectJson:JSON.stringify(d)};LeoAdminApiUtil.callPostAdminApi("/cdp/data-service/save",
e,function(g){0===g.httpCode&&""===g.errorMessage?f(g.data):LeoAdminApiUtil.logErrorPayload(g)},f)};$("#delete_callback").val("");$("#confirmDeleteDialog").modal({focus:!0});if(a){var c="resetDataService_"+a;window[c]=function(){b(a)};$("#delete_callback").val(c);$("#deletedInfoTitle").text("Service ID: "+a).show();$("#deletedInfoMsg").text("Do you want to reset API Key and API URL of data service permanently?")}}
function deleteDataService(a){$("#delete_callback").val("");$("#confirmDeleteDialog").modal({focus:!0});if(a){var b="deleteDataService_"+a;window[b]=function(){LeoAdminApiUtil.callPostAdminApi("/cdp/data-service/delete",{dataServiceId:a},function(c){0===c.httpCode&&""===c.errorMessage?c.data===a?(iziToast.success({title:"Data Service",message:"The service \x3cb\x3e"+a+"\x3c/b\x3e is successfully deleted!",timeout:3E3}),loadDataServices()):console.error("deleteDataService ",c):LeoAdminApiUtil.logErrorPayload(c)})};
$("#delete_callback").val(b);$("#deletedInfoTitle").text("Service ID: "+a).show();$("#deletedInfoMsg").text("Do you want to delete the selected service permanently?")}}
function showDataServiceDialog(a){if("string"!==typeof a.id)notifyErrorMessage("Invalid data service: "+a);else{$("#dialogSetDataServiceInfo").modal({backdrop:"static",keyboard:!1});var b=a.id;$("#dataServiceSaveButton").data("id",b);$("#dataServiceName").val(a.name);$("#dataServiceDescription").val(a.description);$("#dataServiceBuiltIn").prop("checked",a.builtInService);$("#forPersonalization").prop("checked",a.forPersonalization);$("#forDataEnrichment").prop("checked",a.forDataEnrichment);$("#forSynchronization").prop("checked",
a.forSynchronization);var c=$("#dataServiceConfigList");c.empty();_.forOwn(a.configs,function(e,d){var f={inputName:d};f.inputType="number"===typeof e?"number":"boolean"===typeof e?"checkbox":"text";var g=_.template($("#tpl_config_row_item").html());c.append(g(f));"checkbox"===f.inputType?c.find('input[name\x3d"'+d+'"]').prop("checked",e):c.find('input[name\x3d"'+d+'"]').val(e)})}};